### ISSUE TITLE
Get referenced asset URLs

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#1]
A page may wish to use it's own script loader (like LABjs, head.js or require.js). So instead of rendering script elements, allow the page to get the list of asset URLs.

`@Html.ScriptUrls()` ?

**Comment by MarkBorcherding** [comment]
What about allowing allowing those delivery options as part of Cassette? Could I specify separate script tags, modular combined script tags or head.js? Could Cassette spit out the resources for head.js with the cache buster?

**Comment by andrewdavey** [comment]
That could be an interesting feature.
I do want to open up extension points to make Cassette more customisable by the consuming web application. The choice of HTML element rendering strategy could be one of them.

**Comment by andrewdavey** [comment]
I've added these methods:  `@Assets.Scripts.Urls()` and `@Assets.Styles.Urls()`

**Comment by andrewdavey** [comment]
I'll create a new issue for more direct script loader support.
