### ISSUE TITLE
How to render some scripts in the <HEAD> and other scripts just befor the enfing </BODY> tag?

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#10]
To improve webpage performance it is advisable to render included scripts at the bottom of the page.
However, some script libraries don't work correctly when loaded too late; they need to be included from within the <head> tag (like modernizr.js).

Is this already possible? If so, where can I find documentation?

**Comment by andrewdavey** [comment]
I've added this wiki page to explain: https://github.com/andrewdavey/cassette/wiki/Page-Script-Locations

**Comment by sfmskywalker** [comment]
Nice,cleand & easy. Thanks!
