### ISSUE TITLE
.less file returns HTTP 500 but does not throw exception

### ISSUE THREAD

**Issue by kekonn** [andrewdavey/cassette#100]
I have a .less file in ~/Content and reference it as such: `Bundles.Reference("Content/App.less");` When the browser requests it, the server (I'm using IIS Express) returns a 500 status code but no exception is thrown.

**Comment by andrewdavey** [comment]
Is any useful information included in the response body?

Can you paste in the .less file here?

**Comment by kekonn** [comment]
Headers:

<pre>Request URL:http://localhost:1290/_cassette/asset/Content/App.less?38de74bb8f5e2dd6b1b3d406cfbc49b1d15d76c6
Request Method:GET
Status Code:500 Internal Server Error

Request Headers
Accept:text/css,*/*;q=0.1
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Host:localhost:1290
Referer:http://localhost:1290/Signup/Step1
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.121 Safari/535.2

Query String Parameters
38de74bb8f5e2dd6b1b3d406cfbc49b1d15d76c6:

Response Headers
Cache-Control:private
Content-Length:6109
Content-Type:text/html; charset=utf-8
Date:Wed, 23 Nov 2011 07:14:36 GMT
Server:Microsoft-IIS/7.5
X-AspNet-Version:4.0.30319
X-Powered-By:ASP.NET
X-SourceFiles:=?UTF-8?B?QzpcdG1wXGFkZGljdFxUaW1CYXJ0Sm9uYXNDVlxSZWFsRG9sbWVuLkFjYWRkZW1pY3QuQ1ZcUmVhbERvbG1lbi5BY2FkZGVtaWN0LkNWLldlYlxfY2Fzc2V0dGVcYXNzZXRcQ29udGVudFxBcHAubGVzcw==?=
</pre>


LESS file: 

<pre>@import "themes/blitzer/jquery-ui-1.8.16.custom.css";
@import "Site.css";

fieldset {
    legend {
        .ui-widget;
    }
}
</pre>


Not sure about the imports, they are according to the less documentation and the problem existed without imports as well.

**Comment by andrewdavey** [comment]
What about the response body? The content length is 6109 bytes, so I'm guessing there is something like an error in there.

**Comment by kekonn** [comment]
Couldn't get it out of chrome so I just navigated to the url itself and got this from ASP:

<pre>
Server Error in '/' Application.

Unsupported object type.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Unsupported object type.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[InvalidOperationException: Unsupported object type.]
   Jurassic.TypeUtilities.TypeOf(Object obj) +399
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +14464
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +121
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +383
   Cassette.Stylesheets.CompileResult.CallLateBound(Object thisObject, Object[] argumentValues) +203
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +17331
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +121
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +383
   Cassette.Stylesheets.LessCompiler.CompileImpl(String lessSource, IFile file) +280

[LessCompileException: Less compile error in ~/Content/App.less.]
   Cassette.Stylesheets.LessCompiler.CompileImpl(String lessSource, IFile file) +614
   Cassette.Stylesheets.LessCompiler.Compile(String lessSource, IFile sourceFile) +111
   Cassette.BundleProcessing.<>c__DisplayClass1.<Transform>b__0() +158
   Cassette.Stylesheets.ExpandCssUrlsAssetTransformer.ReadCss(Func`1 openSourceStream) +64
   Cassette.Stylesheets.<>c__DisplayClass1.<Transform>b__0() +98
   Cassette.AssetBase.OpenStream() +166
   Cassette.Web.AssetRequestHandler.SendAsset(HttpRequestBase request, HttpResponseBase response, Bundle bundle, IAsset asset) +295
   Cassette.Web.AssetRequestHandler.ProcessRequest(HttpContext _) +426
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +116
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.17020</pre>

**Comment by andrewdavey** [comment]
Thanks - it's a shame that Jurassic doesn't provide very friendly errors! :)
I'll try to recreate the error on my machine.

Looking at your less code, you have `.ui-widget;`. If ui-widget is defined in a jquery-ui.css, does Less support using it as a mixin?

**Comment by kekonn** [comment]
I don't know. This is my first run in with Less. It's just a class. The
only thing I can think of is that it has a problem with the reference and
doesn't know the class.

On 23 November 2011 10:48, Andrew Davey <
reply@reply.github.com

**Comment by andrewdavey** [comment]
I think less mixins are a little different from regular css rules. For example:

```
.my-mixin() {
    color: red
}
```

Note the parenthesis after the mixin name. So I don't think using `.ui-widget;` from jquery-ui.css as a mixin will work for you.

Sorry the error message from the Less compiler isn't very helpful about the problem cause. I hope this can be improved at some point.

**Comment by kekonn** [comment]
In that case, is there any way I can achieve some kind of functionality. I
want to automatically apply a couple of classes to a set of elements? I
know this is beyond your scope what I'm asking so you don't have to answer
this, but this is the main reason I chose your framework because I thought
I could do this with LESS.

Thanks for all the help :)

## Jonas Van der Aa

**Comment by andrewdavey** [comment]
I don't think LESS will do what you want.
You could use jQuery to add the class to the elements during page load perhaps? `$('fieldset legend').addClass('ui-widget');`

Sorry I can't be of more help. Keep using Cassette though, it's still a great way to manage your javascript and css! :)
