### ISSUE TITLE
won't install from nuget

### ISSUE THREAD

**Issue by pilavdzic** [andrewdavey/cassette#101]
Hi Guys...

   Following the directions here:

http://getcassette.net/documentation/getting-started

I get this error:

PM> Install-Package Cassette.Web
'Cassette (≥ 0.9.1.0)' not installed. Attempting to retrieve dependency from source...
Install-Package : Unable to resolve dependency 'Cassette (≥ 0.9.1.0)'.
At line:1 char:16
- Install-Package <<<<  Cassette.Web
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

So then I tried
PM> Install-Package Cassette
for the heck of it, and that installed, but then
PM> Install-Package Cassette.Web

still gave the same error

Anyone know what this means?

Thanks!
   Enis

**Comment by andrewdavey** [comment]
Please try updating nuget first (In VS: Tools > Extension Manager > Updates).
We've had issues with older versions of nuget not handling version equality correctly.

**Comment by pilavdzic** [comment]
Thanks for the quick response and help. That was it!

**Comment by pilavdzic** [comment]
Oops, spoke too soon, I am now getting:

Server Error in '/' Application.

Reference error in "~/Scripts/jquery.unobtrusive-ajax.js", line 1. Cannot find "~/Scripts/jquery-1.4.4.js".
Reference error in "~/Scripts/jquery.validate.unobtrusive.js", line 1. Cannot find "~/Scripts/jquery-1.4.4.js".

When I compile my project. 

But I didn't add any @Bundles. or cassette things yet... 

I was hoping to continue to use my regular script tags on existing pages for now... and just use cassette in the places I intend to. I have a pretty large web app so it would be great if I could use cassette functionality where needed without having to go and change every single include everywhere first... I have a number of js includes on each page, as well as in the layout page... Right now I am using razor to do things like:

```
<link href="@Url.Content("~/Content/global.css?v="+ver)" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="@Url.Content("~/Scripts/global/jquery.min.js")" ></script>
```

all over the place. That's why I am trying to move to cassette...

**Comment by pilavdzic** [comment]
Is it required that I remove all my existing script tags from the project and make them @Bundles.Reference instead before it will work?

Here is the stack trace:
AssetReferenceException: Reference error in "~/Scripts/jquery.unobtrusive-ajax.js", line 1. Cannot find "~/Scripts/jquery-1.4.4.js".
Reference error in "~/Scripts/jquery.validate.unobtrusive.js", line 1. Cannot find "~/Scripts/jquery-1.4.4.js".]
   Cassette.BundleContainer.ValidateAssetReferences() +579
   Cassette.BundleContainer..ctor(IEnumerable`1 bundles) +87
   Cassette.Configuration.BundleContainerFactory.Create(IEnumerable`1 unprocessedBundles, CassetteSettings settings) +140
   Cassette.CassetteApplicationBase.CreateBundleContainer(IEnumerable`1 bundles, CassetteSettings settings, String cacheVersion) +186
   Cassette.CassetteApplicationBase..ctor(IEnumerable`1 bundles, CassetteSettings settings, String cacheVersion) +68
   Cassette.Web.CassetteApplication..ctor(IEnumerable`1 bundles, CassetteSettings settings, CassetteRouting routing, Func`1 getCurrentHttpContext, String cacheVersion) +43
   Cassette.Web.StartUp.CreateCassetteApplication() +1040
   Cassette.CassetteApplicationContainer`1.CreateApplication() +106
   System.Lazy`1.CreateValue() +361
   System.Lazy`1.LazyInitValue() +104
   System.Lazy`1.get_Value() +89
   Cassette.CassetteApplicationContainer`1.get_Application() +35
   Cassette.Web.StartUp.<PostApplicationStart>b__0() +31
   Cassette.Web.CassetteHttpModule.HttpApplicationPostMapRequestHandler(Object sender, EventArgs e) +126
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

All I did was add the package - the app ran just fine previously. I can see that the error is caused by cassette and I can guess why (things are not set up exactly like cassette wants) however... I didn't ask cassette to do anything yet. Is there some default the causes it to try and do something before any of it's functions have been called? Can I turn that off?

**Comment by andrewdavey** [comment]
Open "~/Scripts/jquery.unobtrusive-ajax.js" and check line 1
Is it referencing jquery-1.4.4.js and does your project actually have a newer version of jquery instead?
If so, update the reference to the correct version.

The same applies to jquery.validation.unobtrusive.js

**Comment by pilavdzic** [comment]
You are correct again, jquery.unobtrusive references a jquery version I am not using in a path that doesn't exist.

But... here's the kicker.. I have no idea why anything is looking at that file, it isn't referenced by anything anywhere. Perhaps just because it is in the scripts directory? 

I moved to to /scripts/old2 instead. Also, in my layout file I comment out my old way of doing stuff and moved to:

  @Bundles.RenderScripts()
    @Bundles.Reference("Content/global.css")
    @Bundles.Reference("Content/layout.css")
    @Bundles.Reference("Content/tables.css")
    @Bundles.Reference("Content/narratives.css")
    @Bundles.Reference("Content/ui-smoothness/jquery-ui-1.8.14.custom.css")
    @Bundles.Reference("Content/jquery.nucombo.css")
    @Bundles.Reference("Content/fileuploader.css")
    @Bundles.Reference("Content/functionality.css")

```
@Bundles.Reference("Scripts/global/jquery.min.js")
@Bundles.Reference("Scripts/global/underscore-min.js")
@Bundles.Reference("Scripts/global/jquery-ui-1.8.16.custom.min.js")

@Bundles.Reference("Scripts/global/jquery.tmpl.min.js")
@Bundles.Reference("Scripts/global/jquery.validate.js")
@Bundles.Reference("Scripts/global/knockout-1.3.0beta.js")
@Bundles.Reference("Scripts/global/knockout.mapping-latest.js")

@Bundles.Reference("Scripts/jquery.ui.knockout.binding.js")
@Bundles.Reference("Scripts/jquery.nucombo.js")
@Bundles.Reference("Scripts/global/globals.js")
@Bundles.Reference("Scripts/global/CustomBindings.js")
@Bundles.Reference("Scripts/global/functions.js")
@Bundles.Reference("Scripts/global/date.js")
@Bundles.Reference("Scripts/global/fileuploader.js")
@Bundles.Reference("Scripts/global/history.js")

<!--link href="@Url.Content("~/Content/global.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/layout.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/tables.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/narratives.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/document.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/ui-smoothness/jquery-ui-1.8.14.custom.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/jquery.nucombo.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/fileuploader.css?v=" + ver)" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/functionality.css?v=" + ver)" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="@Url.Content("~/Scripts/global/jquery.min.js")" ></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/global/underscore-min.js")" ></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/global/jquery-ui-1.8.16.custom.min.js")"></script>

<script src="@Url.Content("~/Scripts/global/jquery.tmpl.min.js")" type="text/javascript"></script>   
<script src="@Url.Content("~/Scripts/global/jquery.validate.js")" type = "text/javascript"></script>  
<script src="@Url.Content("~/Scripts/global/knockout-1.3.0beta.js")" type = "text/javascript"></script> 
<script src="@Url.Content("~/Scripts/global/knockout.mapping-latest.js")" type = "text/javascript"></script>

@* knockout custom binding for using jquery UI, see https://groups.google.com/d/topic/knockoutjs/dtXftC1Ncgg/discussion *@
<script src="@Url.Content("~/Scripts/jquery.ui.knockout.binding.js")" type="text/javascript"></script> 
<script src="@Url.Content("~/Scripts/jquery.nucombo.js?v=" + ver)" type='text/javascript'></script>
 <script src="@Url.Content("~/Scripts/global/globals.js?v=" + ver)" type='text/javascript'></script>
```

<script src="@Url.Content("~/Scripts/global/CustomBindings.js?v=" + ver)" type='text/javascript'></script>

```
<script src="@Url.Content("~/Scripts/global/functions.js?v=" + ver)" type='text/javascript'></script>
<script src="@Url.Content("~/Scripts/global/date.js?v=" + ver)" type='text/javascript'></script>
<script src="@Url.Content("~/Scripts/global/fileuploader.js?v=" + ver)" type='text/javascript'></script>
<!--script src="@Url.Content("~/Scripts/global/history.js?v=" + ver)" type='text/javascript'></script-->

 @RenderSection("JavaScript", required: false) 
```

but I still get:

Server Error in '/' Application.

Reference error in "~/Scripts/old2/jquery.unobtrusive-ajax.js", line 1. Cannot find "~/Scripts/old2/jquery-1.4.4.js".
Reference error in "~/Scripts/old2/jquery.validate.unobtrusive.js", line 1. Cannot find "~/Scripts/old2/jquery-1.4.4.js".

Ideas?

**Comment by andrewdavey** [comment]
Look at the `CassetteConfiguration.cs` file (added to your project by the nuget package). It probably has a default setting that is creating a bundle for each script file. On application start-up, the configuration class is executed. So any errors, such as missing/incorrect references, will cause an exception.

**Comment by pilavdzic** [comment]
I don't get how/why is it finding that file... old2 is new directory I just created and put old scripts I am no longer using into it, so I know nothing can possibly be referencing it. I even excluded it from the project, but I get the same error.

**Comment by pilavdzic** [comment]
I deleted the file altogether. Now it just said the same thing about the next one. It's like cassette searches the filesystem for .js files and attempts to include them all by default, regardless of if that makes any sense or not... What am I missing here?

**Comment by andrewdavey** [comment]
By default, Cassette is searching the file system, from `~/Scripts/`, for `*.js` files. The search is recursive by default, so still finds your `old2` directory.

Cassette searches for and builds all the bundles during _application start-up_. This is totally separate from the `Bundle.Reference` calls in a view.

**Comment by andrewdavey** [comment]
Have you read:
http://getcassette.net/documentation/configuration
http://getcassette.net/documentation/configuration/add-directory
http://getcassette.net/documentation/configuration/add-per-sub-directory
?

**Comment by pilavdzic** [comment]
Sorry for asking so many questions in a bug report, but at the moment I have js files that should only be included on certain pages (and not others)... is that possible?

This is all probably just me doing something wrong, but I think the package defaults could use some tweaks. Regardless of why it is doing it - it isn't untuitive to install a package and have it include all your js files from all over the filesystem..

It isn't clear from the docs if it is supposed to do this. I understood that all files in
/scripts/somedir 
will be included once a file in that directory is referenced using @Bundles.reference to form a package.
But what about
/scripts/dontincludeme
which has no files in it that are referenced by anything?

**Comment by pilavdzic** [comment]
Disregard my previous comment. Didn't see your reply. Thanks, I'll read more.
