### ISSUE TITLE
'External' bundle no longer works if the URL is local

### ISSUE THREAD

**Issue by barclayadam** [andrewdavey/cassette#102]
Andrew,

After upgrading to 0.9.2 I have that the use of local external references no longer works due to the check for IsUrl() in src/Cassette/Scripts/ExternalScriptBundle.cs (ln 52).

We have a JS file that is generated on the fly from the server which we want to manage as if it was external. Prior to upgrading I was able to add an external module using a local path (e.g. './myFIle.js') which worked fine.

Can this be reverted to allow relative URLs again.

Thanks,
Adam

**Comment by andrewdavey** [comment]
I'll look into removing the constructor constraint requiring a URL. I don't think it adversely affects other code - just need to check...

It would interesting to know more about your use case as well. Are you able to tell me more about the kind of JS you're generating? I'm guessing you've got a controller action returning the JS?

**Comment by barclayadam** [comment]
Yeah that bis correct. The JS we are generating contains definitions of commands (in the CQRS sense) that have been developed on the server, to include things such as validation details that can be automatically applied on the client-side.

There is probably a better way to do it (e.g. use T4 templates, post-build step or something similar) to get compile-time output but for now the simple case of using Razor / MVC has been working well.

**Comment by andrewdavey** [comment]
It might be possible to implement Cassette's `IAsset` interface in a class that provides your generated script. This asset could then be contained within a `ScriptBundle` and fit into the rest of Cassette's bundle referencing and rendering system. You'd gain all the minification and caching benefits of Cassette.

I'm planning an article discussing interesting extensions to Cassette. This kind of dynamic asset generation will be a great use case to demonstrate.

However, the simplest solution is often the best. So it's probably best stick with what you've got for now. I'll get Cassette updated to allow local URLs.

**Comment by barclayadam** [comment]
For now at least we are happy with just using an external bundle, although of course we do want to find a better way of doing this going forward.

Never even thought about doing direct integration with Cassette as you described to be honest, I was going to investigate compile-time methods of generating the JS (as above, T4 or similar) as we definitively want the other benefits such as minification and caching.

The thing that will need consideration if you do go down the route of creating an article based on this use case would be the best way to integrate a templating solution, don't want to be creating JavaScript all in code. Would be interested in seeing what comes out of this, as it means I'll be able to do a little less thinking when it comes to migrating our current implementation to something better ;)

**Comment by andrewdavey** [comment]
Good point - concatenating script strings together is awful!
It should be simple enough to call into the MVC view engine to render a view that generates the script content. I'll keep you posted :)

**Comment by andrewdavey** [comment]
v0.9.4 is in now nuget
