### ISSUE TITLE
PlaceholderReplacingResponseFilter - Output is missing the "</html>" tag

### ISSUE THREAD

**Issue by barclayadam** [andrewdavey/cassette#103]
Andrew,

Another breaking change when upgrading to 0.9.2, this time regarding the PlaceholderReplacingResponseFilter.

We load templates via AJAX which do not contain the HTML tag (e.g. just a portion of the application). This causes the above mentioned filter to throw an exception at src/Cassette.Web/PlaceholderReplacingResponseFilter.cs (ln 82). 

Not sure exactly what the reasoning is but the problem is the check on line 66 (if (!html.Contains("</html>")) return;) which then does not set the hasWrittenToOutputStream variable to true.

Thanks,
Adam

**Comment by kekonn** [comment]
I am seeing this issue as well. It occurs when I return a PartialView.

Code returning the view:

<pre> [HttpPost]
        public ActionResult Experience(ExperienceViewModel experience)
        {
            if (ModelState.IsValid)
            {
                List<ExperienceViewModel> experiences = (List<ExperienceViewModel>)Session["Step2"] ??
                                                        new List<ExperienceViewModel>();
                experiences.Add(experience);
                Session["Step2"] = experiences;

                return PartialView("DisplayTemplates/ExperienceViewModel", experience);
            }
            if (!Request.IsAjaxRequest())
                return PartialView("EditorTemplates/ExperienceViewModel", experience);

            throw new Exception("Disregard this");
        }
</pre>


Error shown by IIS:

<pre><span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Output is missing the &quot;&lt;/html&gt;&quot; tag.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.InvalidOperationException: Output is missing the &quot;&lt;/html&gt;&quot; tag.<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[InvalidOperationException: Output is missing the &quot;&lt;/html&gt;&quot; tag.]
   Cassette.Web.PlaceholderReplacingResponseFilter.Close() +123
   System.Web.HttpWriter.FilterIntegrated(Boolean finalFiltering, IIS7WorkerRequest wr) +173
   System.Web.HttpResponse.FilterOutput() +112
   System.Web.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +49
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +69
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.17020

            </font></pre>

**Comment by kekonn** [comment]
Update: when I disable html rewriting it returns an empty page that is missing the closing html tag.

**Comment by andrewdavey** [comment]
v0.9.3 is in nuget. It now outputs the buffered, rewritten HTML in the filter's Close method, instead of looking for `</html>`.

@bloodsplatter I'm not sure why disabling rewriting is giving you an empty page! Please create another issue with the details.

**Comment by kekonn** [comment]
Ok, I'll test this one right away and get back to you.

**Comment by kekonn** [comment]
I can't update. It says `Unable to resolve dependency 'Cassette (≥ 0.9.3.0)'.`
Also, AjaxMin has updated again.

**Comment by andrewdavey** [comment]
Hmm, seems my last push failed to connect to nuget server...
I've re-pushed. Try it again now.

**Comment by kekonn** [comment]
So far it seems to work.

EDIT: it's fixed but I can't close the issue.
