### ISSUE TITLE
Minification introduces errors somehow

### ISSUE THREAD

**Issue by pilavdzic** [andrewdavey/cassette#106]
Hi. I am new to cassette but I think I finally have everything working, except when I Change web.config to debug=false I get js errors. The js generated isn't the same as in debug mode somehow, because it all works fine in debug.

I have a CSS bundle and a js bundle.  Is there a way to upload files here so I can submit my example?

I am not sure it all runs under jslint without errors, but it is valid code that works fine when files are added separately. I'll run jslint on it now and correct that.

Any strategies I can use to try to debug? Everything is on one line so I am not sure how to debug it.

Thanks,
   Enis

**Comment by pilavdzic** [comment]
P.S. might want to take down this page, it was confusing because it is out of date and not how current version works.

Took me a bit to figure out that this info is wrong. Was modifying my web config with this stuff and getting errors etc until I read the upgrading to new version page, only then was it clear.
https://github.com/andrewdavey/cassette/wiki/Configuration

Also might be useful to explicitly state in docs somewhere that cassette compiles all bundles even if they are not in use. This isnt intuitive and was not clear to me after reading docs until someone posted on here and explained it to me.

**Comment by andrewdavey** [comment]
In Chrome, load the development tools and go the scripts tab. Select your script then click the "{ }" button near the bottom left. This will attempt pretty-print the code making it easier to find the error.

Common minification errors include:
- Missing semi-colon at end of file
- Creating a global name that isn't referenced elsewhere in the file, means it gets shortened. The another file trying to use that name then fails. e.g.

```
// file1.js
window.example = 42;

// file2.js
alert(window.example);
```

Could minify into:

```
// file1.js
window.a = 42;

// file2.js
alert(window.example);
```

The fix is to use strings when defining the global.

```
// file1.js
window["example"] = 42;

// file2.js
alert(window.example);
```

**Comment by pilavdzic** [comment]
Thanks for the tip I will do this and let you know if I find the error.

**Comment by andrewdavey** [comment]
Thanks reminding me about the wiki - I've switched it off now. http://getcassette.net/documentation is place to look for docs. I'll try to get more up there soon!

**Comment by robertdean** [comment]
Same error here. Is there a way to disable minifcation?

**Comment by pilavdzic** [comment]
The suggestions above worked for me, but it pains pain to go through all my js. A more robust minification that correctly handles those cases would ideal. You can set debug=true in your prod web config and that will disable minification.

**Comment by robertdean** [comment]
Agreed. Thanks for the tip.
