### ISSUE TITLE
HttpContext Items and Server.Transfer

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#107]
Need to investigate use of HttpContext.Items when Server.Transfer is used to invoke another URL. Cassette is storing things in the Items collection so could be affected.

**Comment by peirix** [comment]
I'm having issues with this now. When I'm using Server.Transfer I'm only getting a GUID, or something like that, as output from Bundles.RenderScript() and Bundles.RenderStylesheet()

**Comment by andrewdavey** [comment]
Okay we'll need to investigate this.
