### ISSUE TITLE
Custom pipeline causing intermittent error

### ISSUE THREAD

**Issue by tomdenny** [andrewdavey/cassette#108]
I'm trying to create a bundle in version 0.9.5 where the assets are always concatenated regardless if I'm in release mode or debug mode.  I'd like to conditionally load this particular bundle asynchronously using yepnope.js & Bundles.Url.  Can you spot what's going wrong here?  

I've attempted this using two different methods but both methods give me a 500 internal error/exception intermittently.

**Method1:  Custom ScriptPipeline class derived from ScriptPipeline.**
The Bundle Processor is replaced during configuration with my custom class.  The interesting tidbit in my custom class is:

<pre><code>
protected override IEnumerable&lt;IBundleProcessor&lt;ScriptBundle>> CreatePipeline(ScriptBundle bundle, CassetteSettings settings)
{
            foreach( IBundleProcessor&lt;ScriptBundle> p in base.CreatePipeline( bundle, settings ) ) {
                yield return p;
                if( settings.IsDebuggingEnabled && _concatenateOverride && p.GetType() == typeof( SortAssetsByDependency ) )
                    yield return new ConcatenateAssets();
            }
}
</code></pre>

**Method2: Modify pipeline when creating the bundle.**  

```c#
        private static void AddConcatenateAssets(ScriptBundle bundle)
        {
            ((Cassette.BundleProcessing.MutablePipeline<ScriptBundle>)bundle.Processor)
                .InsertAfter<Cassette.BundleProcessing.SortAssetsByDependency>(new ConcatenateAssets());
        }
```
...

```c#
            Action<ScriptBundle> concatePipeline = (settings.IsDebuggingEnabled ? (Action<ScriptBundle>)AddConcatenateAssets : null);
            bundles.Add<ScriptBundle>("scripts/shim",
                topLevelScriptSearch,
                concatePipeline);
```

Exception:
<pre>
[ObjectDisposedException: Cannot access a closed Stream.]
   System.IO.__Error.StreamIsClosed() +57
   System.IO.MemoryStream.set_Position(Int64 value) +9629708
   Cassette.BundleProcessing.ConcatenatedAsset.OpenStreamCore() +79
   Cassette.AssetBase.OpenStream() +148
   Cassette.Bundle.OpenStream() +64
   Cassette.Web.BundleRequestHandler`1.SendBundle(Bundle bundle, String actualETag) +223
   Cassette.Web.BundleRequestHandler`1.ProcessRequest() +374
   Cassette.Web.BundleRequestHandler`1.System.Web.IHttpHandler.ProcessRequest(HttpContext unused) +34
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +100
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75
</pre>

**Comment by andrewdavey** [comment]
The intermittent nature of the error is very concerning! When in debug mode Cassette detects file changes and re-builds the bundle container. This means disposing the previous bundles and assets. `ConcatenatedAsset.Dispose` disposes its `stream` which I guess is why you're seeing the exception.

This must be some kind of race condition, where the browser issues simultaneous requests for bundles. I will investigate.

**Comment by tomdenny** [comment]
That makes perfect sense although I don't think it's a race condition.  Intermittent might have been the wrong term.  Once I get the exception I seem to continue to get the exception for a while.  I assume when the app-pool is restarted it fixes the problem.

I suspect the issue might be that the routes reference the old bundle collection and not the new one created by instantiating a new application.  The filewatcher disposes the existing bundles and then creates a new application.  But the new application doesn't appear to update the routes.

In StartUp.cs CreateCassetteApplication method (called when the filewatcher notices a change) has 

<pre><code>
                if (_firstCreation)
                {
                    _firstCreation = false;
                    application.InstallRoutes(RouteTable.Routes);
                }
</code>
</pre>


InstallRoutes in turn references the BundleContainer.  Since `firstCreation == false` after the first application is created,   I think the routes still reference the first BundleContainer (with the now disposed bundle) unless the routes are being updated some other way.

Or I could be completely off.

**Comment by andrewdavey** [comment]
Ah ha! Yes that could well be the cause of the issue. Thanks for digging into the code.
I'll look into this some more.

**Comment by tomdenny** [comment]
That fixed it.  thanks
