### ISSUE TITLE
Minification of modernizr.min.js causes javascript errors

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#11]
When running in debug mode, everything works as it should, but as soon as I set debug="false" andrefresh my page, I receive a javascript error that a function is expected. Looking at the source of the error, it is caused in modernzir.min.js.
Could there be a minification issue on already minified scripts?

**Comment by andrewdavey** [comment]
Remove all the minified scripts from your project. Cassette will handle minification for you. The only scripts that belong in your repository are the full source originals.

I'd guess the error is due to the minified script not having a semi-colon at the end.

**Comment by sfmskywalker** [comment]
That worked perfectly, thanks! Yeah you're probably right about the missing semi-colon somewhere.

I'm having the same issue with CSS files (although none of them are minified). It's probably also because of a formatting error.
