### ISSUE TITLE
popups throwing errors Output is missing </html>

### ISSUE THREAD

**Issue by pilavdzic** [andrewdavey/cassette#111]
I am getting the following error. The page being displayed is not supposed to have an /html tag because it is fetched by ajax into a div on the page.

I saw a bug reported earlier similar to this and the issue was closed and fixed, but I don't understand how to update to the new version, when I installed Cassette.Web it looks like it worked fine but I obviously don't have the latest.

Any help would be appreciated.

Server Error in '/' Application.

```
Output is missing the "</html>" tag.
```

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

```
Exception Details: System.InvalidOperationException: Output is missing the "</html>" tag.
```

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

```
[InvalidOperationException: Output is missing the "</html>" tag.]
   Cassette.Web.PlaceholderReplacingResponseFilter.Close() +111
   System.Web.HttpWriter.Filter(Boolean finalFiltering) +184
   System.Web.HttpResponse.FilterOutput() +119
   System.Web.CallFilterExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +52
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.237

```

**Comment by pilavdzic** [comment]
When pasting HTML in here it seems to just ignore the rest of the message...

**Comment by andrewdavey** [comment]
Please update to the latest version of Cassette.

http://docs.nuget.org/docs/start-here/Using-the-Package-Manager-Console#Updating_a_Package

```
PM> Update-Package Cassette.Web
```

**Comment by pilavdzic** [comment]
Even though cassette was installed, I got:

PM> Update-Package Cassette.Web
Update-Package : 'Cassette.Web' was not installed in any project. Update failed.
At line:1 char:15
- Update-Package <<<<  Cassette.Web
  - CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

so then I did:
PM> Install-Package Cassette.Web
Attempting to resolve dependency 'Cassette (≥ 0.9.5.0)'.
Attempting to resolve dependency 'AjaxMin (≥ 4.37)'.
Attempting to resolve dependency 'Jurassic (≥ 2.1)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 4.0)'.
Attempting to resolve dependency 'Cassette.Views (≥ 0.9.5.0)'.
Attempting to resolve dependency 'WebActivator (≥ 1.5)'.
Attempting to resolve dependency 'Microsoft.Web.Infrastructure (≥ 1.0.0.0)'.
Successfully installed 'AjaxMin 4.37.4345.34101'.
Successfully installed 'Cassette 0.9.5'.
Successfully installed 'Cassette.Views 0.9.5'.
Successfully installed 'WebActivator 1.5'.
Successfully installed 'Cassette.Web 0.9.5'.
Successfully added 'AjaxMin 4.37.4345.34101' to UsaidInfo.
Successfully added 'Cassette 0.9.5' to UsaidInfo.
Successfully added 'Cassette.Views 0.9.5' to UsaidInfo.
Successfully added 'Cassette.Web 0.9.5' to UsaidInfo.

but I still get the same error.

So I tried updating again,and still got:
PM> Update-Package Cassette.Web
Update-Package : 'Cassette.Web' was not installed in any project. Update failed.
At line:1 char:15
- Update-Package <<<<  Cassette.Web
  - CategoryInfo          : NotSpecified: (:) [Update-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand

Not sure why it's not working...

**Comment by andrewdavey** [comment]
What version of the Cassette DLLs has your project referenced? In Solution Explorer `References`, right click `Cassette.Web` select `Properties`. What is the Version property?

**Comment by pilavdzic** [comment]
Turns out that after I did the install and update steps above a second time, my problem above is resolved (despite the error message on updating).

My version is 0.9.5.0 now, but I still get errors on trying to update. Does that mean something is still not quite working as it should?

Anyway, my problem is resolved so thanks!
