### ISSUE TITLE
Possible problem with css url("")

### ISSUE THREAD

**Issue by etishor** [andrewdavey/cassette#112]
I can't test this very well right now but it appears that cassette is not handling well the case when images in css are references with url("path/to/img.png") <- double quotes. When single quotes are used everything works fine. In my example it was the css file for kendo ui which uses double quotes for one file, and changing to single quotes adjusted the path correctly.

**Comment by andrewdavey** [comment]
This seems strange because the regex used to find CSS URLs does have support for double quotes:
https://github.com/andrewdavey/cassette/blob/master/src/Cassette/Stylesheets/ExpandCssUrlsAssetTransformer.cs#L44
and this test passes:
https://github.com/andrewdavey/cassette/blob/master/src/Cassette.UnitTests/Stylesheets/ExpandCssUrlsAssetTransformer.cs#L118

Can you create a minimal reproduction of the failing CSS? Either paste in here, or email me andrew@equin.co.uk

Thanks.

**Comment by etishor** [comment]
I've attached the file i had problems with. The problem is at ln 152 :
.k-tabstrip-items .k-item {
  background-image: url("textures/highlight.png");
}

this is from the source code of kendo UI. Changing the double quotes to
single quotes worked. I was only able to spend very limited time on this so
it might even be completely unrelated to cassette - so if double quotes are
handled ok in your tests than don't bother with this issue.

I'm sorry for not being able to provide more details but i'm in a remote
location with limited access to development resources.

Iulian

On Mon, Dec 12, 2011 at 1:44 AM, Andrew Davey <
reply@reply.github.com

**Comment by andrewdavey** [comment]
Thanks for sending me the file. The following test just passed for me:

```
[Fact]
public void Kendo()
{
    var imageFile = StubImageFile();
    SetupDirectoryGetFile(imageFile.Object);

    var css = File.ReadAllText(@"C:\Users\Andrew Davey\Downloads\kendo.default.css");
    var getResult = transformer.Transform(css.AsStream, asset.Object);
    var output = getResult().ReadToEnd();

    output.ShouldNotContain("textures/highlight.png");
}
```

So I'm unsure if Cassette is causing the problem. Are you on the most recent version of Cassette?

**Comment by andrewdavey** [comment]
Also check that the image file referenced by that URL actually exists. Missing files are currently skipped by Cassette.
