### ISSUE TITLE
Served image files dont have an ETag

### ISSUE THREAD

**Issue by gabrielrdz** [andrewdavey/cassette#113]
When Cassette serves image/raw files from the RawFileRequestHandler.cs file, those files are not receiving an ETag / Cache validator.

**Comment by andrewdavey** [comment]
The `Expires` header is set to be 'next year'. Browsers should therefore cache the files and not re-request them next time.
However, it can't hurt too much to also provide an E-Tag based on the hashed file contents.

**Comment by gabrielrdz** [comment]
I completely agree Andrew, but I think you ran into a similar problem in another scenario, where you had to also set the ETag to "help" the browser cache successfully. Reason I ran into this is running my site through Google's PageSpeed online, and just like you said, although the Expires header is there, it still was looking for an ETag.
