### ISSUE TITLE
CassetteSettings.SourceDirectory should be public?

### ISSUE THREAD

**Issue by djcsdy** [andrewdavey/cassette#116]
Is `CassetteSettings.SourceDirectory` deliberately declared `internal`?

To me it would make sense to allow users to provide their own implementations of `IDirectory` and `IFile` where desired.  For example, this could be a first step towards fixing #59.

The `IDirectory` and `IFile` interfaces are already `public`, so everything else is in place to allow this, except that there is no `public` integration point. Just changing `CassetteSettings.SourceDirectory` to be `public` should allow users to choose an `IDirectory` implementation in their implementation of `ICassetteConfiguration.Configure`.

Does this sound reasonable or have I missed something?

**Comment by andrewdavey** [comment]
I've been very strict about keeping most parts of Cassette internal to make being [SemVer](http://semver.org/) compliant easier. However, I don't mind making things public when there is a good reason. It seems fair for `SourceDirectory` to public. I'll try to get this into the next release.

**Comment by djcsdy** [comment]
(I suppose you could make the same argument about `CassetteSettings.CacheDirectory`, in case someone wants to provide their own storage solution for caching).

**Comment by djcsdy** [comment]
Cool, thanks!
