### ISSUE TITLE
Un-referenced Less files causing crash in release mode

### ISSUE THREAD

**Issue by sddaniels** [andrewdavey/cassette#117]
# Backstory

I'm trying to use the Twitter Bootstrap files to get started with a new project. Instead of using cassette to compile the less code, i'm using a different tool because these files will eventually sit on a different server and be shared by multiple apps. But for now I still have the less files in my project, although they are not referenced in any of the views.
# Problem

Everything works great in debug mode, but when I change things to release mode, it crashes with this exception:

```
[InvalidOperationException: Unsupported object type.]
   Jurassic.TypeUtilities.TypeOf(Object obj) +256
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +9236
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +37
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +86
   Cassette.Stylesheets.CompileResult.CallLateBound(Object thisObject, Object[] argumentValues) +106
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +10706
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +37
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +86
   Cassette.Stylesheets.LessCompiler.CompileImpl(String lessSource, IFile file) +216

[LessCompileException: Less compile error in ~/Content/lib/forms.less.]
   Cassette.Stylesheets.LessCompiler.CompileImpl(String lessSource, IFile file) +449
   Cassette.Stylesheets.LessCompiler.Compile(String lessSource, IFile sourceFile) +77
   Cassette.BundleProcessing.<>c__DisplayClass1.<Transform>b__0() +104
   Cassette.Stylesheets.ExpandCssUrlsAssetTransformer.ReadCss(Func`1 openSourceStream) +53
   Cassette.Stylesheets.<>c__DisplayClass1.<Transform>b__0() +43
   Cassette.AssetBase.OpenStream() +103
   Cassette.BundleProcessing.ConcatenatedAsset.WriteAsset(IAsset asset, StreamWriter writer) +54
   Cassette.BundleProcessing.ConcatenatedAsset.CopyAssetsIntoSingleStream(IEnumerable`1 assets) +156
   Cassette.BundleProcessing.ConcatenatedAsset..ctor(IEnumerable`1 children) +72
   Cassette.Bundle.ConcatenateAssets() +42
   Cassette.BundleProcessing.ConcatenateAssets.Process(Bundle bundle, CassetteSettings settings) +9
   Cassette.BundleProcessing.MutablePipeline`1.Process(T bundle, CassetteSettings settings) +488
   Cassette.Stylesheets.StylesheetBundle.Process(CassetteSettings settings) +17
   Cassette.Configuration.BundleContainerFactoryBase.ProcessAllBundles(IEnumerable`1 bundles, CassetteSettings settings) +77
   Cassette.Configuration.CachedBundleContainerFactory.Create(IEnumerable`1 unprocessedBundles, CassetteSettings settings) +148
   Cassette.CassetteApplicationBase.CreateBundleContainer(IEnumerable`1 bundles, CassetteSettings settings, String cacheVersion) +104
   Cassette.Web.StartUp.CreateCassetteApplication() +652
   Cassette.CassetteApplicationContainer`1.CreateApplication() +67
   System.Lazy`1.CreateValue() +361
   System.Lazy`1.LazyInitValue() +104
   System.Lazy`1.get_Value() +89
   Cassette.Web.StartUp.<PostApplicationStart>b__0() +14
   Cassette.Web.CassetteHttpModule.HttpApplicationPostMapRequestHandler(Object sender, EventArgs e) +82
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75
```

I did a little research to see if I could narrow down what was causing the problem. When I added this file search option to the cassette configuration for my content bundle, everything worked fine again:

```
new FileSearch
{
    Pattern = "*.css",
    SearchOption = System.IO.SearchOption.AllDirectories
}
```

The problem is that I probably want to use less for the project specific files here as well. If it crashes when trying to do that then I'm out of luck on that front.

**Comment by andrewdavey** [comment]
Using a `FileSearch` to skip `.less` files is an okay work-around for now. I'll see if I can reproduce the error too.

It may be a problem with the Jurassic JavaScript engine that Cassette uses to run the Less compiler. The next Cassette release should also have a separate implementation that uses Internet Explorer's script engine instead. I would expect this to be much more stable.

I'll do some testing and report back...

**Comment by andrewdavey** [comment]
The problem is that Cassette is trying to compile each `.less` file individually. However, some of these files use variables and mixins defined in other files.

The solution is to make Cassette only compile `bootstrap.less`. This file imports all the others in the correct order.

Assuming you have a bundle just for the twitter bootstrap, create a file alongside the less files called `bundle.txt`. In the file, have just

```
bootstrap.less
```

Cassette will now ignore the other files and rely on the `@import` statements instead.

**Comment by sddaniels** [comment]
That's interesting. I'll give that a try. I was assuming that cassette would not try to compile any less files that were not referenced using `Bundle.Reference()`, but from what you're saying that doesn't appear to be the case.

By the way, great job with the project! I also really enjoy postal, so you're on a roll.

**Comment by andrewdavey** [comment]
Thanks :)

Cassette uses the `CassetteConfiguration` class to build up all the bundles at application start-up and then caches them. The in-page `Bundle.Reference` calls then refer to the pre-built bundle or asset paths.

**Comment by sddaniels** [comment]
Hmm, it didn't seem to recognize my `bundle.txt` file. I did try modifying the file search object again to restrict it to bootstrap.less and that did work. Is there anything special you have to do for it recognize the bundle descriptor file?

**Comment by andrewdavey** [comment]
What does your CassetteConfiguration look like?

**Comment by sddaniels** [comment]
I think I got it. I had the content bundle looking like this:

`bundles.AddPerIndividualFile<StylesheetBundle>("Content");`

When I changed it to this everything worked:

`bundles.Add<StylesheetBundle>("Content");`
