### ISSUE TITLE
Minification of my CSS files cause havoc

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#12]
I'm not sure why, because I can't find any error in my CSS files, but my page looks like shit when debug = false (and thus the CSS gets minified).

Is there any way to turn off minification for stylesheets (perhaps on a module-by-module basis)?
Also, do you have any advice or tools to detect CSS formatting errors that the eye (my eye at least) can't see? :)

**Comment by andrewdavey** [comment]
You can try http://csslint.net/

There's no way to disable minification module-by-module right now.

**Comment by sfmskywalker** [comment]
Thanks for the link. I just validated my stylesheets, none of them gave errors (although I received loads of warnings :))
Might there be a bug in the minification function for CSS?
If it helps I can send you sourcefiles to reproduce the problem.
If all else fails, I would definitely like to be able to turn off minification for stylesheets in a future version (my project won't get released within the next 3 months, so I live in debug mode anyway)

**Comment by andrewdavey** [comment]
It would be useful to see a basic project that reproduces the problem. Can you zip and send to andrew@equin.co.uk please?
Thanks.

**Comment by sfmskywalker** [comment]
I just sent you a sample project, thanks.

**Comment by sfmskywalker** [comment]
As Andrew found out, the problem was an incompatibility between the css minifier and the @page css rule. The solution for now is not using the @page rule until the minifier is updated. I'm not using that @page rule, so I removed it.
