### ISSUE TITLE
Duplication in asset references

### ISSUE THREAD

**Issue by danfma** [andrewdavey/cassette#122]
# Scenario

The problem is simple. Let me say that I have the following configuration for the page:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Bundles.RenderStylesheets()
    @Bundles.RenderScripts("head")
    @Bundles.RenderHtmlTemplates("head")
</head>
<body>
    <header>
        <div id="branding">
        </div>
    </header>
    <section id="content">
        @RenderBody()
    </section>
    @Bundles.RenderHtmlTemplates()
    @Bundles.RenderScripts()
</body>
</html>
```

There are some scripts that must be rendered in the head, like: **jquery**, **jquery.ui** and **jquery.tmpl**. Additionally, I have some templates and others scripts that will be rendered in the end of the body.
# The problem

If I reference some script **App.js** that references back the **jquery**, then **jquery** will have its reference repeated in the body, because it was already added in the head. Then it could be skipped. 

It's not really a problem, because the page will continue to work, but we will be loading twice the same file in the browser, which will be an unnecessary work for the it.
# Solution

Separate and filter the later scripts references by maintaining a cache of rendered filenames.

**Comment by andrewdavey** [comment]
Thanks for the detailed report. There's most certainly a bug in `Cassette.ReferenceBuilder`. I'll try to get a fix into the next release.

**Comment by andrewdavey** [comment]
@danfma Can you grab the latest from master and see if it fixes this issue for you? Thanks.

**Comment by danfma** [comment]
Ok, i will do that and report for you.

**Comment by andrewdavey** [comment]
The above commit is now in v1.0.1 - available via nuget.

**Comment by danfma** [comment]
Hey andrew,

The problem continues there... The jquery file continues to be duplicated on the head and on the body. 

The the scenario is the following:

``` html
@{
    Bundles.Reference("Content/site.css");
    Bundles.Reference("Content/myapp"); // THIS IS A BUNDLE TO THE DIRECTORY Content/myapp

    Bundles.Reference("Scripts/jquery-1.7.1.js", "head");
    Bundles.Reference("Scripts/jquery-ui-1.8.16.js", "head");
    Bundles.Reference("Scripts/jquery.tmpl-1.0.0pre.js", "head");
    Bundles.Reference("Scripts/myapp");  // THIS IS A BUNDLE TO THE DIRECTORY Scripts/myapp
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Html.Partial("_ScriptSupport")
    @Bundles.RenderStylesheets()
    @Bundles.RenderScripts("head")
</head>
<body>
    <header>
        <div id="branding">
            <img src="@Url.Content("~/Content/images/MainLayout_r1_c2_s1.png")" alt="SisImob"/>
        </div>
        <section id="loginContainer">
            @RenderSection("branding", false)
        </section>
    </header>
    <section id="content">
        @RenderBody()
    </section>
    <div id="blockingLayer" data-bind="visible: !login().authenticated()">
    </div>
    @Bundles.RenderHtmlTemplates()
    @Bundles.RenderScripts()
</body>
</html>
```

In the myapp bundle, i have some javascripts the references the jquery file by using the "/// <references..." and that's all. When rendered, the jquery file still continues to appear in the head and on the body.

The App file on the bundle:

``` javascript
/// <reference path="../json2.js"/>
/// <reference path="../jquery-1.7.1.js"/>
/// <reference path="../jquery-ui-1.8.16.js"/>

/// <reference path="../knockout-2.0.0.debug.js"/>
/// <reference path="../knockout.mapping-latest.debug.js"/>
/// <reference path="knockout/knockout.extensions.js"/>

/// <reference path="common.js"/>
/// <reference path="ui/MenuItem.js"/>
/// <reference path="ui/LoginControl.js"/>
/// <reference path="vmodels/AppModel.js" />

App = {
    viewModel: new AppModel(),

    initialize: function () {
        this.applyBindings();

        //
        // Configuring the UI
        //
        $(":button").button();
        $(":input[type='text'], :input[type='password'], :input[type='textare']").addClass("k-input");
        $("#loginControl").sLoginControl();
        $("#tabNavigator li button").button("destroy");
    },

    applyBindings: function () {
        var viewModel = this.viewModel;

        ko.applyBindings(viewModel);
    },

    applyBindingsTo: function (element) {
        var viewModel = this.viewModel;

        viewModel.viewOpened.subscribe(this._onViewOpened);

        ko.applyBindings(viewModel, element);
    }
};

App.initialize();

```

**Comment by andrewdavey** [comment]
Okay, I'm sorry your still having the problem. I'll see if I can replicate the issue...

Can you also paste in the `Configure` method from your `CassetteConfiguration` class please?

**Comment by danfma** [comment]
No worry about the bugs! Your Cassette is a great tool, we just need to make it even better! :P

I will prepare the solution and send you all the code.

**Comment by danfma** [comment]
Andrew, 

I sent to you a project with the problem (your e-mail on the github).

**Comment by andrewdavey** [comment]
Thanks for sending the sample project. I've taken a quick look and now see why it's still include those scripts twice. I'll need longer to properly fix the bug, but for now try this alternative approach:

In CassetteConfiguration, after the bundles have been added:

```
bundles["Scripts/jquery-1.7.1.js"].PageLocation = "head";
bundles["Scripts/jquery-ui-1.8.16.js"].PageLocation = "head";
```

This defaults those bundles to having `head` as their page location. Now the view `Bundles.Reference` calls don't need to specify `head`.

**Comment by andrewdavey** [comment]
The above commit should fix the problem.

**Comment by danfma** [comment]
\o/ It's working now! Thanks Andrew!
