### ISSUE TITLE
Path match issue in css url('') parser

### ISSUE THREAD

**Issue by hempels** [andrewdavey/cassette#123]
Provided the following content in file `~/Content/background.css`:

```
.class {
    background: url('/Content/background.png');
}
```

Cassette will look for the file ~/Content/Content/background.png, determine it does not exist, and create a new asset reference pointing to: ~/Content/Content/background.png. This also has the effect of expiring the cache on every request, which is how I discovered the problem.

I suspect the best fix would be to modify `GetImageFilename` (in ExpandCssUrlsAssetTransformer) to recognize host-relative paths.

**Comment by andrewdavey** [comment]
I've merged these into master. They'll be in the next nuget release (v1.0.1)
Thanks!
