### ISSUE TITLE
Cannot reference aliased external bundle/reference

### ISSUE THREAD

**Issue by kamranayub** [andrewdavey/cassette#129]
If you create an external script reference, such as Google Web Fonts, and give it an alias ("Fonts"), you cannot reference this bundle by the alias in a stylesheet or other asset. You must manually include the reference in the view:

```
@Bundles.Reference("Fonts");

In base.css (example), this won't work:
/* @reference Fonts */
```

**Comment by andrewdavey** [comment]
Try using the app relative path instead:

```
/* @reference ~/Fonts */
```

By default the reference path is relative to the current file. Perhaps Cassette could fallback to trying an app-relative path when it can't find it relative to the file?
