### ISSUE TITLE
Media attribute per css file

### ISSUE THREAD

**Issue by petersonnek** [andrewdavey/cassette#132]
What's the best way to create a bundle per css media type?  Is there a way to set the media attribute per file with an additional attribute in the css file?

I know I can create a separate bundle for a media type for my print stylesheet using a subdirectory or filter but it would be nice if Cassette was smart enough to know to split my css budles by a media type attribute that had been added to the css file.

**Comment by andrewdavey** [comment]
The `StylesheetBundle` type has a `Media` property. So when you add bundles you can do something like this:

```
bundles.Add<StylesheetBundle>("path/to/print/css", bundle => bundle.Media = "print");
```

or, if the bundle has been added already (by `AddPerSubDirectory` for example):

```
bundles.Get<StylesheetBundle>("path").Media = "print";
```

**Comment by petersonnek** [comment]
That's what I ended up doing but I was thinking it would be a cool feature to be able to add an extra attribute in the css files, similar to the references, that Cassette would key on to bundle css by media type.  Might be an edge case but I thought I'd see what you thought.

**Comment by andrewdavey** [comment]
If you wanted to try it out, create an `IBundleProcessor` implementation, similar to https://github.com/andrewdavey/cassette/blob/master/src/Cassette/BundleProcessing/ParseReferences.cs

The insert it into the stylesheet pipeline processor during configuration:

```
bundles.Add<StylesheetBundle>("path", b => b.Processor = new StylesheetPipeline().InsertAfter<ParseReferences>(new MediaTypeParser()));
```
