### ISSUE TITLE
No strong name for Cassette assembly

### ISSUE THREAD

**Issue by robitar** [andrewdavey/cassette#134]
Just putting the issue up here before I fork and try to add it myself, assuming there aren't too many non strong named dependencies.

**Comment by andrewdavey** [comment]
Cassette depends on `WebActivator` and `Jurassic`, which don't have a strong names... so you'll need to fork those too.

What's your reason for needing Cassette to be strongly named?

**Comment by robitar** [comment]
Company policy to strong name assemblies it produces.

I'm able to get around this one though cause the web project just has scripts & styles etc, so I can switch it off, nothing else needs to reference Cassette afaik.
