### ISSUE TITLE
Bundle Descriptor bugs when Site is Virtual Directory

### ISSUE THREAD

**Issue by robasta** [andrewdavey/cassette#138]
I have the following file structure:
~/scripts
~/scripts/calendar

I have setup a  bundles.txt in the calendar folder describing the references and ordering. This works perfectly when I run in Visual Studio. However, when I deploy the site as a virtual folder ("http:/localhost/mysite/") 

My bundles.txt has:

Common.js
jquery.alert.js
wdCalendar_lang_US.js
jquery.calendar.js
*

[references]
~/scripts

I get an error saying:

Reference error in bundle descriptor for "~/Scripts/calendar". Cannot find "~/scripts".

The stacktace reads:

`
[AssetReferenceException: Reference error in bundle descriptor for "~/Scripts/calendar". Cannot find "~/scripts".]
   Cassette.BundleContainer.ValidateBundleReferences() +347
   Cassette.BundleContainer..ctor(IEnumerable``1 bundles) +33
   Cassette.Configuration.BundleContainerFactory.Create(IEnumerable``1 unprocessedBundles, CassetteSettings settings) +122
   Cassette.Web.StartUp.CreateCassetteApplication() +738
   Cassette.CassetteApplicationContainer.CreateApplication() +67
   System.Lazy``1.CreateValue() +361
   System.Lazy``1.LazyInitValue() +104
   System.Lazy``1.get_Value() +89
   Cassette.CassetteApplicationContainer.get_Application() +11
   Cassette.Web.CassetteHttpModule.HttpApplicationPostMapRequestHandler(Object sender, EventArgs e) +15
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75`

**Comment by andrewdavey** [comment]
I'm sorry for not responding to this sooner. I'm looking into it now.

**Comment by andrewdavey** [comment]
Is the directory you've deployed to a proper IIS "application"? I don't think it just being a plain virtual directory will work. The paths in Cassette are relative to the application root.

**Comment by ffzhai** [comment]
if my css and js file in the virtual directory on IIS, how can I AddPerSubDirectory or AddPerIndividualFile them?

**Comment by andrewdavey** [comment]
I'm sorry, I don't understand your question. Where are the css and js files in relation to the web application?

**Comment by ffzhai** [comment]
The application will using this css files which in the virtual directory
file structure of my web application:
Web Site
~/Virtual Directory A(include css files)
~/Virtual Directory B(include js files)
~/Views
--....
the virtual directory reference from another disk path not the web application local path.
