### ISSUE TITLE
Only read IsolatedStorage if config for cache is using it

### ISSUE THREAD

**Issue by bakesteve** [andrewdavey/cassette#139]
If we want to use filebased cache storage, rather than isolatedStorage, and set:

```
settings.CacheDirectory = new Cassette.IO.FileSystemDirectory("d:\\web\\someSite\Scripts\Cache");
```

in
    Cassette.Web.Startup.PostApplicationStart
line 81 references isolated storage regardless - so if we cant use that Cassette will error

Should move to being lazy, and return null if our configurations dont use isolatedStorage?
Easiest way to test is just remove permissions for the iis_wpg users on the isolatedStorage folder.

If not enough time to look at this, I can have a look at producing a patch

**Comment by bakesteve** [comment]
I did a first stab at moving cache directory to lazy - you can see at:
https://github.com/bakesteve/cassette/commit/a173597806ddec8e080e10baf0d3a776d5a91b96

had to change the actual reference in CassetteConfiguration so that you still get IsolatedStorage by default, but that will only be accessed if you dont override in your own cassetteConfiguration.

It does mean an api change from IDirectory > Lazy<IDirectory>
if that is a major issue, then guess make the existing property wrap ontop of a new lazy property and internally just use the lazy version?
Might make keeping in line with semVer a bit easier as my change would count as a breaking api change (even if I reckon you can be sure no one is actually setting the cacheDir.  but know thats not the point!)

**Comment by andrewdavey** [comment]
Thanks for taking a look at this. I do prefer avoiding the breaking API change at this stage, so I've taken a different approach to solving this issue. The v1.1 branch introduces `IsolatedStorageContainer`, which manages the lifetime of the isolated storage object. The Direction and File classes also get new constructors that accept `Func<System.IO.IsolatedStorage.IsolatedStorageFile>` so they'll only trigger the creation of isolated storage on first use.
