### ISSUE TITLE
*-vsdoc.js not being ignored

### ISSUE THREAD

**Issue by HerbieHopper** [andrewdavey/cassette#14]
Hi Andrew,

Further to our Tweets, I set up a default ASP.NET MVC test project to try Cassette, but when I reference the jQuery vsdoc file from within a script file I get the following exception:

The file "scripts/Lib/jquery-1.5.1-vsdoc.js" is referenced by "scripts/TestScript/Core.js", but cannot be found. Either add "scripts/Lib/jquery-1.5.1-vsdoc.js" or change the reference(s) to a file that exists. 

Here is the stack trace:

[FileNotFoundException: The file "scripts/Lib/jquery-1.5.1-vsdoc.js" is referenced by "scripts/TestScript/Core.js", but cannot be found. Either add "scripts/Lib/jquery-1.5.1-vsdoc.js" or change the reference(s) to a file that exists.]
   Cassette.Web.ExceptionCachedManager.CreatePageAssetManager(HttpContextBase httpContext) +75
   Cassette.Web.CassetteHttpModule.<Init>b__0(Object sender, EventArgs e) +118
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

I've copied the jQuery vsdoc file into a /script/Lib sub-folder.  

Am I doing something wrong?

Cheers

**Comment by andrewdavey** [comment]
Don't reference the vsdoc.js file from your script. Reference the regular js file. I think VS still picks up the intellisense for you.

**Comment by HerbieHopper** [comment]
That appears to work, thanks Andrew.
