### ISSUE TITLE
Need an API to retrieve all referenced bundle URLs

### ISSUE THREAD

**Issue by hempels** [andrewdavey/cassette#140]
We have an API to generate the URL for a single bundle, but that is only useful if you know the bundle paths. What I'd like to be able to do ( though I'm not certain it's possible) is generate bundle URLs for all references in a view context.

I'm using JSON to implement a Single Page Interface application. One of the things my SPI framework does is load CSS and Script dependencies dynamically along with each rendered partial view. However, what I don't have is a method to utilize the Cassette references within each view to produce the URLs for them. It would be ideal if I didn't have to make those associations outside of the views, which is what I'm doing currently.

What I've envisioned would be ideal is an API such as this:

public static class Bundles {
    public static IEnumerable<string> Urls<T>() where T : Bundle
}

The problem I'm discovering of course is that without the context of the view, there are no present references. So here's the question - is it possible, and if so how, to retrieve a list of references for a view either before or after rendering said view and then turn those references into an IEnumerable of URLs?

**Comment by andrewdavey** [comment]
The API to do something like this is currently internal. I will be making some of it public in the next release. (This makes testing views possible as well.)

Adding a `Bundles.ReferencedUrls()` method can be done. However, we may also need `ReferencedUrls(string pageLocation)`, `ReferencedUrls<T>(string pageLocation)` and `ReferencedUrls<T>()` for completeness.

The references made from a partial view will cascade to include all dependencies. So you'd end up with the main app bundles also included in the URLs returned. Is this okay?

I've got plans to add [require.js](http://requirejs.org/) support to Cassette. This may end up being a better solution for you actually... I'll keep you posted

**Comment by SLaks** [comment]
I added this API in [my fork](https://github.com/SLaks/cassette).

https://github.com/SLaks/cassette/commit/7fc67a675cdfbf4bb7191afc9dcc1eee09ce9e05

**Comment by hempels** [comment]
That's great!

Is there a way to retrieve URLs for the returned bundles?

**Comment by SLaks** [comment]
```
  Bundles.Url(b.Path)
```

or (faster)

```
 CassetteApplicationContainer.Application.Settings.UrlGenerator.CreateBundleUrl(b)
```

In debug mode, you need to call `CassetteApplicationContainer.Application.Settings.UrlGenerator.CreateAssetUrl` for each item in `b.Assets`.

**Comment by andrewdavey** [comment]
The above commits add support for:

```
var bundles = Bundles.GetReferencedBundles();
```

and

```
var urls = Bundles.GetReferencedBundleUrls<ScriptBundle>();
```

In release mode `GetReferencedBundleUrls` returns bundle URLs. In debug mode `GetReferencedBundleUrls` returns the constituent assets URLs for each referenced bundle.

**Comment by SLaks** [comment]
How does that handle external script bundles?

I used the following code (after making ExternalScriptBundle public):

```
Modernizr.load([
    " + String.Join(",\n\t",
      isDebug ?
        scripts.SelectMany(s => s.Assets.Select(a => JsLiteral(urlGen.CreateAssetUrl(a))))
      :
          scripts.Select(s => {
              var esb = s as ExternalScriptBundle;
              if (esb != null) {
                  if (esb.Assets.Any())
                      return "{ load:" + JsLiteral(esb.Url) + ", complete: function() { if(" + esb.FallbackCondition + ") yepnope(" + JsLiteral(urlGen.CreateBundleUrl(s)) + "); } }";
                  else
                      return JsLiteral(esb.Url);
              } else
                  return JsLiteral(urlGen.CreateBundleUrl(s));
          })) + @"
]);
```

**Comment by andrewdavey** [comment]
Good question. `GetReferencedBundleUrls` doesn't support external bundles correctly.

Perhaps a better design would be for `Bundle` to have an internal abstract `Url` property. Then the `UrlGenerator` can call that when building the bundle URL. If the bundle returns a non-external URL, then it prepends the "_cassette" prefix.

The Modernizr loading you're doing could make for a create Cassette plugin. Let's talk more about how this could work. Either ping me on skype, or create another GitHub issue.

**Comment by andrewdavey** [comment]
Whoops, that commit isn't right! Fix coming soon.

**Comment by andrewdavey** [comment]
Fixed in master
