### ISSUE TITLE
LessCompiler slowing down startup 

### ISSUE THREAD

**Issue by honestegg** [andrewdavey/cassette#144]
It appears that the LessCompiler is slowing down the application startup even when there are no .LESS files to compile. During development, if we make any small change to a page it will then take 30 to 60 seconds to reload the that page.

Setting up the Jurassic ScriptEngine in the constructor seems to be an expensive operation. This happens whether there are any .LESS files to process or not. 

``` c#
public LessCompiler()
{
    engine = new ScriptEngine();
    engine.Execute("window = { location: { href: '/', protocol: 'http:', host: 'localhost' } };");
    engine.SetGlobalFunction("xhr", new Action<ObjectInstance, ObjectInstance, FunctionInstance, FunctionInstance>(Xhr));
    engine.Execute(Properties.Resources.less);
}
```

Would it be better to only setup the ScriptEngine the first time it is used? -- Maybe move this out of the constructor and into the "get" of a property?

**Comment by nazjunaid** [comment]
By Default CompileLess = true in StylesheetPipeline however I believe you can change it like so

```
bundles.Add<StylesheetBundle>(@"resources\styles\common", null, bundle => bundle.Processor = new StylesheetPipeline {
    CompileLess = false 
});
```

**Comment by andrewdavey** [comment]
We can make the LESS compiler initialization lazy, like the CoffeeScript compiler does.

**Comment by honestegg** [comment]
nazjunaid: Thanks for the tip. That fixes it for me for now.
