### ISSUE TITLE
Merge user supplied htmlAttributes object with link/script elements

### ISSUE THREAD

**Issue by tomdenny** [andrewdavey/cassette#145]
### Feature request

One thing that I've come across every so often and think to myself that it would be nice if Cassette supported would be the ability to define htmlAttributes that would get merged with the link/script elements when rendering.

It would be nice to support the async="async" attribute of script and I recently came across an interesting modernizr polyfill that requires you to add a class="cssfx" to your link element: http://imsky.github.com/cssFx/

Love Cassette.  Nice job on it.

**Comment by andrewdavey** [comment]
That could be handy feature to add. Do you fancy having a go at implementing it?

You'll need to add a dictionary property to `Bundle` and update the various `IBundleHtmlRenderer<T>` implementations to generate the attributes in the HTML.

**Comment by tomdenny** [comment]
Sure!  I'm a bit busy so I won't get to it for a day or two, but I'd love to take a crack at it and send a pull request.  Thanks for the opportunity.

**Comment by andrewdavey** [comment]
This is now available in `master`
