### ISSUE TITLE
PIE.htc Issue

### ISSUE THREAD

**Issue by sddaniels** [andrewdavey/cassette#149]
I'm using the PIE.htc file to backfill some nice CSS3 stuff to IE. In my older project, Cassette left the PIE.htc file reference in the CSS file alone and everything worked fine. Now it seems to transform the original path into one that goes through cassette, which is the normal behavior for images I think. The problem is that this essentially removes the ".htc" file extension and IE no longer recognizes it as a behavior file. That means all of my nice CSS3 stuff is missing again.

I think your proposed solution was to maintain the original file extensions through cassette.

**Comment by andrewdavey** [comment]
Thanks for creating this issue.

@stucampbell also noticed this bug. He's working on a fix at the moment.

**Comment by stucampbell** [comment]
I've fixed this and sent the pull request. Sorry for the delay - I had to go watch my kid play tennis. :)

**Comment by sddaniels** [comment]
Good deal! No worries on my end. Thanks for the fix
