### ISSUE TITLE
Allow adding a single file into the BundleCollection

### ISSUE THREAD

**Issue by drlongnecker** [andrewdavey/cassette#152]
Ability to add a single parent file (e.g bootstrap.less) into the BundleCollection and allow that parent file to handle the `@import` references after that.

Current workaround is:

```
bundles.AddPerIndividualFile<StylesheetBundle>("styles/libs/bootstrap", new FileSearch()
{
    Pattern = "bootstrap.less"
});
```

ref: https://groups.google.com/d/topic/cassette/4vdVp9ZyNU4/discussion

**Comment by drlongnecker** [comment]
First stab at it with a few tests; I'll dig a bit deeper into it when I get home tonight to make sure the everything's covered.

**Comment by bakesteve** [comment]
would this allow adding multiple abritary files? or am i missing something - know its been raised on the forums, but didnt think you could say:
AddFiles<T>("Scripts/file1.js","Scripts/File2.js","someWhereElse/moreScript.js") 
would solve a few nuget issues for us and feels one that shouldnt be too hard to add?
and yes - means a pull request is probably in order!

**Comment by drlongnecker** [comment]
My original request was so I would let the raw .less file itself handle `@import` rather than maintain them all in Cassette references.

We ended up just using the existing `Add<T>` method (see #156); however, modifying this to be  useful to cherry pick files as a `params` would be useful for those edge cases where framework libraries expect files in a certain spot. The idea kinda goes against the 'spirit' of Cassette's conventions.

**Comment by bakesteve** [comment]
Yeah. Main case I can think of is nuget packages & a couple edge cases
where we dont yet want to reorganise some scripts that are still referenced
in older parts of the project.

Other approach is to just let nuget go where it wants but then copy them
into more sensible packs.

At present we use chirpy config files for that, but something lighter would
be good (its a vs add, and very good, but overkill for this)
Anyone else faced / solved this?
Extending the bundles.text file to have a import section (that does a
simple file copy) would be nice, any merit to looking at this?
On Feb 7, 2012 10:55 PM, "David R. Longnecker" <
reply@reply.github.com>
wrote:

**Comment by drlongnecker** [comment]
Actually, digging in, it looks like you can already do this.

For example:

```
bundles.Add<StylesheetBundle>("styles",
     new [] {"~/styles/libs/bootstrap/bootstrap.less", "~/styles/site.less"});
```

There's an overload on Add<T> that takes an IEnumerable<string> and then adds the files in.  I just tested it out and it works like a champ.
