### ISSUE TITLE
Unable to determine granted permission for assembly. Cassette.Web

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#154]
When using the release dll of Cassette.Web (debug is fine) of current master whether I use the built.bat or build in Visual Studio I get the following error.

Unable to determine granted permission for assembly.

```
Line 18:         public static IsolatedStorageFile IsolatedStorageFile
Line 19:         {
Line 20:             get { return LazyStorage.Value; }
Line 21:         }
Line 22: 

[IsolatedStorageException: Unable to determine granted permission for assembly.]
   System.IO.IsolatedStorage.IsolatedStorage.InitStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType) +746
   System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType) +77
   System.Lazy`1.CreateValue() +12770415
   System.Lazy`1.LazyInitValue() +355
   Cassette.Web.IsolatedStorageContainer.get_IsolatedStorageFile() in C:\Websites\Git\forks\cassette\src\Cassette.Web\IsolatedStorageContainer.cs:20
   Cassette.IO.IsolatedStorageFile.get_Exists() in C:\Websites\Git\forks\cassette\src\Cassette\IO\IsolatedStorageFile.cs:46
   Cassette.Manifests.CassetteManifestCache.LoadCassetteManifest() in C:\Websites\Git\forks\cassette\src\Cassette\Manifests\CassetteManifestCache.cs:17
   Cassette.Configuration.CachedBundleContainerFactory.Create(IEnumerable`1 unprocessedBundles) in C:\Websites\Git\forks\cassette\src\Cassette\Configuration\CachedBundleContainerFactory.cs:27
   Cassette.Web.CassetteApplicationContainerFactory.CreateCassetteApplicationCore() in C:\Websites\Git\forks\cassette\src\Cassette.Web\CassetteApplicationContainerFactory.cs:82
   Cassette.CassetteApplicationContainerFactoryBase`1.CreateApplication() in C:\Websites\Git\forks\cassette\src\Cassette\CassetteApplicationContainerFactoryBase.cs:51
   Cassette.CassetteApplicationContainer`1.CreateApplication() in C:\Websites\Git\forks\cassette\src\Cassette\CassetteApplicationContainer.cs:135
   System.Lazy`1.CreateValue() +12770415
   System.Lazy`1.LazyInitValue() +355
   Cassette.Web.StartUp.PostApplicationStart() in C:\Websites\Git\forks\cassette\src\Cassette.Web\StartUp.cs:63

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle._InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeType typeOwner) +0
   System.RuntimeMethodHandle.InvokeMethodFast(IRuntimeMethodInfo method, Object target, Object[] arguments, Signature sig, MethodAttributes methodAttributes, RuntimeType typeOwner) +152
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks) +396
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +38
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   WebActivator.BaseActivationMethodAttribute.InvokeMethod() +341
   WebActivator.ActivationManager.RunActivationMethods() +787
   WebActivator.ActivationManager.RunPostStartMethods() +38
   WebActivator.StartMethodCallingModule.Init(HttpApplication context) +159
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +575
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +352
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +407
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +375

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +11700592
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +141
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +4868789
```

**Comment by andrewdavey** [comment]
Is this running in IIS or IIS Express? If IIS, which version. Also, which user account is it running under?

**Comment by nazjunaid** [comment]
IIS 7.5.7600.16385 running under a custom user account.

**Comment by andrewdavey** [comment]
So for some reason I guess that user account can't create the isolated storage...

For now you can tell Cassette to use the regular file system for its cache. In `CassetteConfiguration` try something like:

```
settings.CacheDirectory = new FileSystemDirectory("~/app_data");
```

**Comment by nazjunaid** [comment]
Why would it only happen in the release build of that dll when Cassette.Web.dll is debug it works?

**Comment by andrewdavey** [comment]
Cassette in debug mode does not use the cache because each asset is served separately. There is no combined bundle output to be cached, so it skips this step.

**Comment by nazjunaid** [comment]
Sorry when I mean in debug I don't mean when debug="false" in the config.

I mean when the Cassette.Web dll is built in debug eg. /p:Configuration=Debug and using  debug="false" it works.

When Cassette.Web dll is built in release so /p:Configuration=Release and using debug="false" it breaks.

**Comment by andrewdavey** [comment]
I'm sorry for misunderstanding.

That's very strange behaviour! I'll have to investigate...

**Comment by nazjunaid** [comment]
I was thinking maybe the compiler is optimizing something away.

**Comment by nazjunaid** [comment]
I changed the Release configuration of the Cassette.Web project and unchecked Optimize Code and then resulting dll works.

I narrowed down the issue happening due to using Lazy loading for the IsolatedStorageContainer.

The following code fixes the issue and is thread safe using good old fashion locking.

```
static class IsolatedStorageContainer
{
    static IsolatedStorageFile LazyStorage;
    static readonly object classLock = new object();

    static IsolatedStorageFile CreateIsolatedStorage()
    {
        return IsolatedStorageFile.GetMachineStoreForAssembly();
    }

    public static IsolatedStorageFile IsolatedStorageFile
    {
        get 
        { 
            if (LazyStorage == null)
            {
                lock (classLock)
                {
                    if (LazyStorage == null)
                    {
                        LazyStorage = CreateIsolatedStorage();
                    }
                }
            }
            return LazyStorage;
        }
    }

    public static void Dispose()
    {
        LazyStorage.Dispose();
    }
}
```

Still confused as to why combination of Optimize code and Lazy has problems with IsolatedStorageFile

#### EDIT: Updated fix as previous version wasn't thread safe this one is.

**Comment by andrewdavey** [comment]
Hmm, the compiler optimizing away the Lazy sounds very scary! Thanks for digging into this issue. I'll bear this in mind while I'm looking for answers.

**Comment by nazjunaid** [comment]
I am able to replicate this issue by executing the following code in Linqpad so I don't think it's related only to our application.

```
Lazy<IsolatedStorageFile> Storage = new Lazy<IsolatedStorageFile>(IsolatedStorageFile.GetMachineStoreForAssembly);
var storage = Storage.Value;
```

Error is same as above. 

I think Lazy construction is somehow confusing the context of the isolated storage.

Still not sure why we only get the error on release builds on our site however when I set my Linqpad not to optimize queries and I still get the error.

**Comment by nazjunaid** [comment]
After researching the various ways of lazy loading singleton's I decided to go with the 5th approach described here

http://csharpindepth.com/articles/general/singleton.aspx

I've committed the fix on my branch.

**Comment by andrewdavey** [comment]
I've created a stackoverflow question for this too: http://stackoverflow.com/questions/9113791/lazily-creating-isolated-storage

**Comment by andrewdavey** [comment]
This answer http://stackoverflow.com/a/9113892/7011 suggests we could try changing line 11 of `IsolatedStorageContainer` to:

```
static readonly DisposableLazy<IsolatedStorageFile> LazyStorage = new DisposableLazy<IsolatedStorageFile>(() => CreateIsolatedStorage());
```

i.e. don't use a method group, but a full lambda instead.

Does that work for you?

BTW a basic command line app, running a debug build, also throws the exception for me too. Switching to a proper lambda fixed it.

**Comment by nazjunaid** [comment]
Awsome I changed line 11 to:

```
static readonly DisposableLazy<IsolatedStorageFile> LazyStorage = new DisposableLazy<IsolatedStorageFile>(() => CreateIsolatedStorage());
```

And it works!

Now I must resist of urge of resharper telling me to convert it to a method group :)

**Comment by andrewdavey** [comment]
The above pull request applies the fix.

I've also added the required ReSharper "disable" comment to remind us ;)

**Comment by JayVDZ** [comment]
Oddly I'm getting this with the latest NuGet package update just now. VS did ask me if I wanted to overwrite my CassetteConfiguration.cs file and I said no (obviously) and thought maybe there was something in there new breaking things? I couldn't see anything in the examples in the source though.

Any ideas?

**Comment by JayVDZ** [comment]
This commit seems to have made substantial changes to the IsolatedStorageContainer class:
https://github.com/andrewdavey/cassette/commit/fa00c9819ba8937d3aa4e871824375c5bc9dbba9

Specifically, the ReSharper ConvertClosureToMethodGroup change seems to have come back and could potentially be causing this issue to reappear?

**Comment by nvivo** [comment]
I also started to see this issue after updating to 2.4.0 with VS 2013 and IIS Express. The application is on debug mode.

**Comment by JayVDZ** [comment]
I've emailed Andrew directly about this just in case he doesn't get notifications. No reply as of yet.

**Comment by andrewdavey** [comment]
Sorry about this regression. I don't have the time to debug it right now. I'd be happy to take a pull request that fixes it though. Otherwise, I suggest rolling back to v2.3 for now.

**Comment by JayVDZ** [comment]
My Ninja skills weren't enough to solve it in a few minutes so I gave up and changed my web.config cassette node to &lt;cassette cacheDirectory="~/app_data" /&gt; and it's bypassed the issue for now. Sorry.

**Comment by andrewdavey** [comment]
So far I've been unable to reproduce this exception. I created a new web project in VS 2013, targeting .NET 4.5.1. I ran it using IIS Express and it seems work just fine.

Can someone let me know what configuration/server/etc they are running on please?

**Comment by NikGovorov** [comment]
@andrewdavey , here is my configuration: IIS8, .NET 4.5, AppPool Identity: Local System.

**Comment by JayVDZ** [comment]
My configuration is: Win7, IIS 7.5.7600.16385 .NET 4.5 ApplicationPoolIdentity.

**Comment by nvivo** [comment]
I upgraded my project back to 2.4.0 but I'm not getting the error anymore. I'm still using .NET 4.5.1, VS 2013 Update 1 and its version of IIS Express. I tried using IIS 8.5 at the time, but got the same error at the time.

I'll keep using 2.4.0 and see if it comes back.

**Comment by nwyman** [comment]
+1, updating from 2.2.2 to 2.4 introduced this error. My configuration is similar to Amethi's.

**Comment by noamberda** [comment]
I have the same problem, it only happen when i deploy to Azure. Here are the exception details. Maybe it can help

[IsolatedStorageException: Unable to determine granted permission for assembly.]
   System.IO.IsolatedStorage.IsolatedStorage.InitStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType) +5184248
   System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(IsolatedStorageScope scope, Type domainEvidenceType, Type assemblyEvidenceType) +77
   System.Lazy`1.CreateValue() +14276560
   System.Lazy`1.LazyInitValue() +476
   Cassette.Aspnet.IsolatedStorageContainer.get_IsolatedStorageFile() +88
   Cassette.IO.IsolatedStorageFile.get_Exists() +19
   Cassette.Aspnet.WebHostSettingsConfiguration.IsStaticCacheManifest(CassetteSettings settings) +80
   Cassette.Aspnet.WebHostSettingsConfiguration.Configure(CassetteSettings settings) +249
   Cassette.ConfigurationEnumerableExtensions.Configure(IEnumerable`1 configurations, T configurable) +176

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +281
   Cassette.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +873

[TinyIoCResolutionException: Unable to resolve type: Cassette.CassetteSettings]
   Cassette.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +1241
   Cassette.TinyIoC.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) +165
   Cassette.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) +1296
   Cassette.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +730

[TinyIoCResolutionException: Unable to resolve type: Cassette.FileSystemWatchingBundleRebuilder]
   Cassette.TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) +1049
   Cassette.TinyIoC.SingletonFactory.GetObject(Type requestedType, TinyIoCContainer container, NamedParameterOverloads parameters, ResolveOptions options) +165
   Cassette.TinyIoC.TinyIoCContainer.ResolveInternal(TypeRegistration registration, NamedParameterOverloads parameters, ResolveOptions options) +1296
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +248
   System.Linq.<CastIterator>d__b1`1.MoveNext() +296
   Cassette.HostBase.RunStartUpTasks() +248
   Cassette.HostBase.Initialize() +320
   Cassette.Aspnet.CassetteHttpModule.InitWithTraceLogging() +158
   Cassette.Aspnet.CassetteHttpModule.Init(HttpApplication httpApplication) +165
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +530
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): Unable to resolve type: Cassette.FileSystemWatchingBundleRebuilder]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12968436
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12808141
