### ISSUE TITLE
Backbone.js application example project

### ISSUE THREAD

**Issue by christophercliff** [andrewdavey/cassette#155]
I'd like to write a tutorial/blog post demonstrating how to use Cassette to organize a Backbone.js application. This could either be contributed to the project wiki or be in a standalone blog, but I think it would be useful to people if the application was an additional web project in the Cassette source.

Would you be interested in merging this if I put together a pull request?

**Comment by andrewdavey** [comment]
That sounds like an excellent sample application to show off Cassette's features!

I've been thinking about removing the current "Example" project from the main Cassette solution. In it's place I'd like to see a collection of sample projects that show Cassette being used in different ways. This is much better than cramming all the features into a huge project.

A sample project showing how to organize a Backbone app using Cassette would fit in well with this.

Let's keep everything in the one repository, but put sample applications in `~/samples`. So, for example, your sample could be in `~/samples/backbone`.

The getcassette.net website could also be expanded with a tutorials/articles section to contain the text portion of the samples. I'll speak to @chinxy (the designer behind the website) about this.

**Comment by andrewdavey** [comment]
(Bah - hitting "Close issue" by mistake in GitHub is way too easy! ... re-opened)

**Comment by christophercliff** [comment]
Hmm, my inclination was to create an addtional project similar to [Example](https://github.com/andrewdavey/cassette/tree/master/src/Example), e.g. BackboneExample, to keep the Cassette config understandable.

Not sure if this is what you're suggesting?

**Comment by andrewdavey** [comment]
Yes, exactly.

Also I think moving the samples out of the `src` directory and into a new `samples` directory, in the root of the repo would be good. That makes it clear that `src` is for the main source of Cassette. We may want a separate Visual Studio solution file for samples as well - otherwise the main build will start to take ages :)
