### ISSUE TITLE
minified js causes Opera Issues (ajaxmin 4.45.4416.14249)

### ISSUE THREAD

**Issue by redsquare** [andrewdavey/cassette#157]
Opera does not like the minified js produced by ajaxmin  This is even after upgrading the the latest ajaxmin nuget package (4.45.4416.14249.)

The issue seems to be around the in keyword as show here http://gyazo.com/f516d9499e3d1e87bc30ecef8a8f32e1. That line is from jquery 1.7.1 
The suggested fix from http://ajaxmin.codeplex.com/workitem/16850 is "If you want to minify jQuery 1.7 (for example) and ensure Opera 11 compatibility, please use the kill switch on the command line"

Is it possible for us to include our choice of min tool (yui, closure etc)?

**Comment by redsquare** [comment]
I have just tested my app removing the local copy of jquery and linking directly to the jquery google cdn version and everything works so it is def an issue with ajaxmin and jquery.

**Comment by andrewdavey** [comment]
Try enabling the ajaxmin kill switch like this:

```
bundles.AddPerSubDirectory<ScriptBundle>("scripts", b => b.Processor = new ScriptPipeline
{
    Minifier = new MicrosoftJavaScriptMinifier(new CodeSettings { KillSwitch = 0x40000000000 })
});
```

**Comment by redsquare** [comment]
Thanks, will try this afternoon
On Feb 6, 2012 10:27 AM, "Andrew Davey" <
reply@reply.github.com>
wrote:

**Comment by icrf** [comment]
We just upgraded our website to jQuery 1.7 and are seeing this bug in Opera. At the end of my Configure method after various bundles have been created, I'm running the below, but the kill switch doesn't seem to affect the output any. Am I doing something wrong?

```
foreach (Cassette.Bundle bundle in bundles)
{
    ScriptBundle scriptBundle = bundle as ScriptBundle;
    if (scriptBundle != null)
    {
        scriptBundle.Processor = new ScriptPipeline
        {
            Minifier = new MicrosoftJavaScriptMinifier(new CodeSettings { KillSwitch = 0x40000000000 })
        };
    }
}
```

According to a later issue with AjaxMin, it looks like an Opera dev is aware of and fixed the issue, but it hasn't made it to a public release yet: http://ajaxmin.codeplex.com/workitem/17812

I'm running Cassette v1.2.0 and AjaxMin v4.46.4422.26284 from NuGet in Opera 11.64.

**Comment by tkarpinski** [comment]
same here. looks like the KillSwitch is for something else.

**Comment by icrf** [comment]
My problem was some kind of caching I didn't understand in Cassette. The KillSwitch worked fine, but the bundle wasn't updated when I rebuilt the site, so I didn't see the change. I had to touch one of the actual JS files in the bundle for the bundle to be rebuilt. After that, everything worked fine in Opera.
