### ISSUE TITLE
Update of AjaxMin caused exception

### ISSUE THREAD

**Issue by kaatula** [andrewdavey/cassette#16]
In NuGet package manager I update Cassete and in the same time I decided to update AjaxMin from 4.13 to latest (4.19). NuGet manager successfully updated references in my project file. However, it appears that Cassete has a reference to particular version of AjaxMin. I got following exception:

Could not load file or assembly 'AjaxMin, Version=4.13.4076.28499, Culture=neutral, PublicKeyToken=24297a69a7eae424' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

(No stack trace available)

My guess it's related with reference in project file
https://github.com/andrewdavey/cassette/blob/master/src/Cassette/Cassette.csproj
to AjaxMin assembly with strong name and particular version.

**Comment by andrewdavey** [comment]
What is the correct way to tell nuget that I want the Cassette package to depend on AjaxMin v4 and greater?

It seems like the default behaviour is "ha ha you lose" :( #confused

**Comment by smnbss** [comment]
if you compiled against v 4.13, but you want to use it with 4.19 you have to use assembly binding to tell you apppool to look for the newer version of the dependency

http://msdn.microsoft.com/en-us/library/2fc472t2(v=vs.71).aspx

something like

```
<runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly> 
               <assemblyIdentity name="AjaxMin" publicKeyToken="b03f5f7f11d50a3a" culture=""/>
                <bindingRedirect oldVersion="0.0.0.0-4.18.0.0" newVersion="4.19.0.0"/>
            </dependentAssembly>
       </assemblyBinding>
</runtime>
```

**Comment by kaatula** [comment]
<b>andrewdavey</b>,

I believe the problem was not with nuGet, but with assembly references; maybe it makes sense to advice compiler to use any dll with "SpecificVersion" element in project file, such as:

&lt;Reference Include="AjaxMin, Version=4.19.4141.18463, Culture=neutral, PublicKeyToken=24297a69a7eae424, processorArchitecture=MSIL"&gt;
      &lt;SpecificVersion&gt;False&lt;/SpecificVersion&gt;
      &lt;HintPath&gt;....\Solution\Usadba\packages\AjaxMin.4.19.4141.18463\lib\AjaxMin.dll&lt;/HintPath&gt;
&lt;/Reference&gt;

I found this stackoverflow question about this topic:
http://stackoverflow.com/questions/1063459/net-reference-specificversion-true-or-false

But I'm afraid to say I have a problem with reproducing this issue... right now Cassette works just fine with AjaxMin 4.19 both on Dev and Staging (win 2008) environment. Can't say what changed...

<b>smnbss</b>,
Thank you for advice, but such way of assemble redirection should be set in every Web.config in every project which uses Cassete, which can be a bit boring :)

**Comment by smnbss** [comment]
It can be done by the same merge that adds the configuration for cassette to the web.config. I've seen other NuGet packages working like that.

sometimes the problem happens if you reference 3rd party libraries that reference a specific version of a dll, while you reference a different version from your library. it can get quite complex, so assemblyBinding solve the problem in that specific case

**Comment by andrewdavey** [comment]
Can the binding redirect specify a non-fixed upper bound? Otherwise we have the same problem when AjaxMin gets updated to a new version and the redirect still points to an older version.

I will have a look at setting Specific Version = False and changing the AjaxMin dependency to something like [4-5). Since I'd rather let nuget satisfy the versioning.

**Comment by kaatula** [comment]
I was not right in my comment below, the reference which I quoted is actually going to point only 4.19 always (it appears SpecificVersion works only on compile time, not execution-and-assembly-search time)

Maybe it makes sense to make a reference in csproj file without versions at all:

```
  <Reference Include="AjaxMin">
      <HintPath>....packages\AjaxMin.4.13.4076.28499\lib\AjaxMin.dll</HintPath>
  </Reference>
```

(with no version at all)
I also agree that it's better to let NuGet care about setting minimal required version.

Thanks
