### ISSUE TITLE
Nested dotLess @imports can cause "Index was outside the bounds of the array." exception

### ISSUE THREAD

**Issue by cafedomingo** [andrewdavey/cassette#161]
Some instances when using Cassette with nested, imported less files there seems to be an issue in the less compilation. The stack trace from the issue is as follows. A sample project to reproduce the error can be found here: https://github.com/justanothersunday/CassetteTest. One of the files in the sample works, the other does not. Both do properly compile to css from the command line tool (v.1.2.2.0) found here: https://github.com/dotless/dotless/downloads

---

[IndexOutOfRangeException: Index was outside the bounds of the array.]
   Jurassic.Library.<get_Ranges>d__3.MoveNext() +355
   Jurassic.Library.SparseArray.CopyTo(SparseArray source, UInt32 start) +322
   Jurassic.Library.ArrayInstance.Concat(ObjectInstance thisObj, Object[] items) +1797
   binder_for_ArrayInstance_Concat(ScriptEngine , Object , Object[] ) +125
   Jurassic.Library.FunctionBinder.Call(ScriptEngine engine, Object thisObject, Object[] arguments) +239
   Jurassic.Library.ClrFunction.CallLateBound(Object thisObject, Object[] arguments) +250
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +8555
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +103
   Jurassic.Library.FunctionInstance.Call(Object thisObj, Object[] arguments) +42
   binder_for_FunctionInstance_Call(ScriptEngine , Object , Object[] ) +222
   Jurassic.Library.FunctionBinder.Call(ScriptEngine engine, Object thisObject, Object[] arguments) +239
   Jurassic.Library.ClrFunction.CallLateBound(Object thisObject, Object[] arguments) +250
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +6269
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +103
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +365
   Cassette.Stylesheets.CompileResult.CallLateBound(Object thisObject, Object[] argumentValues) +185
   anonymous(ScriptEngine , Scope , Object , FunctionInstance , Object[] ) +17333
   Jurassic.Library.UserDefinedFunction.CallLateBound(Object thisObject, Object[] argumentValues) +103
   Jurassic.Library.ObjectInstance.CallMemberFunction(String functionName, Object[] parameters) +365
   Cassette.Stylesheets.LessCompiler.CompileImpl(String lessSource, IFile file) +286
   Cassette.Stylesheets.LessCompiler.Compile(String lessSource, IFile sourceFile) +229
   Cassette.BundleProcessing.<>c__DisplayClass1.<Transform>b__0() +164
   Cassette.Stylesheets.ExpandCssUrlsAssetTransformer.ReadCss(Func`1 openSourceStream) +70
   Cassette.Stylesheets.<>c__DisplayClass1.<Transform>b__0() +104
   Cassette.AssetBase.OpenStream() +148
   Cassette.Web.AssetRequestHandler.SendAsset(HttpRequestBase request, HttpResponseBase response, Bundle bundle, IAsset asset) +302
   Cassette.Web.AssetRequestHandler.ProcessRequest(HttpContext _) +447
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +100
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

**Comment by andrewdavey** [comment]
I've decided that working with less.js inside of Jurassic is too hard. Let's instead use dotless. It's C#, so should be much easier to debug and probably faster too.

I've created this branch that replaces less.js with dotless:
https://github.com/andrewdavey/cassette/tree/dotless

I couldn't directly reference the actual dotless library because it depends on asp.net (Cassette's core library doesn't). Instead I pulled out the less compiler source code and add it to a new project in the Cassette solution.

Can you try pulling down the dotless branch and seeing if it works for you? My brief testing with your sample Less files seems to work for me now.

**Comment by cafedomingo** [comment]
I integrated this branch into my project in place of the nuGet package and everything is working as expected. As a bonus, any less compilation errors that do come up seem to throw more informative exceptions and makes tracking down the cause of the error easier. Do you think you'll be integrating this into the 1.1 release version?

Thanks for the quick response!

**Comment by andrewdavey** [comment]
Excellent. Thanks for testing. Yes, this will be in 1.1.0 release

**Comment by cafedomingo** [comment]
As I was doing additional testing, it seems that this compiler does behave a bit differently when evaluating paths within less files.

Using the less.js compiler, when you imported another less file relative paths (for example in a url() for a background image) were output exactly as specified. This was fine if the file doing the importing was in the same directory as the file it was importing, but would result in incorrect paths in if not. The workaround we were using for this was to specify a variable for the absolute path at the top of the imported file and make all of the paths absolute.

Using the dotLess compiler, the relative paths from the import are pre-pended to urls, seemingly even if the path is absolute. This resulted bad paths (for us) though ultimately, I think this will be preferable behavior (assuming it would respect absolute paths). This means that when you import a less file in a different directory, that file can still reference other files with a relative path and the output will still be correct.

My apologies if this is a bit confusing to follow. I've been pretty busy the last few days, but I'll try to put something together to isolate and demonstrate the issue. I'm not sure that it's really a problem, but since it seems to be a change in behavior I figured it was worth pointing out.

**Comment by andrewdavey** [comment]
I've seen other differences in behaviour between less.js and dotless. Nothing really to worry about it seems, but worth letting people that they'll need to watch out for issues.

Re image paths: does using something like `url(../images/test.png)` with `..`'s work for you? I try to avoid absolute paths where possible.

It sounds like creating some unit tests to document the behaviour is best. Also updating the Less page in the getcassette.net docs too would be good.
