### ISSUE TITLE
HtmlTemplate duplicate key bug

### ISSUE THREAD

**Issue by MattsGitCode** [andrewdavey/cassette#164]
I've come across a problem with the HTML template bundle though that causes a "key already exists in dictionary" error when the templates have a HTML extension. It seems to be to do with the search patterns - I think *.htm is also picking up those with the extra L at the end, causing files to be added into the bundle twice.

**Comment by andrewdavey** [comment]
Fixed in b36f5e8c8487429b277ef876909a82a73e7eb867
