### ISSUE TITLE
Less compile error

### ISSUE THREAD

**Issue by jincod** [andrewdavey/cassette#165]
I'm using less from twitter bootstrap 2.0. 
Code:

```
Bundles.Reference("/Content/bootstrap/bootstrap.less");
...
@Bundles.RenderStylesheets()
```

![GitHub Logo](http://www.dropmocks.com/iBgeUb)
Screenshot: http://www.dropmocks.com/iBgeUb

**Comment by andrewdavey** [comment]
I've created a new branch https://github.com/andrewdavey/cassette/tree/dotless that changes the Less compiler. It should fix problems like this.

Can you try it out and let me know if it works for you? I'll get it merged into the next release if everything looks good.

**Comment by jincod** [comment]
This not works too. May be parse directive  @import "filename.less" work incorrect? (bootstrap.less  https://github.com/twitter/bootstrap/blob/master/less/bootstrap.less) 
![GitHub Logo](http://www.dropmocks.com/iBgaiu)

**Comment by andrewdavey** [comment]
You need to tell Cassette to only bundle the main bootstrap.less file. This main Less file then imports the others. So Cassette must not then try to bundle them as well.

To do this, change your `CassetteConfiguration` to include something like:

```
bundles.Add<StylesheetBundle>("Content/bootstrap/bootstrap.less");
```

**Comment by andrewdavey** [comment]
Sorry, I put the wrong issue number on that commit.

**Comment by jincod** [comment]
It works for me. Thx
