### ISSUE TITLE
Investigate backporting Cassette to .NET 3.5

### ISSUE THREAD

**Issue by kamranayub** [andrewdavey/cassette#168]
I am doing this right now; I want to make sure the required tests pass. Using this issue to track against it and for comments.

You can view progress at [kamranayub/cassette/tree/dotnet-35](https://github.com/kamranayub/cassette/tree/dotnet-35).
## Progress
- ~~Cassette core project builds and passes unit tests.~~ (Done)
- ~~Cassette.Web supports .NET 3.5~~ (Done)
- ~~Cassette.Views supports .NET 3.5~~ (Done)
- ~~All projects use directives to turn on/off workarounds~~ (Done)
  - I haven't ever done this before so this might take a bit of playing around
- ~~Add 3.5 compilation to build.bat~~ (Done)
- ~~Create a .NET 3.5 example site~~ (Done)
- ~~Add documentation to Cassette website project~~ (Done)
- ~~Figure out a way to pack both frameworks into each package~~ (Done)
- ~~Finalize changes and docs~~ (Done)
- ~~Submit pull request~~ (Done) See #191
## Issues
- Supporting Isolated Storage is possible in .NET 3.5, but I had to do an ugly workaround for LastWriteTimeUtc.
- .NET 3.5 doesn't like it when you use an `Action<ScriptBundle>` with the bundle collection extensions; I worked around this by just using a lambda inline for unit testing.
- ~~.NET 3.5 can't utilize WebActivator. We may need manual instructions for that.~~ Will document how to do it in 35.
### LastWriteTimeUtc

In Fx35, you can't get last write time off an IsolatedStorageFile. Instead, what I did was creating an index file in isolated storage. When a file is new'd up, it writes in the current UTC date for the filename. Any time the stream is opened for write, it also writes the current time. This is super ugly but it seems to work; when a file is deleted it is removed from the index.

The unit tests uses a ShouldBeInRange check of 500ms to be reasonably sure the index was written close to the same time as the file was created/modified.

**Comment by andrewdavey** [comment]
Thanks for working on this! There will be many happy .NET 3.5 people out there :)

Re: LastWriteTimeUtc in isolated storage
I don't think Cassette's new bundle manifest code ever asks isolated storage files for LastWriteTimeUtc. So you may be able to drop the clever workaround and just throw NotImplementedException instead.

**Comment by kamranayub** [comment]
@andrewdavey, is this in the master branch right now? I do see references to LastWriteTime in `AssetManifest.cs` and I just merged master into my branch.

**Comment by andrewdavey** [comment]
Yes, but I think the `IFile` there is a `FileSystemFile`.

**Comment by kamranayub** [comment]
OK, well, I can definitely change it to throw an NotImplEx. I will do that once I get an example site running 3.5.

**Comment by kamranayub** [comment]
Submitted pull request.
