### ISSUE TITLE
Expose UrlGenerator

### ISSUE THREAD

**Issue by SLaks** [andrewdavey/cassette#173]
Cassette's UrlGenerator should be exposed for direct consumption within views.

It would very really cool to write

```
<img src="@Url.Cassette("~/Content/Logo.png") alt="My cool logo" />
```

And automatically get a cached, versioned URL.

Beware of file disclosure vulnerabilities; you may want to require directories or files to be whitelisted in CassetteConfiguration.

**Comment by SLaks** [comment]
You can do this with an extension method:

```
public static string CachedUrl(this UrlHelper url, string path) {
    return CassetteApplicationContainer.Application.Settings.UrlGenerator.CreateRawFileUrl(
        path,
        HashFileContents(url.RequestContext.HttpContext.Server.MapPath(path))
    );
}
static string HashFileContents(string path) {
    using (var fileStream = File.OpenRead(path)) {
        return fileStream.SHA1Hash().ToHexString();
    }
}
static byte[] SHA1Hash(this Stream stream) {
    using (var sha1 = new SHA1Managed()) {
        return sha1.ComputeHash(stream);
    }
}
static string ToHexString(this IEnumerable<byte> bytes) {
    return string.Concat(bytes.Select(b => b.ToString("x2")));
}
```

The three helper methods were copied from various places in Cassette source.

**Comment by andrewdavey** [comment]
We need a way to create the white list. Any files referenced by assets are already safe, but we'll probably want more than those.

Would adding this to CassetteSettings make sense?

```
settings.AllowRawFileAccess("~/path/to/file.png");
settings.AllowRawFileAccess(path => path.StartsWith("~/path"));
```
