### ISSUE TITLE
External css references are not working as expected

### ISSUE THREAD

**Issue by jgeurts** [andrewdavey/cassette#179]
I have a css file that has the following references at the top:

/*
@reference //twitter.github.com/bootstrap/assets/css/bootstrap.css
@reference ~/Content/css/Shared/global.css
@reference //ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css
*/

Only the global.css is getting pulled into the final rendered page.

**Comment by andrewdavey** [comment]
Good catch! Thank you.

This fix will be in the next release.

**Comment by jgeurts** [comment]
Awesome, thanks!
