### ISSUE TITLE
File disclosure vulnerability in RawFileRequestHandler

### ISSUE THREAD

**Issue by SLaks** [andrewdavey/cassette#185]
RawFileRequestHandler is used to served cached and versioned copies of image / font files referenced by CSS files.

However, it does no path validation, so it can be used to read any source file in the website.

To fix this, Cassette.Web should maintain a whitelist of allowed RawFile paths.
This should be pre-populated with all AssetReferences from registered bundles.
It should also be extensible to allow people to [use cached files indepedently](https://github.com/andrewdavey/cassette/issues/173).
That should probably look something like

```
CassetteConfiguration.AllowRawFile(string path, IFileSearch fileSearch = null)
```

where `path` can be a file or a directory.

**Comment by SLaks** [comment]
This could also be fixed by verifying the hash in RawFileRequestHandler.  
This would prevent attackers from seeing files unless they already know the file's hash (although it would allow them to brute-force the hash).

However, this would turn old URLs with incorrect hashes into 404s.

**Comment by andrewdavey** [comment]
This will be fixed asap and in the next release. Thanks for bringing
this to my attention.

**Comment by andrewdavey** [comment]
The above commit should fix the issue in the 1.0.1 version. Only raw files referenced from assets can be served.

@SLaks can you take a look please? If it's all good I'll release Cassette 1.0.2 as a drop in update for anyone using 1.0.1.

I'll then also merge this into master for 1.1.

**Comment by andrewdavey** [comment]
An extensible white-list of allowed files can be added later, probably in conjunction with implementing #173

**Comment by SLaks** [comment]
Looks OK
