### ISSUE TITLE
After upgrading to 1.0.2, images all return 404

### ISSUE THREAD

**Issue by patrickleet** [andrewdavey/cassette#188]
/_cassette/file/ux/css/base/jquery-cnv-ui/images/ui-bg_flat_0_fef1ec_40x100_d4d3132654ae1b97bea57aa7f0feb6bca12fc4a9_png

Never had a problem with before upgrading..

**Comment by patrickleet** [comment]
Clearing the cache seems to fix this, but every time I make a change to a css file, it happens again, thus defeating one of the major purposes of cassette

**Comment by tomdenny** [comment]
This sounds a lot like issue #187

**Comment by andrewdavey** [comment]
I'm looking into this. I'll find out what I broke in the update!

I assume you were on 1.0.1 before?

**Comment by andrewdavey** [comment]
Cassette 1.1.0 is now available via nuget and should resolve this issue.
