### ISSUE TITLE
FileNotFound Issue

### ISSUE THREAD

**Issue by rojorojo** [andrewdavey/cassette#189]
According to the documentation this is the correct way to handle bundling multiple files:

var jFiles = new[] {
                "Scripts/jquery-1.6.2.min.js",
                "Scripts/jquery.reveal.js",
                "Scripts/modernizr.custom.91789.js",
                "Scripts/jquery.validate.js"
            };
            bundles.Add<ScriptBundle>("scripts", jFiles);

This works work stylesheets but results in a FileNotFound error for scripts. However, adding the ~/ seems to work like so...

var jFiles = new[] {
                "~/Scripts/jquery-1.6.2.min.js",
                "~/Scripts/jquery.reveal.js",
                "~/Scripts/modernizr.custom.91789.js",
                "~/Scripts/jquery.validate.js"
            };
            bundles.Add<ScriptBundle>("scripts", jFiles);

**Comment by andrewdavey** [comment]
Because the "scripts" directory exists Cassette is treating your paths as relative to that directory. Try this instead:

```
var jFiles = new[] {
"jquery-1.6.2.min.js",
"jquery.reveal.js",
"modernizr.custom.91789.js",
"jquery.validate.js"
};
bundles.Add("scripts", jFiles);
```

Adding the ~/ prefix forces them to be app relative.

I'm sorry I didn't see this before. I'll leave this issue open as a reminder to improve the documentation.

**Comment by rojorojo** [comment]
Ah! So Cassette was actually trying to simplify my life! 
I have tested this and it works. So for stylesheets, does Cassette look for a "Styles" folder? Or no?

**Comment by andrewdavey** [comment]
There shouldn't be any different behaviour for stylesheets. If the "Styles" directory exists then the file paths can be relative to it. But, for example, if you've put css files into the "Content" directory, but the bundle path is "styles" then you will need to use absolute "~/Content/file.css" paths.

Essentially: `bundles.Add(PATH, files);` will alter it's behaviour depending on if the `PATH` directory exists.
