### ISSUE TITLE
HTML Templates rendered inline w/o <script> tag in production mode

### ISSUE THREAD

**Issue by christophercliff** [andrewdavey/cassette#190]
After merging latest security patch.

If you set `<compilation debug="false">` in web.config, template bundles are rendered inline as plain text, not wrapped w/ `<script>` tags.

Failing with both Hogan and jQuery pipelines.

Example in the Backbone project:

https://github.com/andrewdavey/cassette/blob/master/examples/Backbone/Views/Home/Index.cshtml

**Comment by andrewdavey** [comment]
I'm looking into this now.

**Comment by andrewdavey** [comment]
The latest in `master` now persists the rendered HTML elements in the cache. This should fix the problem and give us a nice perf boost :)

Can you test it as well please and report back? Thanks

**Comment by christophercliff** [comment]
Great, will test it first thing Monday.
