### ISSUE TITLE
Precompiled manifest breaks Html Rewriting

### ISSUE THREAD

**Issue by hempels** [andrewdavey/cassette#196]
When a precompiledManifest is not specified and rewriteHtml is true, it is possible to reference additional script and style resources within a Partial (MVC Razor view engine.)

If you then specify a precompiledManifest, rendering the same partial within the same page will produce the following error:
**Cannot add a bundle reference. The bundles have already been rendered. Either move the reference before the render call, or set ICassetteApplication.IsHtmlRewritingEnabled to true in your Cassette configuration.**

I suspect the value is rewriteHtml is forced to false when a precompiledManifest is located, but it doesn't seem like there is a technical reason why it needs to be.

**Comment by andrewdavey** [comment]
Good catch, thanks.

This should be an easy fix. I'll get it into the next release.

**Comment by andrewdavey** [comment]
The above commit should fix this issue.

**Comment by andrewdavey** [comment]
Available in v1.2.0
