### ISSUE TITLE
bundle.txt does not override <reference> tag in .js file

### ISSUE THREAD

**Issue by tkarpinski** [andrewdavey/cassette#198]
I've created a sample repository which exhibits this problem.

If CassetteConfiguration.cs is configured to add the ScriptBundle per subdirectory, the subdirectory contains a bundle.txt file, and a file within the subdirectory uses a `/// <reference path="jquery-1.5.1.js" />`, as well, the bundle.txt is ignored and cassette throws an exception, which appears to be in conflict with this [statement](http://getcassette.net/documentation/configuration/bundle-descriptor-file#comment-428433339)

example repo here: https://github.com/tkarpinski/cassette-testing

**Comment by andrewdavey** [comment]
Thanks. I'll look into this.

**Comment by andrewdavey** [comment]
To clarify, `Scripts/jquery.validate.unobtrusive.js` is referencing a file that does not exist.

Because there is a `bundle.txt` present Cassette should not scan assets for reference comments and solely rely on the `bundle.txt` ordering.

I think it already ignores the references for ordering purposes. It's just the parse stage throwing due to file not found.

**Comment by tkarpinski** [comment]
is this something you think should be addressed?  Benefit here would be that nuget packages wouldn't need to be modified in order to work with updated jquery (probably the case for 99% of the times you'd run into this).  Most packages don't update a file if you've modified it, so if we can workaround this, I think that would be a win.

**Comment by andrewdavey** [comment]
Cassette really should work without requiring changes to third-party scripts. Using bundle.txt provides simple way to do this. So it's just a matter of telling Cassette to ignore reference errors.

I'll get this issue fixed in the next release.
