### ISSUE TITLE
Dependencies between JS and CSS

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#2]
JavaScript libraries such as jQuery UI require CSS to render correctly. So perhaps allow a JS file to reference a CSS file. Then the page only needs to reference the JS file and the required CSS module is also added.

**Comment by sfmskywalker** [comment]
That would seem like a great idea, but what about custom jquery UI CSS files that include both core CSS as well as theme specific CSS. Then imagine I have an application where I want the user to be able to pick different themes.
I would dynamically reference the correct jquery UI css files, but always reference the same jquery-ui.js file (although one might argue that the core jquery-ui CSS files should not be in the same file as the theme specific CSS files, but when building a custom jQuery UI package, I usually always include the single css file that includes everything I need.

**Comment by andrewdavey** [comment]
Version 0.9 has a unified bundle container and so allows references between different types of bundles.
