### ISSUE TITLE
Config support for generating CDN-friendly URLs

### ISSUE THREAD

**Issue by KyleK123** [andrewdavey/cassette#20]
It would be nice if you could have a configuration setting to specify that the URLs generated from:

string DebugScriptUrl(Asset asset)
string ReleaseScriptUrl(Asset asset)

have a prefix such as http://static.myDomain.net/...........

rather than always being virtual paths (~/Scripts/) that get converted to app relative paths.

**Comment by andrewdavey** [comment]
This feature will be possible by providing a custom `IUrlGenerator` to the `ICassetteApplication` instance. I will need to document this.

**Comment by andrewdavey** [comment]
In the application `CassetteConfiguration` class `Configure` method:

```
application.UrlGenerator = new UrlGenerator("http://static.mydomain.net");
```

That will prefix generated URLs with the given string.

**Comment by rodmjay** [comment]
I can't figure out how to set this.  I'm assuming in IConfiguration<> something, but what?

**Comment by andrewdavey** [comment]
This changed in v2. Try something like this:

```
public class ContainerConfig : IConfiguration<Cassette.TinyIoC.TinyIoCContainer>
{
    public void Configure(TinyIoCContainer container)
    {
        container.Register<IUrlGenerator>(...);
    }
}
```

Also take a look at https://github.com/andrewdavey/cassette/blob/master/src/Cassette/HostBase.cs#L110 to see the default registration.
