### ISSUE TITLE
Empty assets in bundle.txt ignores bundle

### ISSUE THREAD

**Issue by tomdenny** [andrewdavey/cassette#202]
In V1.1.0 the following bundle.txt no longer works when there are no assets in the directory:

```
[external]
url = //ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/themes/redmond/jquery-ui.css

[assets]
*
```

The bundle isn't created.

I haven't explored the cause yet -- it's too easy to fix by moving the external reference to the configuration instead of the bundle.txt.

**Comment by andrewdavey** [comment]
This should be fixed in `master`.
