### ISSUE TITLE
background url resource not found on live server

### ISSUE THREAD

**Issue by joakimfischer** [andrewdavey/cassette#203]
I think I have two connected issues here.

1) Locally both debug=true and debug=false works fine. On the server, only debug=false works. When having debug=true I get 404 errors accessing all assetts.

2) When I add css "background: url(/images/bg.png) repeat;" It works fine locally in both debug modes but on the server I get 404 on the generated reference (/_cassette/file/images/bg_b009fab58d6c18cef80fa21f67c4e8df191054a7.png)

Is this some kind of permission issue on the server maybe? or is this a common error. I first had my project as a Asp.Net Website but changed it to a Asp.Net Web Application to check if that was causing the issue some way.

I have a third issue that I dont think is related but there is a small chance so I will post it in this same thread.

3) If I change a javascript file or css and upload it to the server, noting happens at first. The bundles isnt updated. My solution have been to change in web.config to debug=true, call site, change back to degug=false, then call site and it works again. I figure the project need a web.config-change to know it needs to recompile or something.. is there a simplier way to do this? I have tryied restarting in IIS but that didnt work.. and isn't really a better solution either.

Thanks for a great project so far though. Its a bit hard to debug issues that appears but otherwise it seems really promising.

**Comment by thecontrarycat** [comment]
Re: Point 3, I asked a similar question to Andrew on twitter earlier this week.  It seems that cassette only watches the filesystem if one of the following is true:

1) cassette < cassette watchFileSystem="true" / >
2) asp.net < compilation debug="true" >

Curiously, < cassette debug="true|false" / > has no effect on this (although, like other cassette features, this should probably be checked for before falling back to the asp.net compilation element).

**Comment by joakimfischer** [comment]
Seems like you comment isn't rendering correct but I did see it in the mail I got :) 

Point 3 isn't really a problem anymore. When I publish the project and repleace all files it seems ok. So its mostly 1&2 that I would like answered.

**Comment by andrewdavey** [comment]
Make sure your web.config has the `runAllManagedModulesForAllRequests` attribute set:

```
<system.webServer>
    <modules runAllManagedModulesForAllRequests="true">
    ...
```

Otherwise a request for a ".png" file, for example, does not get passed to ASP.NET and Cassette's handler.

**Comment by andrewdavey** [comment]
Cassette's default behaviour in production mode is to not watch for file system changes. So just uploading a new css or js file does not trigger any rebuilding of bundles.

Touching web.config causes your application to restart. Cassette's initialization routine checks for changes to bundle files. If it finds files newer than the cached bundles then it rebuilds the cache.

I think most production deployments trigger an application restart, so the above should work. However, please let me know if there is a greater need for file system watching in production.

**Comment by joakimfischer** [comment]
Great. "runAllManagedModulesForAllRequests" was all that was needed, thanks. Maybe that should be included in the nuget Cassette.Web installation?

Regarding the problem with application-restart I figured as much. I have no problems with it now since I decided to compile the project locally before uploading it to server.

Thanks for the comprehensive answers!

**Comment by andrewdavey** [comment]
Adding `runAllManagedModulesForAllRequests` to the nuget package's web.config transform does make sense. I'll get that into the next release.
