### ISSUE TITLE
The process cannot access bundle file when web garden is setup

### ISSUE THREAD

**Issue by klalex** [andrewdavey/cassette#205]
Hello,

I faced with strange error after I setup web garden on IIS 6 to use more than 1 process. Sometimes I see exception "The process cannot access the file '.bundle' because it is being used by another process."

Any ideas how to fix it?

Thanks.

**Comment by andrewdavey** [comment]
Are you using Cassette 1.1.0?

**Comment by klalex** [comment]
I use version 1.0.1.20979. Will try to upgrade now. Thanks!

**Comment by dylanclementas** [comment]
I saw this issue on v2.0.0.28805, my guess is there must have been a request during deployment that kept the file open. Restarting the server seems to fix it.

**Comment by sergei-startsev** [comment]
I also saw this issue with Cassette.Aspnet 2.0.0 and restarting the server resolved this problem too.
