### ISSUE TITLE
Cassette with T4MVC and virtual directory

### ISSUE THREAD

**Issue by robertbird** [andrewdavey/cassette#209]
Hi,

I have an issue when using cassette in conjunction with T4MVC when hosted in a virtual directory. I'd like to be able to 
reference my scripts and stylesheets without using paths as string and instead use the T4MVC objects.

i.e. Bundles.Reference(Links.Content.styles_css);

However when this runs in a virtual directory, T4MVC resolves to an absolute URL. 

i.e. /myvirtualdir/content/styles.css

This throws a connot be found error in cassette (probably fair enough). So it's probably more of an issue with T4MVC.

But are there any ideas of how I can get these two to play nicely together?

Cheers,
Rob

**Comment by andrewdavey** [comment]
Cassette expects paths to be application relative i.e. without the virtual directory prepended.

Can you change your T4MVC template to exclude the virtual directory from the constants?

**Comment by robertbird** [comment]
I appreciate this is really a problem with T4MVC and not cassette - Thanks for the response Andrew. 

Just a shame, as I like the way T4MVC allows me to eliminate strings like paths in my code.

Great work with Cassette though - it's working really well for us so far!
