### ISSUE TITLE
Coffeescript and Mindscape Web Workbench and referencing dependent scripts

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#21]
I installed Mindscape Workbench to support Coffeescript.
Now I understand that Cassette is able to compile .coffee files into  .js files, which is great.
However, the Mindscape Workbench alread generates a .js file at design time.

Now I could directly reference the generated .js file (using Assets.Scripts.Reference()), but I'm not sure how to declare dependent scripts in my .coffee file. The Mindscape Workbench doesn't put # comments into the .js file.

So I thought I would reference the .coffee file directly and let Cassette handle the compilation so that the # reference  statement works.
That works great, however, Cassette includes both it's own version of the generated .js file as well as the design-time generated /js file by Mindscape Workbench.

Any tips on how to resolve this?

Thanks

**Comment by sfmskywalker** [comment]
I could uninstall Mindscape Workbench, but then I would loose SASS as well.

**Comment by andrewdavey** [comment]
You can stop Mindscape generating the JavaScript for each .coffee file. Select the .coffee files in solution explorer, then press F4 to open the properties window.
Clear the "Custom Tool" property. This should get rid of the generated JavaScript. You can let Cassette generate the JavaScript for you, while still keeping the Mindscape syntax highlighting :)

**Comment by sfmskywalker** [comment]
You're right, works like a charm :) Thanks!
