### ISSUE TITLE
CDN issue with cassette.xml cache file and a UrlModifier

### ISSUE THREAD

**Issue by pbering** [andrewdavey/cassette#211]
Using Cassette v1.2.0.

In the cassette.xml cache file, the hostname part of a bundle uri is being rewritten to 127.0.0.1!

Steps to reproduce:
1. Change bundle uri with a UrlModifier, fx the hostname to a CDN
2. Deploy and refresh site
3. Observe that your new hostname is used in cassette.xml
4. Make a CSS change, deploy and refresh
5. Observe that the hostname is now 127.0.0.1

Notes: 
- When the cassette.xml exists, then the CassetteConfiguration is not loaded and neither is the UrlModifier so It is now our UrlModifier that does the 127.0.0.1 rewrite.
- Even making sure that our assembly changes AssemblyVersion on each build to force the cassette.xml to expire, we still get 127.0.0.1
- When keeping the assemblyversion at 1.0.0.0 and only do a css change, I can see that the LastWriteTimeUtc is updated correctly, but we still see 127.0.0.1
- Seems that our only option is to delete the cassette.xml on deployments?

**Comment by andrewdavey** [comment]
I think the key issue here is that you need the `CassetteConfiguration` to be called even when loading from cache. Of course, we don't want to redefine the bundles. So how about something like:

```
public void Configure(BundleCollection bundles, CassetteSettings settings)
{
    settings.UrlModifier = new CustomUrlModifier();
    if (settings.IsLoadingFromCache) return;
    bundles.Add<ScriptBundle>("Scripts");
}
```

**Comment by pbering** [comment]
Looks great, it would properly do it. Is there anything I can do in the 1.2 version to fix it? What is it that rewrites the host in the cache file?

**Comment by pbering** [comment]
I did some more digging and found it that my UrlModifier was using HttpContext.Current.Request.Url.Hostname, which is 127.0.0.1 right after you do a change to a file in a bundle and rebuild/deploy! So cassette is actually calling the modifier correctly but the  HttpContext.Current.Request.Url is "broken" when it does... Is this expected behavior?

**Comment by andrewdavey** [comment]
Closing this issue because Cassette v2 has a new and improved approach to bundle caching and rebuilding.
