### ISSUE TITLE
Loosing the reference to Newtonsoft.Json & IOCing in different minifiers.

### ISSUE THREAD

**Issue by albertjan** [andrewdavey/cassette#214]
v2 is looking very promising I decided to go with that because adding the Cassette.Nancy package added such a long list of deps i got intimidated :).

I have two things though and I'm willing to help offcourse. 

The reference to Newtonsoft.Json for generating a bit of json in one spot of the application feels a bit off. There are some jsonserializers in the public domain that could be included in cassette and there is also one in .net that might be use-able.

I would like to try to externalize the minifier also. There are several options for it and people might want to use something else then AjaxMin. I believe there is also a minifier in the public domain that could be used so cassette doesn't have to use any remote deps.  You could offcourse use ajaxmin as a default in nuget. making cassette.web depend on it or something like it.

Let me know what you think.

**Comment by andrewdavey** [comment]
I've just pushed a commit to `v2` that removes `Newtonsoft.Json` and uses `SimpleJson` instead.

If you fancy adding support for other minifiers please go ahead. Personally, I'm very happy with AjaxMin. I like that it's all managed code.
