### ISSUE TITLE
Update Hogan.js to 2.0.0

### ISSUE THREAD

**Issue by kamranayub** [andrewdavey/cassette#215]
Let me know if I can override this locally, but right now Cassette is using 1.x.

It would be nice if we could point to the source file to use for this, perhaps?

http://twitter.github.com/hogan.js/builds/2.0.0/hogan-2.0.0.js

**Comment by Daniel15** [comment]
The version of Hogan is embedded in the Cassette codebase - https://github.com/andrewdavey/cassette/blob/master/src/Cassette.Hogan/Resources/hogan.js . You could fork Cassette, update it to use the latest Hogan version, and send it back as a pull request :)

**Comment by andrewdavey** [comment]
I've done this in the v2 branch.
