### ISSUE TITLE
Suport to silverlight

### ISSUE THREAD

**Issue by nmocruz** [andrewdavey/cassette#22]
When a add a silverligth application a get this error

[ArgumentException:  An item with the same key has already been added.]
   Cassette.Web.ExceptionCachedManager.CreatePageAssetManager(HttpContextBase httpContext) +75
   Cassette.Web.CassetteHttpModule.<Init>b__0(Object sender, EventArgs e) +118
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

**Comment by andrewdavey** [comment]
Have you updated to Cassette.Web v0.5.4?

**Comment by nmocruz** [comment]
i got the source yesterday, and the exception happens when this call:

UnresolvedModule.css - line 115

Asset[] OrderScriptsByDependency(Asset[] assets){
         var assetsByPath = assets.ToDictionary(asset => asset.Path, StringComparer.OrdinalIgnoreCase);
...
}

the assets array have 2 objects with the same path

I solve it with this :

```
        var assetsByPath = new Dictionary<string, Asset>();
        foreach (var item in assets)
        {
            if (!assetsByPath.ContainsKey(item.Path))
                assetsByPath.Add(item.Path, item);
        }
```

 but I dont now if is safe.
