### ISSUE TITLE
Ability to remove type attribute from script markup

### ISSUE THREAD

**Issue by jgeurts** [andrewdavey/cassette#220]
It would be nice to be able to omit the type="text/javascript" part from the rendered script tags.  You mentioned maybe adding the type attribute to the HtmlAttributes collection for scripts.  That would allow a bundle processor to be able to remove the "type" attribute from the HtmlAttribute dictionary.

**Comment by keithly** [comment]
This would be nice to have.

**Comment by curtisj44** [comment]
Same for the type attribute on link tags.

**Comment by andrewdavey** [comment]
Cassette v2 supports this. The `bundle.HtmlAttributes` collection is used to store all attributes, such as `type`, so it can be altered by a bundle processor.
