### ISSUE TITLE
Intermittent null placeholderTracker

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#221]
For one page in my application I consistently get a
NullReferenceException - stack trace below:

[NullReferenceException: Object reference not set to an instance of an object.]
  Cassette.ReferenceBuilder.Render(String location) +130
  Cassette.Views.Bundles.Render(String location) +87
  Cassette.Views.Bundles.RenderStylesheets(String pageLocation) +10
  Bluewire.Epro.UI.WebForms.PageResourceManager.RenderStyleSheets(HttpRequest
request) in C:\dev\epro\Web\AppCode\WebForms\PageResourceManager.cs:88
  Bluewire.Epro.UI.WebForms.PageHelper.PreRender(Object sender,
EventArgs eventArgs) in
C:\dev\epro\Web\AppCode\WebForms\PageHelper.cs:81
  System.Web.UI.Control.OnPreRender(EventArgs e) +92
  System.Web.UI.Control.PreRenderRecursiveInternal() +83
  System.Web.UI.Page.ProcessRequestMain(Boolean
includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
+974

This appears to be because placeholderTracker is null in the
ReferenceBuilder class. Looking in HttpContext.Current.Items there is
a PlaceHolderTracker instance there so for some reason it is not
getting passed to the referenceBuilder at construction time.

**Comment by andrewdavey** [comment]
Are you using Server.Transfer anywhere?

**Comment by willholley** [comment]
Not explicitly, but I am calling FormsLogin.RedirectFromLoginPage when
it breaks which presumably initiates a Server.Transfer under the hood?

On 29 March 2012 23:36, Andrew Davey
reply@reply.github.com
wrote:

**Comment by willholley** [comment]
Actually, I think this may be a red herring. My login page renders
without error but other pages do not, even when they are not going
through my explicit FormsAuthentication.RedirectFromLoginPage call.

**Comment by willholley** [comment]
I finally got to the bottom of this.

The application that I'm trying to integrate Cassette into registers scripts / stylesheets in page constructors (previously we had our own resource management classes but I am replacing them with Cassette). The constructors fire before the PostMapRequestHandler event and so the placeholderTracker has not been initialised yet.
