### ISSUE TITLE
Background-image CSS reference to image, isn't being changed to "_cassette/yadayada".

### ISSUE THREAD

**Issue by stapiagutierrez** [andrewdavey/cassette#227]
What's strange is that for the past three hours this has worked flawlessly.

Cassette changed my .CSS styles from this:

```
#header {
    background: url("/Public/images/logo.png") no-repeat;
```

To this:

```
#wrapper #header {
    background: url("/_cassette/file/Public/images/logo_81ab1e7f2fdb27c91a9e9b41eed420390e21f7e0.png") no-repeat;
```

This worked very well for the past hour. Suddenly I added a new image to my MVC3 application, to the same folder all of my images are in, and the CSS rule refuses to "compile" to what Cassette is supposed to do.

It stays on this:

```
background-image: url('/Public/image/ribbon.png');
```

Instead of being 

```
_cassette/file/yada yada.
```

Any ideas?

My web.config is set to debug=true; nothing is configured out of the ordinary, I'm using cassette pretty much at default settings.

Any suggestions?

**Comment by rojorojo** [comment]
I also am seeing this same problem as well. There is something going on with the cache. And rebuilding the cache does not help. It seems that Cassette is recognizing CSS changes elsewhere but when it comes to background images, it does not.

**Comment by andrewdavey** [comment]
This should be fixed in Cassette v2.
