### ISSUE TITLE
Cassette rendering some, but not all scripts

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#23]
After updating from cassette 0.5.2 to 0.5.4, Cassette suddenly stops rendering scripts from certain modules (I have 4 script modules, of which only one gets rendered).
I'm not sure what's going on, but stepping through the debugger shows me that Graph<T>.TopologicalSort returns only one path node, causing to only render a single module (the one that is defined with location="Head", all modules with location="Body" are not being rendered).

My web.config looks like this:

``` xml
<cassette moduleMode="OffInDebug">
    <scripts>
        <add path="Scripts/libs" location="Body"/>
        <add path="Scripts/app" location="Body"/>
        <add path="Scripts/ui" location="Body"/>
        <add path="Scripts/enhancements" location="Head"/>
    </scripts>
    <styles>
      <add path="Content" />
      <add path="Areas" />
    </styles>
    <htmlTemplates>
    </htmlTemplates>
  </cassette>
```

My view looks like this:

``` html

@{
    Assets.Scripts.Reference("scripts/libs/plugins.js");
    Assets.Scripts.Reference("scripts/enhancements/modernizr-2.0.6.js");
    Assets.Scripts.Reference("scripts/ui/panelbarmenu.js");
    Assets.Scripts.Reference("scripts/app/init.coffee");
    Assets.Scripts.Reference("scripts/ui/tabstrip.coffee");
    Assets.Scripts.Reference("scripts/ui/cssbehaviors.coffee");
}
<!doctype html>
<head>
    @Assets.Scripts.Render("Head")
</head>
<body>
    @RenderBody()
    @Assets.Scripts.Render("Body")
</body>
</html>
```

I'm clueless, so hopefully you see what's going on.

Thanks!

**Comment by andrewdavey** [comment]
I'm unsure if the paths are case sensitive. Try making sure the paths exactly match the casing of the file system e.g. Scripts or scripts, etc.

**Comment by sfmskywalker** [comment]
You're right, that fixes it! :) Thanks!

**Comment by andrewdavey** [comment]
Cassette really should provide a better error message for this situation, or maybe even allow case-insensitive path comparisons.

**Comment by sfmskywalker** [comment]
True. I think that allowing case-insensitve path comparisons makes more sense since nowhere in the ASP.NET platform does case matter when it comes to paths.
