### ISSUE TITLE
Need a generic Bundles.Reference

### ISSUE THREAD

**Issue by normallywho** [andrewdavey/cassette#230]
In cases where an external URL is being referenced and it isn't clear what type of resource is being referenced, Cassette throws the error:

Cannot determine the type of bundle for the URL "https://someurl.com". Specify the type using the generic type parameter.

**Comment by andrewdavey** [comment]
We need:

```
Bundles.Reference<ScriptBundle>("http://someurl.com/where/theres/no/file/extension");
```

Without the generic parameter, and the URL having no file extension Cassette can't figure out the type of bundle to create.
