### ISSUE TITLE
Bundle alias is not app relative

### ISSUE THREAD

**Issue by normallywho** [andrewdavey/cassette#231]
Adding an external script with an alias requires the alias to be referenced as:

Bundles.Reference("~/myscriptalias");

instead, it should be assumed to be app relative.

**Comment by andrewdavey** [comment]
I can't reproduce this on the current v2 branch. Can you also show me the bundle configuration code you used? Also the exception stack trace would be useful. Thanks.

**Comment by normallywho** [comment]
I think you asked that I post this early on when I was still getting a grip on Cassette while we were talking in IRC. Now that I've worked with it a bit, I'm not sure this is accurate. I'm using v1 (v2 has only just been integrated for a future branch) right now and when I use AddUrlWithAlias with an internal script I have to create the bundle like this:

bundles.AddUrlWithAlias<ScriptBundle>("/Portal/Scripts/jqueryui/jquery-ui.min.js", "~/jqueryui");

But when I reference the bundle, it's like this:

Bundles.Reference("jqueryui");

Referencing an external script I'll use this:

bundles.AddUrlWithAlias<ScriptBundle>("http://www.someurl.com", "somealias");

And then the matching reference would be:

Bundles.Reference("somealias");

So the noteworthy bit is that, when referencing an internal script with AddUrlWithAlias I have to provide the alias as "~/someinternalscriptalias" but I can reference it normally in the actual cshtml pages.

Looking in v2, it looks like the "~/" isn't necessary when creating the alias. I would probably say this can be closed.
