### ISSUE TITLE
rendering cassette output before handler mapping / execution

### ISSUE THREAD

**Issue by matt-mercer** [andrewdavey/cassette#233]
bit of an edge case, but using cassette 1.2.0
In my global exception handling, I'm basically sneakily rendering a view to splurge out a pretty error page with appropriate status codes ..

eg.

Application_Error()
{
            mvcContext.RouteData.Values["controller"] = errorControllerName;
            mvcContext.RouteData.Values["action"] = errorActionName;
            mvcContext.RouteData.Values["StatusCode"] = httpError.GetHttpCode();
            mvcContext.RouteData.Values["StatusDescription"] = httpError.Message;
            var controller = controllerFactory.CreateController(mvcContext, errorControllerName);
            controller.Execute(mvcContext);
}

now generally this works nicely with cassette ... 
with the exception that there are scenarios when an exception is throw before OnPostMapRequestHandler  ..
in these cases  the CassetteApplication.OnPostMapRequestHandler and CassetteApplication.OnPostRequestHandlerExecute  hooks are not getting executed ...  (and rightly so)

we found a workaround ( using reflection to invoke the methods against cassette application, ) to simulate the pipeline stages (before and after the exception rendering ..) ... 

Issue I'm raising ( at AD's request ) is just a reminder to make sure there is a way to manually invoke the cassette pipeline stages if needed :)

kind regards
Matt Mercer

**Comment by andrewdavey** [comment]
I'm working on the Cassette v2 API at the moment. It's looking something like this:

```
var rewriter = CassetteHttpModule.Host.CreatePlaceholderRewriter();
rewriter.AddPlaceholderTrackerToHttpContextItems(); // Call this before executing your view
rewriter.RewriteOutput(); // Call this after executing the view - it installs the response filter
```

**Comment by matt-mercer** [comment]
superb :)
