### ISSUE TITLE
Relative urls in css files should be rewritten when served through cassette

### ISSUE THREAD

**Issue by DouglasLivingstone** [andrewdavey/cassette#234]
If a css file uses a relative path which does not map to a file on disk then the relative path needs to be rewritten if the file is served through the cassette http handler, since relative urls will no longer reference the correct url. For example, when a relative url is used to reference an image generated by an http handler, the path will need to be absolute or relative to the original css file location.

See also forum post: https://groups.google.com/d/msg/cassette/hfaz8KwdCoE/QrThQb8oMR4J

**Comment by andrewdavey** [comment]
Are the following transformations correct?

```
Virtual directory = "/vdir"
Stylesheet path = "~/styles/example.css"

url(test.png) -> url(/vdir/styles/test.png)
url(/test.png) -> url(/test.png)
url(../test.png) -> url(/vdir/test.png)
```

**Comment by DouglasLivingstone** [comment]
Those transforms look good.

**Comment by willholley** [comment]
This appears to have regressed with beta 4. We have a css rule which looks like:

`background: url(../Recolour/cbcbcb/Images/Workflow/tail.recolour.gif)`

where the url points to a httphander.

Previously (beta 1?), this was being served up correctly relative to the original stylesheet

e.g. `background:url(/<application path>/StyleSheets/../Recolour/cbcbcb/Images/Workflow/tail.recolour.gif)`

In beta 5 this is getting written out as:

`background: url(/<application path>/cassette.axd/StyleSheets/../Recolour/cbcbcb/Images/Workflow/tail.recolour.gif`

and breaks.

**Comment by willholley** [comment]
It looks like this commit f0d3d1e56069becfc6025dde23df2d42a6cb9493 broke this.

UrlGenerator.cs/CreateAbsolutePathUrl calls urlModifier.Modify which, with the addition of HandlerPathPrepender, now always prepends "cassette.axd/" to the output.

**Comment by DouglasLivingstone** [comment]
Cheers for watching the betas.

**Comment by mikeschuld** [comment]
I seem to be experiencing this problem or one like it in Cassette 2.2.2.34609.

Stylesheets/level1/level2/Test.css:
.somerule {
    background: #000 url(images/image.png);
}

output css:
.somerule {
background: url("cassette.axd/file/Stylesheets/level1/level1/images/image.png");
}

Final URL not loading:
http://www.mywebsite.com/somepath/cassette.axd/asset/Stylesheets/level1/level2/cassette.axd/file/Stylesheets/level1/level2/images/image.png

Has this regressed or is it another issue? This is occurring with ALL urls, not just relative ones.

Adding a "/" to the start of the output css path directs to the image correctly.
