### ISSUE TITLE
Bundle AddInlineScript: account for possibly existing <script> tag

### ISSUE THREAD

**Issue by alonando** [andrewdavey/cassette#235]
I think it would be nice if AddInlineScript would NOT add an enclosing <script> tag when it renders IF the js text is already enclosed in one.

One reason for this is that when the <script> keyword is present Visual Studio will provide syntax coloring and intellisense for the javascript code.

**Comment by kobi** [comment]
I submitted a pull request for this exact feature yesterday: https://github.com/andrewdavey/cassette/pull/239

**Comment by alonando** [comment]
I hope this makes it in the next relase. Thanks!
