### ISSUE TITLE
Not throw exception for non-existent file

### ISSUE THREAD

**Issue by RaveNoX** [andrewdavey/cassette#238]
Is any way to not throwing exception for non-existent file which needed by page?
I think there's not good when one broken file will boke all site...

**Comment by Daniel15** [comment]
Why would a required file ever not exist? This seems like a very unlikely scenario.

**Comment by RaveNoX** [comment]
i just don't want to one js script or css file can broke all site
it is not good scenario, but sometimes it's need to edit files on-server => one mistake in script file or less and site goes offline =(

**Comment by andrewdavey** [comment]
Cassette should already tolerate missing images. What sort of files are you missing?

**Comment by Daniel15** [comment]
I personally think that throwing an exception for invalid LESS/CSS is much better than allowing the invalid LESS. IF errors are ignored, there's a chance you'll never find CSS issues until someone reports stuff looking weird. In any case, the LESS parser can't handle invalid LESS, so this is not something Cassette can control.

Missing files are bad too - Unless you're checking your web server logs for 404s (or logging them yourself somewhere), you won't know that pages are broken.

**Comment by RaveNoX** [comment]
Yes, but exceptions may throws for refereces in js files when using AddPerIndividualFile, which may not be referenced and used in project
