### ISSUE TITLE
_cassette dashboard depends on having an internet connection

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#242]
The dashboard references jQuery from a CDN which fails load if you are in a disconnected / internet blocked environment (our application is deployed at public sector customer sites which block general internet access. It would be nice to include a local copy of jQuery so an internet connection is not required for the dashboard to function properly.

**Comment by andrewdavey** [comment]
Latest in `v2` now uses scripts stored in assembly resources, rather than CDN URLs.

**Comment by willholley** [comment]
Fantastic - will give it a go...

On 19 June 2012 02:15, Andrew Davey
reply@reply.github.com
wrote:
