### ISSUE TITLE
InlineScriptBundle translates to a null bundle

### ISSUE THREAD

**Issue by normallywho** [andrewdavey/cassette#247]
Trying to add an inline script bundle is failing. Looking at Cassette.Views.Bundles line 91:

var bundle = new InlineScriptBundle(scriptContent);

While the scriptContent going into InlineScriptBundle() seems fine, the assignment back to bundle is null. This ultimately leads to a NullReferenceException on line 217:

Helper.Reference(bundle, pageLocation);

This is in the latest Cassette v2 code.

**Comment by andrewdavey** [comment]
Are you trying to use this in a view or in CassetteConfiguration?

**Comment by normallywho** [comment]
I get the exception when I start my application at the first instance of AddInlineScript() in the first view the application shows. I hope that answers your question...

**Comment by normallywho** [comment]
Because I was doing a manual installation instead of through Nuget, I was missing a number of changes to the web.config. Once I was able to capture those changes (by doing a Nuget install in a copy of the project and then comparing the web.configs) I updated my real project and got things working again.
