### ISSUE TITLE
Stylesheet Rendering Order 

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#25]
With javascript files, Cassette knows the correct order in which to render the scripts, based on the defined dependencies using the xml comment /// <reference ... />.

However, I have some stylesheets where it matters in which order they are included.
For example, I have Styles.css defining a default color for <a> elements, and a Buttons.css defining another color for <a> elements.

If I would manually include Style.css before Buttons.css, it would work as needed.
However, Cassette renders Buttons.css before Style.css.

I could of course use the !important value or be more specific in my Buttons.css so that its rules will overrule.
But it would be great if I could control dependencies between .css files just like we can with .js files.
Maybe something like:

**Comment by andrewdavey** [comment]
Try using:

``` css
/* @reference "Style.css"; */
```

**Comment by etishor** [comment]
I use a [manual module definition](https://github.com/andrewdavey/cassette/wiki/Manual-Module-Definition) to handle this.

**Comment by sfmskywalker** [comment]
Thanks, both suggestions work great for me.
