### ISSUE TITLE
Directory not found on mono 2.10

### ISSUE THREAD

**Issue by RaveNoX** [andrewdavey/cassette#250]
When using standard config on mono 2.10 Cassette throwing exception: 

```
Directory not found: opt/<site>/www/Content
```

Cassette config: 

```
bundles.AddPerIndividualFile<StylesheetBundle>("~/Content");
```

By "opt/<site>/www/Content" line it looks like non-absolute path is using =/

**Comment by RaveNoX** [comment]
version: latest from NuGet

**Comment by RaveNoX** [comment]
looks like problem in src/Cassette/Utilities/PathUtilities.cs in method NormalizePath
possible fix: 

``` csharp
else
{
  var ret = string.Join("/", stack.Reverse().ToArray());
  if(path.StartsWith(Path.DirectorySeparatorChar.ToString()) or path.StartsWith(Path.AltDirectorySeparatorChar))
  {
    ret = "/" + ret;     
  }
  return ret;
}
```

**Comment by andrewdavey** [comment]
Please give the above commit a try and let me know if that's fixed it. Thanks.

**Comment by merwan** [comment]
I tried it with Mono 2.10.8.1 on Linux and I no longer have this issue.
I still cannot use Cassette because of an issue with IsolatedStorageFile.GetMachineStoreForAssembly() but it's probably related to Mono or to my configuration. I will let you know.

**Comment by andrewdavey** [comment]
Thanks. I'll close this issue. Feel free to open another issue with details about the Isolated Storage problem.
