### ISSUE TITLE
SearchOption.TopDirectoryOnly not working

### ISSUE THREAD

**Issue by peirix** [andrewdavey/cassette#251]
I have this structure:
- skin
  - pagespecific
    - gallery.less
    - forum.less
  - screen.less
  - layout.less

And I only want to include the less-files in the top directory (skin). So I've set up CassetteConfiguration.cs like this:

```
bundles.Add<StylesheetBundle>("Customer/Name/Skin", new FileSearch
{
    Pattern = "*.css;*.less",
    SearchOption = SearchOption.TopDirectoryOnly
});
```

But when I view the page, I still get the less-files from the pagespecific folder.

**Comment by peirix** [comment]
I'm sorry, I was mistaken, it does work, but if I do it that way, I can't do

```
Bundles.Reference("customers/name/skin/pagespecific/gallery.less");
```

What I'm after is creating one bundle with all the less-files in the "skin" folder, and then just adding one and one less file from the page specific as I need them.

**Comment by andrewdavey** [comment]
Have you tried using two `bundle.Add` calls? For example:

```
bundles.Add<StylesheetBundle>("Customer/Name/Skin", new FileSearch
{
    Pattern = "*.css;*.less",
    SearchOption = SearchOption.TopDirectoryOnly
});

bundles.AddPerIndividualFile<StylesheetBundle>("customers/name/skin/pagespecific");
```

**Comment by peirix** [comment]
Ah, that works like a charm. Thank you!

**Comment by peirix** [comment]
On a similar note, is it possible to have it add bundles for every subfolder of "skin"? Something like

```
bundles.AddPerIndividualFile<StylesheetBundle>("customers/name/skin/*");
```

**Comment by andrewdavey** [comment]
How about:

```
bundles.AddPerSubDirectory<StylesheetBundle>("customers/name/skin");
```

?

**Comment by peirix** [comment]
I want it to be one bundle for the root "skin" folder, then addperindividual for every subfolder.

**Comment by andrewdavey** [comment]
You may need to manually get the directory paths using `System.IO.Directory.GetDirectories`. Then iterate and call `AddPerIndividualFile` for each.

**Comment by peirix** [comment]
Yes, that's a good solution. Thanks.
