### ISSUE TITLE
v1 nuget package definition problem with AjaxMin

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#252]
The package says it depends on AjaxMin >= 4.46. However, the binaries appear to have a dependency on exactly that version, so updating to AjaxMin 4.51 breaks at runtime.

**Comment by andrewdavey** [comment]
Looking at the Cassette v2 project, the AjaxMin reference has the Specific Version property set to False. Should this fix the problem?

**Comment by willholley** [comment]
I believe this is fixed in v2, if that's what you are asking?

**Comment by andrewdavey** [comment]
Cool - just double checking. I'll close this.
