### ISSUE TITLE
LESS files not compiled under debug="false"

### ISSUE THREAD

**Issue by hfjallemark** [andrewdavey/cassette#254]
When running Cassette on IIS (7.5) LESS files are not getting compiled when setting debug="false" in Web.config. If debug is on everything works.

**Comment by andrewdavey** [comment]
Note to self: This is with Cassette 2.0.0-beta1

**Comment by hfjallemark** [comment]
Let me clarify this: it does not work when setting `<compilation debug="false"/>`. However it does work when setting `<cassette debug="false"/>`.

Feels like some optimizations in release mode prohibits the Cassette.Less assembly to get loaded into the AppDomain.

**Comment by andrewdavey** [comment]
I just found a bug in the Cassette bundle cache invalidation. If the bundle was cached before you'd added the Cassette.Less reference then it may be cached in its un-compiled form. Can you try pulling down the latest from `v2` and testing again?

**Comment by hfjallemark** [comment]
Will try tomorrow and get back to you.
