### ISSUE TITLE
Cassette v2 does not work in CassiniDev

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#257]
We use cassinidev (http://cassinidev.codeplex.com/) as a drop-in replacement for cassini in development, primarily because there is a 64-bit build unlike cassini or IIS express 7.5. It looks like this suffers from the same *.axd problem as cassini so needs a similar hack / workaround.

**Comment by willholley** [comment]
It seems there are a couple of ways the detection could be changed to make this work. One option is to check Request.ServerVariables["SERVER_SOFTWARE"] == "" (true for non-IIS / express servers) but needs the context of a request to work. 

Another is to check the current process name (e.g. http://stackoverflow.com/questions/9540437/programmatically-determine-if-code-is-running-under-iis-express) but this requires full trust.

**Comment by andrewdavey** [comment]
Take a look at https://github.com/andrewdavey/cassette/blob/v2/src/Cassette.Aspnet/CassetteHttpModule.cs#L66

We should be able to expand the predicate to also check for CassiniDev. Do you fancy doing a pull request?
