### ISSUE TITLE
Smaller nuget packages

### ISSUE THREAD

**Issue by kayone** [andrewdavey/cassette#266]
Hi, just installed cassette and it looks like a great solution, the only thing that I would improve is the package size,

it would be great if Sas, less, and coffee script were packaged separably and could be installed only if needed.

we only need the basic functionality of cassette and all those libraries have increased the size of our deployment package by quite a bit.

again thanks for the great library.

**Comment by willholley** [comment]
To a large extend this is happening in v2. Beta 1 is available via nuget (as a pre-release package) but has a number of known issues. I expect the next beta will be significantly better.

**Comment by andrewdavey** [comment]
Yes, v2 has a new plugin based design, so the core library has just the essentials, making it a much slimmer install. I want to get a beta2 out soon that includes the latest bug fixes.

**Comment by kayone** [comment]
That's great. thank you,
