### ISSUE TITLE
Specifying a folder for module exclusion

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#27]
By default every path you add cassette will combine all JavaScript files in the folders into modules.

On certain folders I would like to be able to specify to cassette to ignore combining the JavaScript on that folder and it's sub folders. 

I would still like to have cassette manage (minification, visioning etc.) but as individual resources.

Maybe this could be done in the configuration like

```
<add path="resources/scripts/controllers" module="Off" />
```

**Comment by tommck** [comment]
I'd like to have it so that we can define different modules out of the same folders.
For instance, you've got a legacy app you're grafting Cassette into...  Instead of having to refactor to move every script in the system to get clean modules, why not be able to define the modules as XML instead?

``` xml
<modules>
    <module name="foo">
        <script file="fooUtil.js"/>
        <script regex="foo*.js" />
        <script file="lalala.js" />
    </module> 
    <module name="bar">
        <script file="impromptu.js"/>
        <script regex="hello.js" />
    </module> 
</modules>
```

That would be highly flexible

**Comment by andrewdavey** [comment]
Cassette's new `IModuleSource<T>` interface should make this possible. Currently there are two file-system based module sources (`PerSubDirectorySource` and `DirectorySource`).

A module source has a method `GetModules` that should return a collection of modules. So creating an implementation of this that accepts a fixed set of asset paths should be quite easy. I'll have a go at adding this.
