### ISSUE TITLE
Cannot reference (some) assets with hyphens in their name

### ISSUE THREAD

**Issue by worldspawn** [andrewdavey/cassette#270]
Can't load

[assets]
class.js
knockout-2.0.0.js

File is definitely there but I get:

System.IO.FileNotFoundException: The asset file "~/ui/js/defaultscripts/knockout-2.0.0.js" was not found for bundle "~/ui/js/defaultscripts".

If I rename the file to knockout2.0.0.js and update the bundle file it works. But I have another bundle that looks like this:

[external]
url = //ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
fallbackCondition = !window.jQuery

[assets]
jquery-1.7.1.min.js

Which is working fine... o.0

Also doesn't work with knockout.2.0.0.js
Works with knockout_2.0.0.js

Seems to be something to do with combining certain non alpha chars adjacent to a number?? But then why does it work with jquery-1.7.1.min.js

**Comment by andrewdavey** [comment]
Do you also have `knockout-2.0.0.debug.js` in the same directory? If so Cassette is probably ignoring the minified file and picking up the .debug.js instead.

**Comment by andrewdavey** [comment]
v2.0.0 has a better exception message when you try to reference an ignored script.
