### ISSUE TITLE
Simple index out of bounds issue.

### ISSUE THREAD

**Issue by benlesh** [andrewdavey/cassette#272]
If the length of the SourceFile.Path is less than the Path.Length + 2, you'll get an index out of bounds error here:

Cassette.HtmlTemplates.HtmlTemplateBundle.GetTemplateId

Line 32-35

https://github.com/andrewdavey/cassette/blob/master/src/Cassette/HtmlTemplates/HtmlTemplateBundle.cs

**Comment by andrewdavey** [comment]
How are you creating an HTML template bundle that contains assets which have shorter paths than the containing bundle path? Can you provide a quick example please? Thanks.

**Comment by benlesh** [comment]
@andrewdavey :  Oh man... I changed the code, but I think it was something where I was creating a template bundle with a path like "/Templates/Whatever/Foo", but within the bundle, I had a few files I wanted to include from "/Templates", and some from "/Templates/Whatever" and some from "/Templates/Whatever/Foo".... if that makes sense.

Either way, it seemed to be a really simple fix. Just needed to add a length check in there.
