### ISSUE TITLE
Concatenation of files with line-comment and block-comment fails to produce valid JS in release mode

### ISSUE THREAD

**Issue by jdt** [andrewdavey/cassette#274]
Given two js-files that are added to a bundle with one ending with a line-comment and the next one starting with a block comment, the concatenation in release mode will fail. Example:
[File1]

``` javascript
function MyAwesomeFunction()
{
}
// This is my awesome function!
```

[File2]

``` javascript
/* License info
* This is open source!
*/
function MyOtherAwesomeFunction()
{
}
```

The resulting concatenated code in release mode will be

``` javascript
function MyAwesomeFunction()
{
}
// This is my awesome function!; /* License info
* This is open source!
*/
function MyOtherAwesomeFunction()
{
}
```

Whereas debug mode would yield

``` javascript
function MyAwesomeFunction()
{
}
// This is my awesome function!
/* License info
* This is open source!
*/
function MyOtherAwesomeFunction()
{
}
```

The code in release mode is obviously wrong as the characters that are supposed to be part of the comment are treated as javascript. The cause can be traced to the ScriptPipeLine code being

``` c#
if (!settings.IsDebuggingEnabled)
{
    Add(new ConcatenateAssets { Separator = ";" });
    var minifier = container.Resolve<IJavaScriptMinifier>();
    Add(new MinifyAssets(minifier));
}
```

In debug mode, the separator is a newline because ConcatenatedAsset's constructor does

``` c#
this.separator = separator ?? Environment.NewLine;
```

In release mode, the separator is set to a semicolon.

For our code this resulted in very odd "'return' Statement Outside of Function"-exceptions due to the concatination throwing off the minify'ing, but I'm pretty sure this can be the cause of some very odd errors.

Solution: either explicitly check for the start of a comment in the next file or always start the content of a new file on a new line. (the latter option seems the safest one as it deals with any and all such problems now and in the future, at the cost of losing a wee bit of minification.)

**Comment by andrewdavey** [comment]
Thanks for reporting this issue and tracking down the root cause. I really appreciate it when people take the time to dig into the source!

Let's always add the newline characters. The minifier will run after this anyway, so it will be able to remove them again if it's safe to do so.

I'll get this fixed for the next release (should be this weekend).
