### ISSUE TITLE
v2, not rebuilding bundles in release mode

### ISSUE THREAD

**Issue by kayone** [andrewdavey/cassette#278]
we are using a configurable base url for our resource so our cassette config looks something like this,

```

var baseUrl = ConfigurationManager.AppSettings["BaseUrl "];
bundles.AddUrlWithAlias(baseUrl + "css/reset.css", "reset.css");
bundles.AddUrlWithAlias(baseUrl + "css/general.css", "general.css");
bundles.AddUrlWithAlias(baseUrl + "css/login.css", "login.css");

```

it seems like once the bundles urls are calculated in "release" mode, they are never calculated again. we can change the value in web.config all we want it will still use the original config.

the strange thing is if we switch to debug mode it will pick up the new value but as soon as we switch back to release it goes back to the first value.

our current work around is to have the app in release mode but have cassette in debug using

```
  <cassette debug="true"/>
```

we tried restarting iis and app pool with no help. does cassette store these things somewhere on disk? where does it get the original values from?

**Comment by andrewdavey** [comment]
I reckon this issue was due to the equality check for external bundles not comparing the URLs. The above commit should fix this.

Please give this a try and let me know if it's working now. Thanks.

**Comment by kayone** [comment]
is this in a nuget package or should I build from source?

**Comment by andrewdavey** [comment]
This should now be in the v2.0.0-beta2 nuget package.
