### ISSUE TITLE
SASS Setup?

### ISSUE THREAD

**Issue by sgentile** [andrewdavey/cassette#283]
I see an example of using LESS, but nothing on SASS.

Does anyone have any examples or how-to for setting up for using SASS ?

Thanks!

**Comment by andrewdavey** [comment]
In Cassette v1.x it should work by just adding `.sass` or `.scss` files to your project.

In Cassette v2 (beta) you need to `install-package Cassette.Sass`

**Comment by sgentile** [comment]
Thanks Andrew.

this morning I could see I had it configured incorrectly - it's working now

appreciate the quick response!

On Wed, Jul 4, 2012 at 3:52 AM, Andrew Davey <
reply@reply.github.com

**Comment by sgentile** [comment]
Andrew, if you don't mind, I have a side question on this:

I was able to get the SASS working, however, it's taking 2-3 minutes for
the page to load - and the SASS code is very minimal.

Any ideas ?

Thanks
Steve

**Comment by sgentile** [comment]
update, the problem was the SASS files I was using were created to use with compass.  so this perf issue wasn't related to getcassette.
