### ISSUE TITLE
AjaxMin version problem

### ISSUE THREAD

**Issue by Hainesy** [andrewdavey/cassette#285]
There is a difference between Cassette and Cassette.Apsnet nuget package references for AjaxMin that causes problems if you install Cassette first and then Cassette.Aspnet

**Comment by ericbock** [comment]
As a workaround, getting the latest AjaxMin, 4.58, through nuget seems to resolve the issue.

**Comment by Hainesy** [comment]
That didn't sort it for me. I had to specifically request an earlier version.

**Comment by robinminto** [comment]
I've had the same problem. The fix is here:
https://github.com/andrewdavey/cassette/commit/2596425efe100bb6fa32a0afc849fb798b26b7a0 
I updated to AjaxMin 4.59 as a workaround.

**Comment by andrewdavey** [comment]
This should be resolved in v2.0.0
