### ISSUE TITLE
Incompatible with Glimpse

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#3]
From: https://github.com/andrewdavey/knapsack/issues/16

It seems that Cassette interferes with glimpse or I don't know the correct Cassette config!. (http://getglimpse.com/)

To repro:

New MVC3 project.
Use Nuget to install Glimpse MVC3
Ensure Glimpse running OK
Set Project to use IIS Express --> Run website in Debugger - Glimpse works OK
Use Nuget to install Cassette.Web --> Run website in debugger - Glimpse doesn't work. Blank screen shown in browser.

**Comment by andrewdavey** [comment]
The implementation of Cassette's response filter stream was waiting for Flush before writing its content. Glimpse wraps the Cassette filter, but never calls Flush. I don't see any docs requiring Flush to be called, so I've changed Cassette's filter.

The code, in master, now writes to the output stream when Write is called and seems to work fine with Glimpse. Please pull the latest code and let me know if it's working now. I'll then get a new nuget package released next week. Thanks.

**Comment by darran** [comment]
Tested Cassette 0.51 with Glimpse 0.84 on MVC3 project. 

Glimpse working as expected. 

Many Thanks, Darran

**Comment by andrewdavey** [comment]
Excellent. Thanks for testing it. The latest nuget package is now Glimpse compatible.
