### ISSUE TITLE
YSOD - An item with the same key has already been added - Again

### ISSUE THREAD

**Issue by barclayadam** [andrewdavey/cassette#30]
I'm having the same problems as [issue 18](https://github.com/andrewdavey/cassette/issues/18), where I am receiving a YSOD with 'An item with the same key has already been added'. I'm using version 0.5.4 though which has not solved the issue, as that one seems to be a different cause.

Having worked through the issue I have modified the latest source code in 2 places which seems to have fixed the issue, although I'm not sure whether the fix is correct or not. I have:

ModuleContainer.cs, line 27:

```
modulesByScriptPath = (
    from module in this.modules
    from asset in module.Assets
    select new { asset.Path, module }
).Distinct().ToDictionary(x => x.Path, x => x.module, pathComparer);
```

UnresolvedModule.cs, line 60:

```
var modulesByAssetPath = (
    from module in unresolvedModules
    from asset in module.assets
    select new { asset.Path, module }
).Distinct().ToDictionary(x => x.Path, x => x.module.path, StringComparer.OrdinalIgnoreCase);
```

To give some background as it stands my web.config looks like:

```
<cassette moduleMode="OffInDebug">
    <scripts>
        <add path="Scripts/Lib" />
    </scripts>
    <styles>
        <add path="Content/Css/" />
    </styles>
</cassette>
```

Without Scripts/Lib everything works OK. In Scripts/Lib I have a number of 3rd party JS files (jQuery, jQuery UI etc.) and a modules.txt file.

In addition, the exception that is thrown is not particularly useful as it points only to ExceptionCachedManager as the exception is rethrown from there. Can the stack trace be preserved, something along the lines of:

Line 20, in the constructor:

```
PreserveStackTrace(exception);
```

Add:

```
private static void PreserveStackTrace(Exception exception)
{
    var preserveStackTrace = typeof(Exception).GetMethod("InternalPreserveStackTrace",
                                                         BindingFlags.Instance | BindingFlags.NonPublic);

    preserveStackTrace.Invoke(exception, null);
}
```

Although the YSOD still gives the unhelpful stack trace (it does not look at the Stack Trace of the exception but does some other magic to determine the 'incorrect' stack trace), the stack trace logged in event viewer and available elsewhere will be valid and point in the right direction.

Thanks,
Adam

**Comment by andrewdavey** [comment]
Closing this because the newer version of Cassette has largely rewritten the module container and other code. Let me know if you still get errors.

https://github.com/andrewdavey/cassette/wiki/0.6-Migration-Guide

Thanks for the idea about preserving the stack. I may borrow that at some point.
