### ISSUE TITLE
IUrlModifier ignored when running in release (debug=false)

### ISSUE THREAD

**Issue by jamesh1971** [andrewdavey/cassette#301]
Using the latest version 2.0.0, beta 5 from NuGet. When in debug mode the IUrlModifier is invokved fine. When running in release mode (debug=false in web.config) the IUrlModifier is never invoked.

Here's the code I have:

```
public class ServeCassetteThroughCDN : IUrlModifier {
    public string Modify(string url) {
        Log.Write(string.Format("Request for {0}", url));
        if (Configuration.IsRemoteServer && !HttpContext.Current.Request.IsSecureConnection) {
            Log.Write("Request through CDN");
            return (Configuration.CDNSiteURL + @"cassette.axd/" + url);
            }

        return (@"cassette.axd/" + url);
        }
    }

public class CassetteServices : ServicesConfiguration {
    public CassetteServices() {
        Log.Write("Setup configuration");
        UrlModifierType = typeof(ServeCassetteThroughCDN);
        }
    }
```

CassetteServices cconstructor is run in both cases, to set UrlModifierType. But ServeCassetteThroughCDN.Modify is never called in release mode.

What am I doing wrong?

**Comment by andrewdavey** [comment]
Cassette caches the HTML generated by `Bundle.RenderScripts()`, etc. The custom URL modifier will be called the first time the app is run, when Cassette is building the bundles.

Are you wanting Cassette to call the IUrlModifier every time HTML is rendered?

**Comment by jamesh1971** [comment]
Hi Andrew,

Below is my code in CassetteConfiguration.cs. When the server starts up in release mode the log contains Setup configuration, then Setup bundles, but no log at all for “Request for…”. In debug mode I get the “Request for…” and it works fine.

Can you reproduce the bug?

If not, is there anything I can add into the CassetteBundleConfiguration.Configure method to log values that will help you discover the problem, e.g. a method call or property values that provide the currently configured IUrlModifier?

James

/// <summary>


            /// Configures the Cassette asset bundles for the web application.
            /// </summary>


            public class CassetteBundleConfiguration : IConfiguration<BundleCollection> {
                        public void Configure(BundleCollection bundles) {
                                    // Please read http://getcassette.net/documentation/configuration 
                                    Log.Write("Setup bundles”);

```
                                bundles.Add<StylesheetBundle>("Styles", "_/bootstrap/2.0.4/less/bootstrap.less", "_/bootstrap/2.0.4/less/responsive.less", "_/content.less", "_/blog.less", "_/form.less", "_/layout.less", "_/nav.less", "_/table.less", "_/type.less", "_/store.less", "_/camtasia.css", "_/compat.less");
```

bundles.Add<ScriptBundle>("Scripts", "_/bootstrap/2.0.4/js/bootstrap-button.js", "_/jquery.validate.js", "_/jquery.validate.unobtrusive.js", "_/slides.jquery.js", "_/jquery.scrollintoview.js", "_/script.js");  
                                    }
                        }

```
        public class ServeCassetteThroughCDN : IUrlModifier {
                    public string Modify(string url) {
                                Log.Write(string.Format("Request for {0}", url);
                                return (@"cassette.axd/" + url);
                                }
                    }

        public class CassetteServices : ServicesConfiguration {
                    public CassetteServices() {
                                Log.Write("Setup configuration”);
                                UrlModifierType = typeof(ServeCassetteThroughCDN);
                                }
                    }
```

**Comment by andrewdavey** [comment]
If the scripts have not changed, then when the application loads, it does so directly from cache. You can clear this by either changing a script (re-saving should be enough) or click Rebuild Bundle Cache on the /cassette.axd page.

To see what URL modifier is getting load you could add a constructor to the config class:

``` csharp
public class CassetteBundleConfiguration : IConfiguration<BundleCollection> {
    public CassetteBundleConfiguration(IUrlModifier modifier) {
        Log.Write(modifier.GetType().FullName);
    }
}
```

**Comment by jamesh1971** [comment]
Thanks. It was the caching that was the problem. Clearing the cache solved the problem.
