### ISSUE TITLE
Allow Pluggable Serializer For Page Data

### ISSUE THREAD

**Issue by mickdelaney** [andrewdavey/cassette#303]
Can cassette allow for the host system to plug in a serializer (e.g. json.net).
At present we use Json.net but there is a difference between what cassette does for page data, and what we do for ajax requests.

**Comment by andrewdavey** [comment]
This affects `PageDataScriptBundle` (the only place we do JSON serialization in Cassette).

We need to introduce an IJsonSerializer interface and a default implementation of this that uses the existing SimpleJson code.

Then these can be registered in the container, and so allow the application code to override.

**Comment by mickdelaney** [comment]
Cool. once your ready give me a shout and i'll create a Json.net plugin for it.

**Comment by andrewdavey** [comment]
To use a different serializer, e.g. Newtonsoft.Json, create a class that implements `Cassette.IJsonSerializer` and calls the serialization library.

Then register this in Cassette's container. One way to do this:

``` csharp
public class AppConfiguration : Cassette.ServicesConfiguration
{
    public AppConfiguration()
    {
        JsonSerializerType = typeof(MySerializer);
    }
}
```
