### ISSUE TITLE
Latest AjaxMin Nuget Package contains a breaking change

### ISSUE THREAD

**Issue by RobCannon** [andrewdavey/cassette#309]
The 4.66 version of AjaxMin contains a breaking change.  The assembly name has changed to AjaxMinLibrary.dll.

If a project updates to the latest version of AjaxMin, it breaks the project.  I can think of two possible solutions.  One is the change the Cassette Nuget to requires a specific version of Ajax.  The other is to go ahead and adopt the latest version and consume the new assembly name.

**Comment by andrewdavey** [comment]
Thanks for reporting this. I'll update Cassette to use the latest version and release an updated nuget package.

**Comment by andrewdavey** [comment]
It looks like the AjaxMin DLL has been renamed back to AjaxMin.dll http://ajaxmin.codeplex.com/releases/view/94207

I'll still update Cassette to use the most recent AjaxMin package.

**Comment by andrewdavey** [comment]
Actually, can you just `update-package AjaxMin` to get the latest? That should fix things without needing to update Cassette.

**Comment by RobCannon** [comment]
It looks like the AjaxMin Nuget has been changed back to the expected assembly name.  Never mind...
