### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by pilavdzic** [andrewdavey/cassette#31]
Hello,
   Sorry for posting this here but I can't find any documentation.

I found one page on this github wiki that told me how to use

Assets.Scripts.Reference() and I am migrating my site over to using that and this works... 

But how do you include a css file?
Is it Assets.Style.Reference() or Assets.Styles.Reference or Assets.Css.Reference or something?

Is it just me that does not have intellisense in Razor cshtml files?

Obviously I did a google search for "cassette javascript css" and "casseette javascript styles" and many other such searches and all the top pages returned don't have any useful info...

**Comment by andrewdavey** [comment]
The helper is here: https://github.com/andrewdavey/cassette/blob/master/src/Cassette.Web/Assets.cs
So `Assets.Stylesheets.Reference(...);`

If you aren't getting intellisense, make sure the `~/Views/Web.config` includes this:

``` xml
<system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
    <pages pageBaseType="System.Web.Mvc.WebViewPage">
      <namespaces>
        ...
        <add namespace="Cassette.Web"/>
        ...
      </namespaces>
    </pages>
  </system.web.webPages.razor>
```

Also, sometimes I have to force a build and reload the .cshtml files when first creating a project to make the intellisense work.

**Comment by andrewdavey** [comment]
The documentation certainly needs to catch up with the feature set! I've been very busy this week rewriting large parts of Cassette's core. Once this is finished I'll be moving on to documenting it all. Thanks for your patience and for taking the time to try out a very young open source project ;)

**Comment by tommck** [comment]
This is a huge need.  At least a simple example of different scenarios.  I didn't even realize you could include a whole module with this until I looked at the sample...
