### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by sgentile** [andrewdavey/cassette#313]
https://github.com/andrewdavey/cassette/issues/67

In there is SASS and Compass, I see it's closed.  does it include support for Compass ?

If it does, is there any setup requirement for it?

Thanks!
Steve

**Comment by andrewdavey** [comment]
Cassette uses SassAndCoffee to compile Sass, so I don't think Compass support is quite there yet.
https://github.com/xpaulbettsx/SassAndCoffee/pull/4
