### ISSUE TITLE
Including Scripts that were removed from the project

### ISSUE THREAD

**Issue by tommck** [andrewdavey/cassette#32]
I have scripts (amplify.js stuff) that I removed from the project while I'm testing and I killed the Cassini (WebDev) web server.  I rebuilt the code... I reran the page.  I'm still getting the files included in the project...

<script src="/Scripts/amplify.js?e90b20fc3cb0acb9e50c1134fc430194335815a5" type="text/javascript"></script>

<script src="/Scripts/amplify.min.js?83c1d95e2a30458f77e9a8ebd14826639df78f6e" type="text/javascript"></script>

Nothing references amplify.  I just added it to my project and did not use it anywhere.
Now, I excluded the js files from my project and it's still happening??

**Comment by tommck** [comment]
Actually, it looks like it's getting every file that's in the directory, not just those that are in the Project.

Can that be stopped?

**Comment by tommck** [comment]
OK... getting weirder; stopped debugging; deleted files; restarted debugging.

It's _still_ getting amplify.js somehow?

**Comment by tommck** [comment]
OK, that last part was cache, which is a Cassini problem (my app doesn't cache anything during debug, but Cassini ignores that).  Switching to IIS for sanity

**Comment by andrewdavey** [comment]
Assets are located using a regular `Directory.GetFiles` call. So even if they are not added to the VS project they will be found.

I need to document why the default behaviour includes all scripts.
For now please read https://github.com/andrewdavey/cassette/issues/36#issuecomment-1939718
That should go some way to explaining things.

**Comment by pilavdzic** [comment]
I have this same problem as well. It is very annoying. For me it is behaving even worse, not only does it include script files not in the project, it includes entire folders of script files (modules) that should not be included at all and that I am not telling it to include anywhere.

**Comment by pilavdzic** [comment]
P.S. It does this even when I rename the folder to an entirely different one. It finds it - no idea how, and includes it.

For example, I had files in /Scripts/NotInUse.

I renamed this to /OldScripts and STILL it tries to include them all (creating errors for me in the process).

**Comment by tommck** [comment]
Yeah, in addition, when you're developing, you may sometimes do something
like making a backup copy of files or something in a subdirectory, or a
"Copy Of XXXX.js" or something.

This causes duplicate naming errors,etc.

I think the module definitions need to be tied into the Project definition
somehow.
