### ISSUE TITLE
Nuget Package modifies Web.Config incorrectly. 

### ISSUE THREAD

**Issue by AnalogJ** [andrewdavey/cassette#321]
Cassette is incredible btw.

I did notice one issue with the nuget installer though, I had the following in my webconfig:

```
<modules runAllManagedModulesForAllRequests="true">
  <add name="ErrorLog" type="Elmah.ErrorLogModule, Elmah" preCondition="managedHandler" />
  <add name="ErrorMail" type="Elmah.ErrorMailModule, Elmah" preCondition="managedHandler" />
  <add name="ErrorFilter" type="Elmah.ErrorFilterModule, Elmah" preCondition="managedHandler" />
  </modules>
```

and after the nuget installer had run, I had this:

```
<modules>
  <add name="ErrorLog" type="Elmah.ErrorLogModule, Elmah" preCondition="managedHandler" />
  <add name="ErrorMail" type="Elmah.ErrorMailModule, Elmah" preCondition="managedHandler" />
  <add name="ErrorFilter" type="Elmah.ErrorFilterModule, Elmah" preCondition="managedHandler" />
  <add name="CassetteHttpModule" type="Cassette.Aspnet.CassetteHttpModule, Cassette.Aspnet" />
  </modules>
```

As you can see, the `runAllManagedModulesForAllRequests="true"` attribute is missing. 

You might want to make sure that your nuget installer does not make breaking changes like that.

**Comment by andrewdavey** [comment]
Did this happen when upgrading from an old version of Cassette? Or does it happen when installing for the first time?

My guess is that this is upgrade-related. An old version of Cassette required `runAllManagedModulesForAllRequests="true"`. But that requirement has since been removed. So the nuget update may have inadvertently removed the attribute.

**Comment by AnalogJ** [comment]
Nope this happened from a clean install of v2 from nuget. I actually had the 'runAllManagedModulesForAllRequests="true"' for  Elmah actually.

**Comment by andrewdavey** [comment]
I can't reproduce this. I created a new MVC4 app, which has `runAllManagedModulesForAllRequests` in web.config. I then installed `Cassette.Aspnet`. The web.config was updated, but `runAllManagedModulesForAllRequests` correctly. remained.

Are you using the most recent version of Nuget? I'm using 2.0.30815.3

**Comment by AnalogJ** [comment]
Hey,
I'm acutally pretty confused too. I created a new MVC3 app with just `Elmah` and then installed `Cassette` after, and the issue didn't reoccur. I guess you should just close this, it may be just a [PEBLAC](http://xkcd.com/1031/) issue.

**Comment by andrewdavey** [comment]
No problem - at least it's working for you now :) Feel free to reopen if you can reproduce this at some later point.
