### ISSUE TITLE
Build XML Documentation File

### ISSUE THREAD

**Issue by SLaks** [andrewdavey/cassette#323]
Cassette has nicely-written XML doc comments on most of its members, but no-one ever sees them because they aren't built into the release.

At least for Cassette and Cassette.Views, we should tell the compiler to build XML doc comments

**Comment by SLaks** [comment]
I checked the checkboxes for these two projects and got 583 warnings.
Most of these warnings are CS1591's for members with missing comments; I'll suppress that warning.
25 of them are for bad param tags, which I'll fix.

I'll submit a pull request when I'm done.

**Comment by SLaks** [comment]
I'll also fix spelling errors.

**Comment by andrewdavey** [comment]
Thanks for looking into this. Does the nuget build script need updating to include the documentation?

**Comment by SLaks** [comment]
I think so
I'll add that too.
