### ISSUE TITLE
NuGet packages for 2.1-beta2 have incorrect dependencies on .NET 4

### ISSUE THREAD

**Issue by willholley** [andrewdavey/cassette#336]
If you list the package dependencies for Cassette, it does not include AjaxMin as expected. This is also the case with Cassette.Less (should depend on Cassette and DotLessClientOnly) and Cassette.MSBuild (should depend on Cassette).

They all report dependencies on Iesi.Collections which, from the nuspec, is intended only for .NET 3.5?

**Comment by andrewdavey** [comment]
I was confused by the nuspec `<group>` element documentation. I've updated them to correctly work with .NET 3.5 and .NET 4.0.

Please try installing v2.1.0-beta3 which should fix things.

**Comment by andrewdavey** [comment]
Fixed in current beta.
