### ISSUE TITLE
During css minification of a CSS3 transition duration, Cassette changes '0s' to '0'

### ISSUE THREAD

**Issue by dontjee** [andrewdavey/cassette#339]
If I have the following CSS in a stylesheet

```
div
{
   transition: width 0s;
   -moz-transition: width 0s;
   -webkit-transition: width 0s;
   -o-transition: width 0s;
}
```

when Cassette minifies the CSS it will remove the 's' character from all of the '0's. This behavior is OK in most browsers but breaks in Firefox.

The workaround is to set the time to '1ms' instead because the 'ms' is not stripped from the '1'.

This may even be a bug in Firefox but is there a way to fix it in Cassette?

**Comment by elerch** [comment]
@dontjee Cassette doesn't actually perform the minification: by default it's passed off to AjaxMin.  You might see if you can reproduce your issue with the command line AjaxMin and file an issue over there: http://ajaxmin.codeplex.com/workitem/list/basic

In the meantime you can also swap out minifiers (e.g. to YUI) by overriding the default configuration.  There's some direction on doing this in the docs here: http://getcassette.net/documentation/v2/scripts/minification

That page configures the Javascript minification, but stylesheets would be along similar lines.  Looks like this groups thread refers specifically to v2 YUI integration with Cassette: https://groups.google.com/forum/?fromgroups=#!topic/cassette/brJXtkJf49k

**Comment by dontjee** [comment]
That make sense. Thanks!
