### ISSUE TITLE
Conditional inclusion of scripts/css

### ISSUE THREAD

**Issue by tommck** [andrewdavey/cassette#34]
I have shared views which are used in 2 different situations (Desktop/iPad).  I have a test in my Site.Master to include the CSS for the iPad (lots of overriden styles) if the requesting user is using an iPad.  Unfortunately, Cassette puts all of this stuff together, it seems.

How can I accomplish this, given that they're the same exact views?

**Comment by andrewdavey** [comment]
You will need to split your styles into separate modules (folders) for the two scenarios. Something like this in your project:

```
/styles/desktop
/styles/ipad
```

Are detecting the user agent (e.g. iPad Safari) server side? Or do you want to use a media query (based on screen width)?
For the former, something like this in the view could work:

```
@{
if (Request.IsIPad()) { // for example
    Assets.Styles.Reference("styles/ipad");
} else {
    Assets.Styles.Reference("styles/desktop");
}
}
```

For the media query (which I think is a better approach in general), please wait for the new version of Cassette which adds support for defining the stylesheet link media attribute. I'm hoping to get this released next week.

**Comment by tommck** [comment]
RIght, but this would require I put an if/then/else in every file instead of just in the Site.Master, right?

**Comment by tommck** [comment]
Media queries are nice if you're only detecting size and orientation, but the UI is different when we're on the iPad.  Different stylings, different font sizes, etc.  We don't want the font sizes to change based on the size of the person's browser window

**Comment by andrewdavey** [comment]
If the styles are site-wide then put the if-else Reference calls in your master page.

Otherwise, you may want to look into adding a extension method to `StylesheetAssetManager` that does the if-else and calls Reference with the required path. (Assuming you have some predictable for desktop and iPad stylesheet names.)

```
@Assets.Stylesheets.ReferenceForRequestingDevice("styles/example")
```

**Comment by andrewdavey** [comment]
I'm closing this issue as I don't think Cassette itself needs to handle this. It's possible to extend and customize Cassette in your application code.
Let me know if you need any more help with this.
