### ISSUE TITLE
Image Spriting for jQuery UI

### ISSUE THREAD

**Issue by Meligy** [andrewdavey/cassette#347]
Hello,
I was experimenting with replacing ASP.NET MVC 4 Bundling with Cassette for few specific features , namely image spriting and JS templates.

Anyway, I created a default template site, copied the jQuery UI part from MS bundling to my configuration, and use the standard optimization code (after adding the relevant NuGet package of course).

After referencing the bundle, I looked at generated CSS for jQuery UI default theme (included in default ASP.NET MVC project template), and the image paths seemed to be just the same. No spriting there.

I assume this is related to how the files are written that they don't meet the sprite requirements like ensuring the width, etc is included in the same selector? I know RequestReduce at some point removed some of these requirements, is the current version of spriting compatible with it? (I haven't tested it on MapReduce though).

I'm using Cassette.Spriting Nuget package v. 2.1.0-beta4.

For reference, this is my configuration, in case it was specific to my code:

```
        bundles.Add<StylesheetBundle>("~/Content/themes/base/css",
                                      new[]
                                          {
                                              "~/Content/themes/base/jquery.ui.core.css",
                                              "~/Content/themes/base/jquery.ui.resizable.css",
                                              "~/Content/themes/base/jquery.ui.selectable.css",
                                              "~/Content/themes/base/jquery.ui.accordion.css",
                                              "~/Content/themes/base/jquery.ui.autocomplete.css",
                                              "~/Content/themes/base/jquery.ui.button.css",
                                              "~/Content/themes/base/jquery.ui.dialog.css",
                                              "~/Content/themes/base/jquery.ui.slider.css",
                                              "~/Content/themes/base/jquery.ui.tabs.css",
                                              "~/Content/themes/base/jquery.ui.datepicker.css",
                                              "~/Content/themes/base/jquery.ui.progressbar.css",
                                              "~/Content/themes/base/jquery.ui.theme.css"
                                          }, 
                                          bundle => bundle.SpriteImages());
```

I have confirmed the output was produced by Cassette's .axd file.

**Comment by Meligy** [comment]
Update:

I tested RequestReduce now. It doesn't sprite the images in jQuery UI too. Not sure if it is an issue rooted in RequestReduce, or whether these images are not possible to sprite at all.

**Comment by andrewdavey** [comment]
Cassette uses the same spriting code as Request Reduce.

Have you read this https://github.com/mwrock/RequestReduce/wiki/Can-I-make-changes-to-my-CSS-classes-to-optimize-RequestReduce-spriting%3F ? It explains what you need to do in your CSS to make it spritable.
