### ISSUE TITLE
NuGet: Cassette.Web vs Cassette.Aspnet

### ISSUE THREAD

**Issue by Meligy** [andrewdavey/cassette#348]
In the documentation, it sounds like the right NuGet to use is `Cassette.Aspnet`.

In the Github project homepage, it suggests using `Cassette.Web`.

After installing both to a new project, I got a configuration file that did not compile. When I installed only  `Cassette.Aspnet` to another new project, I got the correct file. (Note -if related-: I have pre-releases enabled in my NuGet dialog)

Is  `Cassette.Web` a legacy package? Or is there a different role for each?

**Comment by andrewdavey** [comment]
Cassette.Web is a legacy package. You need to only use Cassette.Aspnet. Make sure you fully remove Cassette.Web from your project and bin directory, otherwise it will break things!

I will update the project readme.
