### ISSUE TITLE
Variables in Switch in Anonymous Function not minified

### ISSUE THREAD

**Issue by jwynveen** [andrewdavey/cassette#351]
When enabling minification on my site, I noticed an issue with minification of scripts with anonymous functions. Any variables inside a switch statement in that function will not be renamed; however, all variables outside the switch but still within the function are renamed properly.

Example:

``` javascript
(function() {
    var myVariable = {
        prop1: true,
        prop2: false
    };
    var testVar = myVariable.prop1;
    switch (testVar) {
        case myVariable.prop1:
            console.log('prop1');
            break;
        case myVariable.prop2:
            console.log('prop2');
            break;
    }
}());
```

When minified, it turns into this (after running it through jsbeautifier):

``` javascript
(function () {
    var n = {
        prop1: !0,
        prop2: !1
    }, t = n.prop1;
    switch (t) {
        case myVariable.prop1:
            console.log("prop1");
            break;
        case myVariable.prop2:
            console.log("prop2")
    }
})()
```

You can see that 'myVariable' was renamed to 'n' everywhere except inside the switch.

**Comment by SLaks** [comment]
That's a bug in the minification engine, not Cassette itself.

I believe Cassette uses [AjaxMin](http://ajaxmin.codeplex.com/) by default; you can also plug in your own minifier.

**Comment by jwynveen** [comment]
Yep, looks like you're right. Downloaded the newest version of AjaxMin and it works correctly. Any idea how I can update the version I'm using? I just pulled in the newest NuGet of AjaxMin, but how do I register it with Cassette? http://getcassette.net/documentation/v2/scripts/minification isn't helping me too much.

**Comment by SLaks** [comment]
Just delete the old one, and it should work.
If you get an error about loading the assembly, add / update the `<bindingRedirect>`.

**Comment by jwynveen** [comment]
Oh duh. That worked. Didn't even need the binding redirect. Thanks!
