### ISSUE TITLE
BundleCollection#InitializationException not allowing LESS to be rebuilt

### ISSUE THREAD

**Issue by TheCloudlessSky** [andrewdavey/cassette#355]
There is an issue where if a referenced file has an error and causes an exception to be thrown during exception, the bundle collection is not re-initialized with the `FileSystemWatchingBundleRebuilder`.

Create the following files:

content/ref.less:

```
@foo: red;
body {
    background-color: @foo;
}
```

content/site.less:

```
@import-once "ref.less";
```

content/bundles.txt:

```
a.less
```

Add the bundle config:

```
bundles.Add<StylesheetBundle>("content");
```

Finally, reference and render the bundle:

```
@{
    Bundles.Reference("content");
}
@Bundles.RenderStylesheets()
```

Open the site in a browser. Background renders red. 

Now, change `@foo: red` to `@    foo: red` (to introduce a compile error). Refresh the browser and the error is displayed. Now - fix the error by removing the spaces. Refresh the browser and you should **still see the error**. 

I've narrowed it down to `BundleCollection#InitializationException` still being set once the file is changed. For some reason the `IsKnownPath()` of `FileSystemWatchingBundleRebuilder` is returning false when the `ref.less` error is _fixed_. 

I haven't had time to narrow it down or even see if I can reproduce with a test, but can happen quite often. To fix this, it requires a Clean/Rebuild All of the web project (which is quite a pain).

Thanks!

**Comment by TheCloudlessSky** [comment]
I'd also like to point out that this _doesn't_ seem to happen if you're just referencing a single .less file.

**Comment by kamsar** [comment]
IsKnownPath is returning false because it appears the assets' references collection has been cleared after a compilation error so it's not finding the reference. I've encountered this same issue with my Compass extensions, and am going to try and fix it.

**Comment by kamsar** [comment]
The culprit is the following code in BundleCollectionInitializer:

```
   public void Initialize(BundleCollection bundleCollection)
    {
        using (bundleCollection.GetWriteLock())
        {
            bundles = bundleCollection;
            bundles.Clear();
            AddBundles();
            ProcessBundles();
            AddBundlesForUrlReferences();
            bundles.BuildReferences();
        }
    }
```

Because the bundles collection is cleared and rebuilt from scratch, if an exception occurs prior to `bundles.BuildReferences()` being called, the references are not evaluated for the bundle - so the pre-existing references are summarily removed and become no longer considered for the purposes of cache eviction.

It seems like the correct behaviour here may be to remove the busted bundle from the collection entirely? I'll keep investigating.
