### ISSUE TITLE
[2.1.0-beta5] AddInlineScript throws NullReferenceException

### ISSUE THREAD

**Issue by herrquark** [andrewdavey/cassette#364]
I guess this link should be enough to locate the problem: http://getcassette.net/documentation/v2/bundles-helper/inline-script

**Comment by ghidello** [comment]
The same error appears opening cassette.axd (for a site working with 2.1.0-beta4 version

**Comment by andrewdavey** [comment]
Thanks for catching this. I've fixed and updated the nuget package.
