### ISSUE TITLE
Module per file

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#37]
The default behaviour of creating a single asset module for the entire application is really confusing people.
I can see "WTF?! Why is Cassette including all my files?!" becoming a common question :)

So perhaps the default mode of Cassette should treat each file as a separate module. Referencing would still work. So if a script references jquery.js then referencing that script in a page also brings in jquery.

We just need to add a `ModulePerFile` implementation of `IModuleSource` and use that as the default when no other module sources have been configured.

Thoughts?

**Comment by nazjunaid** [comment]
I couldn't agree with you more

**Comment by ChrisMH** [comment]
Perhaps a better explanation of why Cassette is including all files in a module is all that is needed.  

It's fairly clear why when you consider Cassette's behavior in release mode.

**Comment by nazjunaid** [comment]
I don't know how people are using cassette but with the default setting of taking every JavaScript in the project file and merging them into one is not how we use is as we have around 20-30 js files in a fairly large application. In my opinion I think the default setting makes a massive assumption and modifies the behaviour of your application too much which can be confusing and slightly scary.

I much prefer the idea of the ModulePerFile implementation so then a developer is encouraged to use cassete with minimal change to begin (no modules but dependency management) and then eventually as they discover an learn more about cassette's they can start using the modules feature correctly with a properly thought out plan.

**Comment by andrewdavey** [comment]
Recent code in master now has `PerFileModuleSource<T>`.

```
moduleConfiguration.Add(
    new PerFileModuleSource<ScriptModule>("") // parameter is directory path - empty means app root.
    {
        FilePattern = "*.js;*.coffee"
    }
);
```

Also, the defaults for an application with no configured module sources are as follows:

```
IModuleSource<ScriptModule> DefaultScriptModuleSource()
{
    return new PerFileModuleSource<ScriptModule>("")
    {
        FilePattern = "*.js;*.coffee",
        Exclude = new Regex("-vsdoc\\.js$")
    };
}

IModuleSource<StylesheetModule> DefaultStylesheetModuleSource()
{
    return new PerFileModuleSource<StylesheetModule>("")
    {
        FilePattern = "*.css;*.less"
    };
}

IModuleSource<HtmlTemplateModule> DefaultHtmlTemplateModuleSource()
{
    return new PerFileModuleSource<HtmlTemplateModule>("")
    {
        FilePattern = "*.htm;*.html"
    };
}
```
