### ISSUE TITLE
External module configurable in module.txt

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#38]
Add support for external module config in module.txt

```
[external]
http://cdn.com/jquery.js

[assets]
jquery.js
```

**Comment by nazjunaid** [comment]
Just a note maybe the txt should be something more structured like xml to support this and potentially other features in the future?

**Comment by andrewdavey** [comment]
I do like the simplicity of the plain text file, especially for when it is just a list of filenames. The INI style extensions add just enough extra control for now.

However, adding support for xml/yaml/json would be possible too.

**Comment by andrewdavey** [comment]
Going with the following syntax:

```
[external]
url = http://cdn.com/jquery.js
fallbackCondition = !window.jQuery

[assets]
jquery.js
```
