### ISSUE TITLE
Normalize File System Module Source paths

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#39]
e.g.

```
new DirectorySource<ScriptModule>("Content/Scripts/lib/")
```

should be the same as

```
new DirectorySource<ScriptModule>("Content\\Scripts\\lib")
```

**Comment by etishor** [comment]
You might also be interested in the first problem i describe [here](http://www.erata.net/net/cassette-asset-management-net-web-apps/).I think Normalizing should also be done for paths in module.txt files.

**Comment by andrewdavey** [comment]
Thanks for the blog post - it's great to see Cassette getting picked up by people!

I'll be sure to test and fix the module.txt path problem as well.

I've created an issue for the IIS6 problem here https://github.com/andrewdavey/cassette/issues/40

**Comment by etishor** [comment]
Thank you for the great tool :)
