### ISSUE TITLE
Grouping of assets

### ISSUE THREAD

**Issue by worldspawn** [andrewdavey/cassette#4]
Hello. Teleriks' asset manager provides for the adding of assets to specific groups. In this way I could define a group like "form" which might reference jquery validate, my validate extensions, other form stuff. Then on a page that contains a form I can just enable that group.

In this way all the possible assets and groups etc are always configured, usually in a single spot, then they are "turned on" when needed.

**Comment by andrewdavey** [comment]
How about referencing jQuery validate and your extensions from the form stuff script? Then in the page simply reference the form stuff script. Cassette will pull in all the other required scripts for you.

**Comment by andrewdavey** [comment]
Cassette 0.6 supports module references within a "module.txt" file.

Assuming you've grouped your scripts into module sub-directories of `~\Scripts` already, create a new sub-directory of `~\Scripts` called `mygroup`, for example.

Create a file called `module.txt` in the `mygroup` directory. Add the following:

```
[references]
~\Scripts\lib # what ever modules you need add here...
~\Scripts\forms
```

Now in your page you can do:

```
@{ Assets.Scripts.Reference("mygroup") }
```

Cassette will bring in the two referenced modules.
