### ISSUE TITLE
Generate Automatic Bundle

### ISSUE THREAD

**Issue by SeriousM** [andrewdavey/cassette#406]
When I ask Cassette to render my css files I added with Bundles.Reference, Cassette knows all my Files I need including the order of them.
Is it possible to generate an automatic bundle that is concatinated and minified?
The scenario that I have is that my file count is pretty high but I can't define static Bundles.
I could also live with a solution where I create Bundles on the fly on each Page request. Is that possible?

Thanks, Bernhard

**Comment by andrewdavey** [comment]
Unfortunately Cassette isn't designed to work this way. I suggest taking a look at http://requestreduce.org/

**Comment by SeriousM** [comment]
We are using cassette now in production... is requestreduce compatible with cassette?

**Comment by andrewdavey** [comment]
I'm not sure if you can use them together. It may work if you set `<cassette rewriteHtml="false"/>` in web.config.

**Comment by SeriousM** [comment]
ok, in this case i just stay with the cassette :), thanks
