### ISSUE TITLE
AddUrlWithAlias with HTTP or HTTPS

### ISSUE THREAD

**Issue by noamberda** [andrewdavey/cassette#431]
Hi,
What would be the best practice if i am referencing and external resource by URL and i need to load the HTTP or the HTTPS of the same resource based on the protocol my current page is?

For example i have a Url in my resources to google maps. if i will not open google maps with the same protocol my page is currently in i will get a javascript error.

Thanks,
noam

**Comment by andrewdavey** [comment]
Try using a protocol relative URL, e.g. `//example.com/foo.js`

**Comment by noamberda** [comment]
Working great now. Thanks.
