### ISSUE TITLE
`@reference` doesn't include the files in the bundle.

### ISSUE THREAD

**Issue by Crisfole** [andrewdavey/cassette#436]
I'm trying to have my dependencies automatically picked up by Cassette, but when I `@reference` a css (or less, for that matter) file in a less file at least (haven't tested my scripts yet) I get a bundle rebuild exception (just including inner exception):

```
{"Reference error in \"~/assets/styles/login.less\", line 1. Cannot find \"~/assets/styles/normalize.css\"."}
```

My CassetteConfiguration contains the following line:

```
bundles.Add<StylesheetBundle>("~/styles/login.css", "assets/styles/login.less");
```

My login.less file has `// @reference normalize.css` at the top (which is spelled correctly and located in the same folder as `login.less`).

My login.cshtml has:

```
@using Cassette.Nancy
@{
    Bundles.Reference("~/styles/login.css")
}
<head>
    <!-- Various and Sundy Headers, Code and valid html -->
    @Bundles.RenderStylesheets()
</head>
```

I can make it work by manually listing normalize in the call to `bundles.Add<T>`:

```
bundles.Add<StylesheetBundle>("~/styles/login.css", "assets/styles/normalize.css", "assets/styles/login.less");
```

But that means any time I want to add a file I'm going to have to restart my server entirely, which doesn't feel like it's how Cassette is supposed to work.

Am I missing something, or doing something wrong?  I tried posting in the Google Group for help first, but thus far I'm the only viewer of that item.

**Comment by Crisfole** [comment]
Environment Details:

```
Cassette 2.4.0.18555
Cassette.Nancy 2.1.1.28682
Cassette.LessJs 1.0.0.2 (Note, the same error happens w/ Cassette.Less, whatever version NuGet installed yesterday)
```

Target Framework: .NET 4

In a Windows 7 x64 VM on Ubuntu x64 13.10

**Comment by andrewdavey** [comment]
The overload of `Add` you're using stops Cassette from intelligently looking for referenced assets.

Instead, try something like:

```
bundles.Add<StylesheetBundle>("~/styles");
```

Anything in the `styles` directory will be bundled and the references will be used to order the assets.

**Comment by Crisfole** [comment]
My directory structure looks like this:

```
MyAppProject
      assets
          styles
              //some common files
              //login.less
              //app.less
```

I want login.less and app.less (only) to be accessible from the urls: `/styles/login.css` and `/styles/app.css`.  The overload of Add I was using allowed me to name the bundle something completely different which showed up correctly in Release mode.  Is there some way to Add each file individually and also choose the url?

**Comment by Crisfole** [comment]
I just tried directly `Add`ing ~/assets/styles/login.less and still got the same error, so I'm not sure what's going on there...

**Comment by Crisfole** [comment]
As a side note, when I just add "~/assets/styles" and then reference login.less in my page, I get every file in the directory, even ones that aren't referenced by login.less.  I don't want the application css showing up in my login screen because there's no point and it's just clutter....

**Comment by Crisfole** [comment]
I restructured my stylesheet directory so I could use AddPerSubDirectory.  Now it works ok, but @references from my base file aren't being picked up: base/base.less contains a line `// @reference normalize.css`.  login/login.less contains an @import of `../base/base.less`.  The normalize.css file isn't being added (although all my less stuff seems functional).

**Comment by Crisfole** [comment]
Directly adding `// @reference ../base/normalize.css` pulls in the whole base directory including my mixins and variables files as well as my base.less file which is simply @include-ed in login.less...Not what I'd expect either.

Is there a different way you'd like me to report these things, which aren't necessarily errors in your work, but just ways that someone who's been exposed to other package managers are likely to misunderstand Cassette?

**Comment by andrewdavey** [comment]
A directory per bundle is the way I organise things, and I recommend that approach to keep things simple.

The difference between `@reference` and `@import` can be tricky. I don't use `@reference` very much in LESS files. Only use it when the order of the CSS rules matter.

If you have common variables and mixins to use in multiple files, then use `@import`. Keep those variable and mixin files pure i.e. containing no rules, so they can be imported into many files without duplication in the output.

It may be that Cassette isn't a good fit for what you're trying to achieve. Perhaps try posting to the Cassette Google Group with a more detailed description of your project layout and desired bundling behaviour. I don't have much time to handle issues like this, but some other Cassette users may have more ideas based on their own work.

**Comment by Crisfole** [comment]
Alright, thanks. Appreciate that you got back to me.
