### ISSUE TITLE
MSBuild Task bundle building

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#48]
Create MSBuild task to allow bundle building at compile-time.

Should generate the equivalent of the bundle cache (xml manifest + .bundle files).

Will probably need to enhance start-up code to skip cache validation and generation.

**Comment by mickdelaney** [comment]
This is one for me defo.

**Comment by nazjunaid** [comment]
+1

**Comment by andrewdavey** [comment]
This is now implemented. Documentation is only in the form of an example application https://github.com/andrewdavey/cassette/tree/master/examples/Precompiled

Let me know if you have any questions about this :)
