### ISSUE TITLE
Default modules

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#5]
The current default is for each sub-directory of "scripts", "styles", "htmlTemplates" to be a module.
This is confusing for new users, especially when it comes to stylesheets.

An alternative default is to treat the entire web application as a single module. So the default path is "~/" for each asset type.

This would be simpler for small web applications. More complex apps can always edit the web.config for more advanced module definitions.

**Comment by sfmskywalker** [comment]
Could be handy, lthough personally I love using the modules setup, even though I'm a new user :)

**Comment by andrewdavey** [comment]
v0.5.3 treats the entire application root directory as a single module.

This can the be overridden in web.config to restore the previous, more complex behaviour, using:

```
<cassette>
  <scripts>
    <add path="scripts/*"/>
  </scripts>
  ...
</cassette>
```

**Comment by sfmskywalker** [comment]
Great :)

FYI: I just installed Cassette via NuGet a few minutes ago, and I'm receiving version 0.5.2.

**Comment by andrewdavey** [comment]
Cassette 0.6 now treats the entire application as a single module by default.
