### ISSUE TITLE
Unable to disable cassete's handling of images

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#51]
I've tried disabling cassete's handling of images using code bellow

```
modules.Customize<StylesheetModule>(
    module => module.Processor = new StylesheetPipeline
                                                   {
                                                       CompileLess = false,
                                                       ConvertImageUrlsToDataUris = false,
                                                   });
```

I set ConvertImageUrlsToDataUris to false but it still tries to handle images in the project when viewing source I can see lots of the

```
<link href="/resources/styles/common/images/ui-icons_ef8c08_256x240.png?5a3fd02264b7d5d6ed8b22ad7de42e0859997bff" type="text/css" rel="stylesheet"/>
```

type tags on the page.

**Comment by andrewdavey** [comment]
Hmm, so it's rendering the images of the stylesheet into the HTML as `<link>`s? Sounds broken, I'll look into that ASAP.

**Comment by andrewdavey** [comment]
This was caused by the module source not specifying a `FilePattern` to restrict to types of files found.
e.g.

```
modules.Add(new DirectorySource<StylesheetModule>("Content") { FilePattern = "*.css" });
```
