### ISSUE TITLE
Referencing external fallback JavaScript in modules

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#56]
I've added jquery as an ExternalScriptModule like so

```
modules.Add(new ExternalScriptModule("jquery", "//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js", "!window.jQuery", @"resources\scripts\jquery\jquery-1.6.2.js"));
```

However I get error Reference error in "slider.js", line 1. Cannot find "~\resources\scripts\jquery\jquery-1.6.2.js". when my JavaScript files reference jquery. If I add jquery as a module then cassette will output both the module and the external reference.

**Comment by nazjunaid** [comment]
I've actually found a way to work around this issue which is by specifying a location for jquery which I don't render.

Example.

```
modules.Add(ScriptModule(@"resources\scripts\jquery", "Hidden"));
```

```
private static DirectorySource<ScriptModule> ScriptModule(string path, string location = null)
{
     var directorySource = new DirectorySource<ScriptModule>(path) { FilePattern = "*.js" };

     if (location != null)
         directorySource.CustomizeModule = x => x.Location = location;

     return directorySource;
}
```

**Comment by andrewdavey** [comment]
I'm working on the external module support at the moment. The old code just stuffed the fallback URL into the page. It didn't go through the asset pipeline at all. The new code is fixing this. Stay tuned :)

**Comment by nazjunaid** [comment]
Cool :D

**Comment by andrewdavey** [comment]
Recent code in master supports a more advanced `module.txt` format.

```
[external]
url = http://mycdn.com/jquery.js
fallbackCondition = !window.jQuery # optional - fallback condition

[assets] # assets section specifies the fallback assets
jquery.js # in same folder as this module.txt file

[references] # optional references section
~/any/other-module
```

The fallback assets will be treated like assets of any other module (processed with the pipeline, cached, etc).

In your `CassetteConfiguration` treat this module just like any other module folder. So it can be picked up by `DirectorySource` or `PerSubDirectorySource` along with your non-external modules.
