### ISSUE TITLE
Multiple ICassetteConfiguration (one for each MVC Area)

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#60]
I have an ASP.NET MVC project consisting of multiple Areas, each seperated into its own project.
I thought I'd configure Cassette per Area to maintain modularity. However, only the CassetteConfiguration class in the root gets executed.
Is it somehow possible to have Cassette execute all classes that implement ICassetteConfiguration from different assemblies?

**Comment by andrewdavey** [comment]
Cassette currently calls the first implementation it finds. Allowing multiple configurations to run is certainly feasible. The order would be non-deterministic (based on whatever Assembly.GetTypes returns). I hope that'll be okay?

**Comment by sfmskywalker** [comment]
That'd be simply awesome! That way I can package my Areas as standalone modules, including its Cassette configuration. I think the order won't matter at all, since Cassette will know in what order the assets should be rendered based on the references within each asset / module.txt.

One minor annoyance might be that even though my areas will be modular, most assets will have a dependency on shared libs like jquery. Although it works using relative paths from my Areas' assets to these shared assets of the main project, it's not verry pretty.

What do you think if we were somehow able to reference assets (or perhaps asset modules) by name? For exampe, I have defined the "jQuery" asset using some new Cassette provider API method.
Now, from my CassetteConfiguration in my Area, I have a "app-specific-widgets.js" file with a dependency on the jquery library. From this "app-specific-widgets.js" file, I would normally reference jQuery using a path like: "/// reference path="../../../scripts/lib/jquery.js"" 
But instead, I would like to simply reference the name of the asset: /// reference asset="jQuery"  so that I could redistribute my Area to other MVC projects, who will also provide me with a jQuery asset, but my Area wouldn;t care in what folder.
This would also allow me to freely move my own javascripts in my Areas around without having to know what the relative path to the main project's shared assets are. 

Of course, the main project will have to register the shared assets. Or possibly even more logical, another Area with the sole purpose of providing shared assets could register these.
Then my main MVC application will be a set of Areas acting as modules, where each Area can have a dependency on other Areas (such as a "jQuery" Area)

For modular MVC apps this I think such an update would be really useful.

**Comment by andrewdavey** [comment]
Tip: surround inline XML in back ticks. For blocks, new line, new line, triple back tick, newline, code..., newline, triple back tick :)

**Comment by andrewdavey** [comment]
That would be a nice feature. Cassette would need some notion of "search paths" rather than just checking from current directory. That may need to be a 2.0 feature, but I'll keep it in mind.

Out of interest, how are you "packaging" areas?

**Comment by sfmskywalker** [comment]
Ah, thanks for the XML back ticks tip :)
Some notion of "search paths" would be nice indeed. So we're talking about 2 updates: the ability to load multiple CassetteConfigurations, and "search paths". With regards to the first enhancement, for now I can load the Areas CassetteConfiguration classes myself from within the "main" CassetteConfiguration.

Packaging areas in my definition is nothing more than simply x-copying some reusable Area and pasting it into the Areas folder of some project. Currently I'm just using it for a backoffice application for a client (by the way, ever heard of DigiNotar? ;) with extensibility features, where each module is represented by an Area. This area gets discovered dynamically on Application_Start by the MVC application.
It's also possible to embedd assets as compiled resources, providing a default set of views for example. Also, the Area could be pacakged using Nuget. Orchard CMS uses this technique, and I'm quite inspired by that framework.

**Comment by andrewdavey** [comment]
Issue created for search paths: https://github.com/andrewdavey/cassette/issues/62

I'd not heard of DigiNotar before.
Dynamic Area discovery sounds cool.

Another option to avoid lots of "../../.." noise is using the app-root form of paths (by starting them with "~"). Then rely on a convention of always putting your common scripts in the same location e.g. "~/areas/common/jquery.js"

**Comment by sfmskywalker** [comment]
Search paths would be cool, but I'd definitely like using app-root form of paths ("~/areas/common/jquery.js") as you suggested.
If I had to vote which one to do first, I'd vote for this one :)

**Comment by andrewdavey** [comment]
To be clear, using "~/" paths should work already. Let me know if it's broken :)

**Comment by andrewdavey** [comment]
Latest in master now supports multiple configuration classes.

**Comment by sfmskywalker** [comment]
Oh! I must have missed that while reading the docs.
Awesome, I will try out the multiple ICassetteConfiguration implemenations.
One thing I noticed from reading the check-ins: it looks like the EmptyConfiguration exception is no longer thrown when there are no ICassetteConfiguration implementations, since you now simply return a list. But you're probably checking for an empty list from the calling method. I'll just try it out. Thanks for the update!
