### ISSUE TITLE
External modules should always use fall-back when debug

### ISSUE THREAD

**Issue by nazjunaid** [andrewdavey/cassette#65]
Firstly thanks for the great work with the external modules in Cassete 0.7. 

In 0.6 I was able to always use the fall-back when debugging as sometimes you need to step through unminized jquery to understand what's going on.

eg.

```
    @if (ViewBag.IsDebug == true)
    {
        <script src="@Url.Content("~/resources/scripts/jquery/jquery-1.6.2.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/resources/scripts/jquery.ui/jquery-ui-1.8.15.js")" type="text/javascript"></script>
    }
    else
    {
        Assets.Scripts.Reference("jquery");
        Assets.Scripts.Reference("jquery-ui");
    }
```

Now since these external modules are handled much better by cassete the workaround above doesn't work for me.

Will it be possible to have cassette always use the fall-back on debug?

**Comment by andrewdavey** [comment]
You're very welcome! :)

Yes, this would be a very useful feature. I'm keen to keep Cassette's output as debug friendly as possible.
I suppose making this the default behaviour would be nice. I can perhaps add a setting on ICassetteApplication to control it if needed.

**Comment by andrewdavey** [comment]
Latest in master now supports this. When in debug mode (`ICassetteApplication.IsOutputOptimized = false`) and external module has fallback assets, then simple script elements are rendered into the page.

Switching to release mode changes to using the external URL, plus conditional document.write, as before.

**Comment by nazjunaid** [comment]
Thanks, I've tested it seems to work.
