### ISSUE TITLE
Passing data into page script

### ISSUE THREAD

**Issue by andrewdavey** [andrewdavey/cassette#66]
It's common to need server generated values in script. This usually manifests in the view as something like:

```
<script>
MyApp.foo = "@ViewBag.Foo";
MyApp.bar = "@System.Configuration.AppSettings["bar"]";
</script>
```

It gets very tempting to start splicing server data all over the place in scripts. This is bad. It makes it hard to extract those in-line scripts into their own files.

Cassette can provide a better approach.

```
@{
    Assets.Scripts.PageData("MyApp", new
    {
        foo = ViewBag.Foo,
        bar = System.Configuration.AppSettings["bar"]
    });
    // ... other asset references here...
}
<!doctype html>
<html>
...
@Assets.Scripts.Render()
```

This will create the in-line script element that assigns the data.

An added benefit is proper JSON serialization of the data, so things like arrays and complex objects can be passed to the page. Strings are also escaped correctly.

**Comment by ChrisMH** [comment]
Interesting idea.  I would typically grab this kind of data with an AJAX call or by emitting some kind of javascript init function containing the data that I wanted available to the page.  I would probably stick with one of these methods because it's clearer to me when debugging where the data came from (i.e., in my Javascript, I'm not using some "magic" global value that I have to track down and maintain).

I'm sure others have different opinions.

I'm sure you're planning to, but make sure to namespace appropriately.

**Comment by andrewdavey** [comment]
A common use case is the controller action needing to pass data into the page for use by the scripts. For example, URLs to use, configuration data and other static-ish data which you don't want littered throughout the actual scripts.

Emitting a javascript init function with the values spliced in is exactly what Cassette will be doing for you. The following:

```
@{
    Assets.Scripts.AddPageData("MyApp", new {
        foo = ViewBag.FooData,
        items = new[] { 1,2,3 }
    });
}
<html> ....
```

will generate, (when `Assets.Scripts.Render()` is called):

```
<script type="text/javascript">
(function(){
var MyApp = window.MyApp || (window.MyApp = {});
MyApp.foo = "foo data";
MyApp.items = [1,2,3]
}());
</script>
```

I think this is a neater approach than scattering data insertion snippets throughout other inline scripts in the page.

Of course if you're doing anything clever with ajax, etc, then this won't be for you :)

**Comment by andrewdavey** [comment]
Cassette now supports both "Inline" and "PageData" scripts.

```
@Assets.Scripts.AddInline("alert('hello');");
@Assets.Scripts.AddPageData("SomeGlobalVariable", new { foo = "test", bar = 123 });
```

this will generate

```
<script type="text/javascript">
alert('hello');
</script>
<script type="text/javascript">
(function(){
var SomeGlobalVariable = window.SomeGlobalVariable || (window.SomeGlobalVariable = {});
SomeGlobalVariable.foo = "foo data";
SomeGlobalVariable.items = [1,2,3];
}());
</script>
```

**Comment by dotnetchris** [comment]
Is this possible to be used with modules that it gets combined directly into the module.js output?

**Comment by andrewdavey** [comment]
The script HTML is generated along with the other scripts referenced by the page. However, it is an inline script, not a downloaded resource.

**Comment by dotnetchris** [comment]
Right, I'm saying it would be a good feature (or option atleast) for it to treat it as if it truly was part of the module and append it to the start of the module probably, if it was invoked liked

  Assets.Scripts.Reference("Scripts/Global").AddPageData("SomeGlobalVariable", new { foo = "test", bar = 123 });

**Comment by andrewdavey** [comment]
That could be interesting. It's like an asset of the module then - perhaps useful for inline data which may actually be defined in the config, for example, not in the page.

Having the `AddPageData` call after the reference may be a little confusing, if you want the data before the other scripts.
Currently, you would do something like:

```
Assets.Scripts.AddPageData("SomeGlobalVariable", new { foo = "test", bar = 123 });
Assets.Scripts.Reference("Scripts/Global");
```

Cassette knows to retain the in-page order of these two 'modules'.
