### ISSUE TITLE
Support for SCSS/SASS + Compass

### ISSUE THREAD

**Issue by mickdelaney** [andrewdavey/cassette#67]
Has there been any consideration given to supporting the above for CSS. 
saasandcoffee is adding compass support soon so could probably look to 
leverage how paul betts has achieved it..

**Comment by andrewdavey** [comment]
SCSS/SASS support is definitely something I want added to Cassette. I'll be taking a close look at sassandcoffee for ideas :)

**Comment by sfmskywalker** [comment]
+1 for me. A recent update to the Mindscape Workbench add-in causes the T4 template to generate 2 .css files from a .scss file: a .css file and a .min.css file. Cassette includes both files. Configuring Cassette with the FilePattern = "*.min.css" still includes the normal .css files. The best solution I think would be to be able to tell Mindscape Workbench to stop generating 2 files and have Cassette understand .scss.

**Comment by sfmskywalker** [comment]
Please ignore my comment that Cassette includes *.css even though I set: *.min.css. Cassette nicely does what it is told. Just make sure you build your project when you change a .cs file... duh :)

**Comment by audionerd** [comment]
+1 for SCSS + Compass support.

**Comment by Ridermansb** [comment]
+1 for SCSS + Compass support.

**Comment by andrewdavey** [comment]
It seems that SassAndCoffee's core and ruby packages (required for Sass compilation) may do the trick. I hope they can be made to play nice with Cassette's file system abstraction. It would be very handy to simply add them as dependencies, rather than hack apart their source :)

**Comment by andrewdavey** [comment]
Cassette v1.2.0 beta1 has support for Sass by using SassAndCoffee's core packages. To install the pre-release package:

```
Install-Package Cassette.Web -Pre
```

**Comment by audionerd** [comment]
@andrewdavey Very cool!

**Comment by kamranayub** [comment]
This is gonna be awesome. I wish there was an easy way in Mindscape to tell it to shut up and not generate CSS files now. 

Technically I think having Cassette use Mindscape's generated CSS is still better, though, as far as performance goes, right?

**Comment by andrewdavey** [comment]
Select the sass files in Solution Explorer, hit F4 to open properties window, then clear the Custom Tool property. This will stop Mindscape generating the css.

Performance-wise: you'll have to see what works best for you. They'll probably have similar compile times. So it's a question of when you want to take the hit: on save or on request.

**Comment by andrewdavey** [comment]
Sass support is now in v1.2.0
