### ISSUE TITLE
Allow named regions for Assets

### ISSUE THREAD

**Issue by dotnetchris** [andrewdavey/cassette#70]
There are many times we want to split when the order of script files physically load in browser. Such as ones that handle core layout of the page, vs ones that expect to act on a fully downloaded page.

Assets.Scripts.Render()

From glance seems to only expect to be used in 1 location. I feel it would be very beneficial if cassette had a concept like

``` c#
<html>
  <head>
    Assets.Scripts.Render("First")
  </head>
  <body>
  <div...
  <div...

    Assets.Scripts.Render("Last")
  </body>
```

And something like

``` C#
Assets.Scripts.Reference("scripts/utils/date.js", "First")
```

or even getting fancy with the dynamic keyword

``` C#
Assets.Scripts.First.Reference("scripts/utils/date.js")
```

**Comment by andrewdavey** [comment]
Cassette already supports this. There is an optional parameter called `location` which acts exactly as you have described :)
