### ISSUE TITLE
Cassette stops application from working on anything other than local machine

### ISSUE THREAD

**Issue by dotnetchris** [andrewdavey/cassette#71]
I can't seem to get my application to work anywhere else other than my local machine after integrating cassette. Going to the application url returns the 403 message about directory browsing as if MVC3 didn't load at all. All routes return a 404.

**Comment by andrewdavey** [comment]
Running on IIS 7?

Do you have this in web.config:

``` xml
    <system.webServer>
        <modules runAllManagedModulesForAllRequests="true">
        </modules>
    </system.webServer>
```

**Comment by dotnetchris** [comment]
Modules was not configured that way, but how would it work on my local machine? I did also turn debug=false and saw all the combining work on my local machine.

**Comment by andrewdavey** [comment]
When you run locally are you using the Visual Studio development web server (it's the default)? That doesn't use the `<system.webServer>` settings.

**Comment by dotnetchris** [comment]
Locally was running on full IIS on Win7, deployed was full IIS on Server 2008.

**Comment by andrewdavey** [comment]
The machine-wide configuration for IIS could have `runAllManagedModulesForAllRequests=true` so even when it's missing from the web app's config it gets inherited.

Have you tried deploying a plain asp.net mvc 3 app, without Cassette, to the server? Let's try to narrow down what could be causing the problem.

**Comment by dotnetchris** [comment]
It was an existing MVC3 app, rolling back my deployment put it back online. I haven't tried deploying again but using a different server 2008 machine changing the modules configuration did seem to bring it up.

Also checked machine.config and applicationHost.config on my machine neither seemed to have runAllManagedModulesForAllRequests=true, although is that a AppPool wide setting? I do have multiple applications running under the default website on my local machine some which specify that value.

**Comment by andrewdavey** [comment]
Cassette does use the asp.net routing stuff to add it's custom handlers and also dynamically adds an IHttpModule to support page HTML filtering. So that requires the runAllManagedModulesForAllRequests to be true.

I'm still unsure why it's crashing in the way it is for you though! Let me know if you do manage to reproduce it locally and can attach the debugger.

**Comment by dotnetchris** [comment]
Not having that set seemed to be the entire problem, you probably want to include that config setting in the nuget package.

I do appreciate how quickly you responded in seeking to help, that's very rare.  If you keep a list of sites using your work or similar, http://medicarequoteengine.com has it live now.
