### ISSUE TITLE
GPL licensing without linking exclusion

### ISSUE THREAD

**Issue by dotnetchris** [andrewdavey/cassette#74]
The usage of the GPL license will require me to completely abandon Cassette entirely. The GPL license is completely incompatible with commercial software development as merely linking to Cassette requires me to open source my entire application.

I strongly urge you to either add the linking exclusion to the license or to use the LGPL which differs primarily for offering the linking exclusion.

-- edit I see your licensing page mentions a commercial license but with no further information.

**Comment by andrewdavey** [comment]
The plan is to offer a commercial license for Cassette as well. I've been discussing this option on the Cassette Google Group.
I'll paste the post here:

---

Firstly, my motivation for offering a commercial license is that I enjoy 
working on Cassette and would like to do so more of the time. I write better 
code in the day, not at night after a full day of consulting on client work 
:) So commercial licenses will help fund the continued development of 
Cassette. I also want Cassette to have excellent documentation, website and 
tutorials, so more time is required to create these. 

However, I strongly believe in open source. _So Cassette will remain open 
source and free for non-commercial use_. If a developer wishes to download 
and try out Cassette, I want that to be as easy as _git clone_ or 
_Install-Package Cassette.Web_! 

Therefore I'm looking at a dual-license model. The primary license of the 
code will change to some flavour of GPL. Then my company will offer a 
commercial license, which removes all burdens of the GPL. 
(Non-commercial/charities should be able to ask for free licenses as well if 
they can't use the GPL.) 

The commercial license pricing will be based on the number of production 
servers you are using Cassette on. You can use Cassette as much as you like, 
on any number of computers, for development and testing. 

I think the commercial license price should be around $200 per server. 

Technical support will also be made available. I think the license fee 
should include a couple of support incidents. Then additional support can be 
purchased if required. This gives you priority responses to bug fixes and 
feature requests.

**Comment by andrewdavey** [comment]
Commercial licensing is now available for those who cannot use the GPL:
http://getcassette.net/licensing
