### ISSUE TITLE
File Locking Issues

### ISSUE THREAD

**Issue by ChrisMH** [andrewdavey/cassette#76]
I have run into an issue with cassette locking development problems.  I believe I have solved the issue (pull request incoming).

I have seen it manifest two ways:
1. During development, I occasionally get a web site error page indicating that cassette could not open a file (typically an apparently random .js file, it does not appear to be related to files I am modifying).  Rebuilding and reloading or restarting the web server will sometimes solved this problem, but occasionally I have had to restart my computer.
2. I used a Visual Studio addin to generate .js files from .coffee files.  At times, the generator will start generating additional .js files because, I believe, Cassette has locked the correct .js file.  For example, history.coffee should generate history.js.  But I have seen it generate history1.js, history2.js, etc. until I force Cassette to let go of the file.

Since I made these changes yesterday, I have not seen the issue.

The fix was to set the FileShare parameter appropriately when opening files.

**Comment by andrewdavey** [comment]
Thanks for catching this. It's exactly the kind of real world testing Cassette needs!
I've merged your changes and updated the unit tests to match.
