### ISSUE TITLE
IIS6 HttpModule issue

### ISSUE THREAD

**Issue by ghost** [andrewdavey/cassette#80]
I think this is related since I get this issue since upgrading from 0.6.1 to 0.8.1 via Nuget.

When calling my login page on an IIS6 instance I receive

"This operation requires IIS integrated pipeline mode."

Since this is not supported in IIS6, it appears to be a bug with the way cassette is adding response headers in

See here for more information: http://stackoverflow.com/questions/186548/iis6-httpmodule-this-operation-requires-iis-integrated-pipeline-mode

**Comment by andrewdavey** [comment]
Thanks for reporting the issue. It affects the VS web dev server as well. It should be easy to fix (I hope!)

**Comment by ghost** [comment]
Looks like its the PlaceholderReplacingResponseFilter which is the offender in iis6 (Line 43)

 if (response.Headers["Content-Encoding"] != null)
            {
               // throws Exception here
            }

**Comment by andrewdavey** [comment]
OK, thanks for tracking it down. Are you able to fix and send me a pull request?

**Comment by ghost** [comment]
Hi Andrew

I managed to create a workaround (to be fair your exception message told me what to do :) )

application.HtmlRewritingEnabled = false;

From what Im reading it looks like there isn't a workaround in IIS6 - as they only offer classic integration mode.

Thanks, Mark

**Comment by ghost** [comment]
yeh that pretty much sums it up...
http://msdn.microsoft.com/en-us/library/system.web.httpresponse.headers.aspx

**Comment by andrewdavey** [comment]
Cool, thanks for that link. Good to know for sure!

I'll leave this issue open for now. There may be another way to perform the encoding check without asking for the headers.
I'll see what I can do. Ideally I'd like Cassette to work properly for those poor people stuck on IIS 6 ;)

**Comment by ghost** [comment]
Yeh its a shame theres not a permanent "fix". I'll see if I can find any other way to check for the encoding..

**Comment by andrewdavey** [comment]
Perhaps:
http://msdn.microsoft.com/en-us/library/system.web.httpresponse.contentencoding.aspx

**Comment by ghost** [comment]
Could you use response.ContentEncoding ?
http://msdn.microsoft.com/en-us/library/system.web.httpresponse.contentencoding(v=VS.100).aspx

**Comment by ghost** [comment]
Great minds :)

**Comment by ghost** [comment]
Only other thing I found was this
http://stackoverflow.com/questions/5434858/can-i-detect-if-content-has-been-compressed-in-my-httpmodule

**Comment by andreialecu** [comment]
+1 

I had to switch my project from the VS web dev server to IIS7 because of this as well.

**Comment by sfmskywalker** [comment]
Me too. Normally that would be fine for me, but there's a nasty bug in the Jurrassic dll that sometimes causes a stackoverflow exception when running inside the debugger in combination with IIS Express. In VS WebDev, that problem doesn't exist. So right now I keep my fingers crossed and hope I don't have to use the debugger too much :)

**Comment by andrewdavey** [comment]
Latest in master now has this line:

```
if (HttpRuntime.UsingIntegratedPipeline && response.Headers["Content-Encoding"] != null)
```

I think only IIS7 has the pre-output cache compression magic, (which breaks Cassette's HTML rewriter). So this testing for Integrated Pipeline mode before reading the response Headers should now stop non-IIS7 servers from throwing there.

Can those poor people stuck on IIS6 please test? My quick test using VS WebDev.exe works.

**Comment by ghost** [comment]
ill test now for you

**Comment by ghost** [comment]
Fixes the issue on IIS6 for me ;)

**Comment by andrewdavey** [comment]
Awesome - thanks for testing! I should be updating the nuget package later today or tomorrow. I've got a few more bugs to fix...

**Comment by ghost** [comment]
Pleasure, I meant to get round to helping with the project, just been snowed under with impending deadlines :S

**Comment by herrquark** [comment]
`2.1.0-beta-5` brings this problem back. Now it dies on `Cassette.Aspnet.PlaceholderRewriter.InstallPlaceholderReplacingResponseFilter()`

**Comment by naradae** [comment]
I'm also experiencing this in 2.1.0-beta-6

**Comment by Daniel15** [comment]
I worked around this issue by adding this to my Web.config file:

``` xml
<cassette rewriteHtml="false" />
```

This sets the `HtmlRewritingEnabled` property as mentioned above.

**Comment by herrquark** [comment]
True, but I do want to rewrite my html :(

**Comment by Daniel15** [comment]
Potentially that feature requires the IIS integrated pipeline. Might be difficult getting it working with IIS 6.

**Comment by herrquark** [comment]
It's IIS7

**Comment by Daniel15** [comment]
Are you using the classic pipeline for your app pool? If so, that's basically the IIS 6 "way of doing things" shoehorned into IIS 7. I'd suggest running your app using the integrated pipeline if at all possible. IIS 7 with the classic pipeline has all the same issues that IIS 6 has.

**Comment by herrquark** [comment]
Sorry, just noticed that 2.1.0 (not beta) version was released. This issue is fixed in this version

**Comment by coryrylan** [comment]
I just installed the latest version, running iis8 and net 4.5 ( multiple projects ) and get this error also.
"An ASP.NET setting has been detected that does not apply in Integrated managed pipeline mode."
Ill take a look into it and post anything I find.

**Comment by Daniel15** [comment]
@splintercode  That's a different issue, it means that you have some configuration settings set in Web.config that don't apply in integrated mode. You can add this to the `<system.webServer>` section to suppress the warning:

``` xml
<validation validateIntegratedModeConfiguration="false"/>
```

However, if your app doesn't need to run using the classic pipeline (usually legacy apps that were built for IIS 6), the better fix would be to remove the configuration settings triggering this warning. Generally they're settings in the `<system.web>` (not .webServer) section as some settings in here only apply to IIS 6.

**Comment by fpavlic** [comment]
Did someone get Cassette working on ASP .NET Development Server or is it working only on IIS7+ ?
I tried using v2.2.1 but, above mentioned 'This operation requires IIS integrated pipeline mode.', error occurred.

**Comment by Daniel15** [comment]
@fpavlic Did you try setting `rewriteHtml="false"` in your web.config settings? We've got Cassette working in production in a system that gets hundreds of thousands of hits per month, running on a mixture of IIS 6.0, 7.0 and 7.5. The only tweak I needed to do was turn off HTML rewriting.

I haven't tested using the ASP.NET Development Server but this server does have quite a few limitations so I wouldn't be surprised if it didn't work 100%. Have you considered using [IIS Express](http://www.iis.net/learn/extensions/introduction-to-iis-express/iis-express-overview) instead?

## 

Regards,
Daniel Lo Nigro
http://dan.cx/ | http://twitter.com/Daniel15

**Comment by fpavlic** [comment]
@Daniel15 - as my understanding I have to rewrite html to bundle and minify js scripts via Bundles.RenderScripts(). When rewriteHtml is set to false I don't get this error, but it seems that scripts are not being rendered.
Using IIS7+ or IIS Express is last resort unfortunately.

**Comment by Daniel15** [comment]
As far as I know, you only need rewriting enabled when you're adding references after the `Bundles.RenderScripts()` call. If you add all your references before then, you do not need rewriting enabled. I'm using Bundles.RenderScripts() with rewriting disabled and it's working fine.
