### ISSUE TITLE
Cassette is too aggressive when searching for ICassetteConfiguration

### ISSUE THREAD

**Issue by andreialecu** [andrewdavey/cassette#81]
I've been having various issues in two separate applications I've been trying Cassette in. By reviewing the code, it looks like Cassette loads up every dll in the bin folder and looks for exported types in each of them.

Eventually it runs into a type that needs a dll that isn't there, and I get an error like the following:

```
Could not load file or assembly 'Castle.Core, Version=2.5.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The system cannot find the file specified.

[FileNotFoundException: Could not load file or assembly 'Castle.Core, Version=2.5.1.0, Culture=neutral, PublicKeyToken=407dd0808d44fbdc' or one of its dependencies. The system cannot find the file specified.]
   System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) +0
   System.Reflection.RuntimeAssembly.GetExportedTypes() +122
   Cassette.Web.StartUp.<CreateConfigurationsByScanningAssembliesForType>b__3(Assembly assembly) +13
   System.Linq.<SelectManyIterator>d__31`3.MoveNext() +267
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +148
   System.Linq.<DistinctIterator>d__81`1.MoveNext() +472
   System.Linq.<ConcatIterator>d__71`1.MoveNext() +344
   System.String.Join(String separator, IEnumerable`1 values) +341
   Cassette.Web.StartUp.CreateCassetteApplication() +317
   Cassette.CassetteApplicationContainer`1.CreateApplication() +97
   System.Lazy`1.CreateValue() +12770415
   System.Lazy`1.LazyInitValue() +355
   Cassette.Web.CassetteHttpModule.HttpApplicationPostMapRequestHandler(Object sender, EventArgs e) +99
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +80
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +270
```

Castle.Core is not referenced in my project, I removed it. It probably must be a dependency of some reference I currently have, but it doesn't seem to come with it to the bin folder. My project builds and runs without Cassette just fine.

There should be a better way to handle this, perhaps ignore the error.

I was able to work around it by looking through the code and using:

```
        Cassette.Web.StartUp.CreateConfigurations = () => new[] { new CassetteConfiguration() };
```

Just a heads up though, I've been scratching my head for a while on this error almost giving up on Cassette, and I'm not sure if Cassette.Web.StartUp.CreateConfigurations is documented anywhere.

**Comment by andrewdavey** [comment]
Thank you for reporting this issue. (And not giving up on Cassette just yet!) :)

I'll look into other ways of scanning the assemblies in bin that won't try to load all the dependencies as well. If you have any ideas for this please let me know.

**Comment by andreialecu** [comment]
I'm not very familiar with your code, or the reasoning behind the LoadAssemblies() routine, but maybe you could use  AppDomain.CurrentDomain.GetAssemblies(). 

This should return all the assemblies in use in the appdomain without potentially running into the security risk of loading other dlls that are in the bin folder but not used by the application.

**Comment by andrewdavey** [comment]
Latest in master now uses `BuildManager.GetReferencedAssemblies()`. I think this is what MVC uses to find AreaRegistration classes, so it should work for Cassette too.

Can you try building from master and let me know if it's working for you?

**Comment by kamranayub** [comment]
I am using beta5 and still am getting this (it's trying to load assemblies that aren't in the bin)... is there still a workaround like this?

Edit: I've looked around and I still can't figure out a way to avoid this short of implementing my own module that calls my own derived web host. I would prefer if I could either a) modify the assemblies to ignore or b) specify what DLL(s) to search for ala Ninject and other libraries. Even a simple web.config property to point to the namespace/assembly where the configuration is would suffice.

**Comment by NikGovorov** [comment]
@kamranayub, my workaround for the issue: 

``` C#
// ReSharper disable PossibleNullReferenceException
            ((List<Func<Assembly, bool>>)Type.GetType("Cassette.AssemblyScanner, Cassette", true)
                .GetField("IgnoredAssemblies", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null))
                    .Add(assembly => assembly.FullName.StartsWith("Interop."));
// ReSharper restore PossibleNullReferenceException
```

Run in Application_Start

**Comment by kamranayub** [comment]
Was hoping I could avoid doing that but until that list is made public (that's all I need, really), this will do.
