### ISSUE TITLE
Script references not loaded in correct order

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#82]
When I installed Cassette 0.8.1, my scripts suddenly don't get rendered in the correct order, causing my javascripts depending on jQuery to cause errors (since jQuery is not yet defined).

My Scripts directory looks as follows:

\Scripts
...\Common
......\Lib
.........\jquery.js
......\Site
.........\cssbehaviors.coffee

My cssbehaviors.coffee file has the following reference line:
# reference path="~/scripts/common/lib/jquery.js"

so that Cassette would see that cssbehaviors.coffee has a dependency on jquery.js.
However, when I view the rendered HTML, cssbehaviors.coffee gets rendered before jquery.js.

**Comment by andrewdavey** [comment]
Try referencing like this:

```
#reference "~/scripts/common/lib/jquery.js"
```

Sorry for the lack of docs on this!

**Comment by sfmskywalker** [comment]
Never mind, it was a mistake I made myself. It works now.

**Comment by sfmskywalker** [comment]
#reference "~/scripts/common/lib/jquery.js" works fine, thanks.
Don't worry about the docs, I'm sure that will come, and your incredibly fast response makes it all up.
