### ISSUE TITLE
Font faces not working anymore

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#83]
Somehow my fonts don't work anymore. I use Squirrel to generate a set of font formats, but when using Cassette I only see Times New Roman fonts (which is the default for my app).
I noticed that Cassette replaces url references from within my stylesheet. For example:

url('../fonts/pali1-webfont.ttf')

becomes:

url(/_assets/images/content/fonts/pali1-webfont_ab0c842e0f1cade5945cb708be117e5b22df33c2_ttf)

I'm not sure if this is the cause, but can I somehow disable this css processing?

Thanks

**Comment by andrewdavey** [comment]
Cassette needs to distinguish between image URLs and font URLs.
In the case of fonts I guess it's enough to just rewrite the URL to be domain absolute, but not go through the custom handler. Or I need to write a font handler as well, since it is nice to keep the hash-versioning in the URL if possible.

For now, try something like this to remove the URL expansion step. This may cause broken URLs though...

```
moduleConfiguration.Add(new DirectorySource<StylesheetModule>("style") {
  Customize = module => module.Processor = new StylesheetPipeline().Remove<ExpandCssUrls>()
});
```

I'll come up with a proper fix soon.

**Comment by sfmskywalker** [comment]
I think you're right. Removing the ExpandCssUrls processor fixes the problem.
I agree that it would be nice to keep the hash-versioning in the url, so a font handler would be desirable.
Until then (or until the processor rewrites font urls to absolute urls) I'm happy by removing the ExpandCssUrls processor.

Thanks!

**Comment by andrewdavey** [comment]
Reopened until Cassette behaves correctly with fonts.

**Comment by andrewdavey** [comment]
I've pushed changes to the "font-urls" branch. Can you give that a go please?

It now enables the custom handler to serve images and fonts. So you can keep the URL hash benefits, etc.

If it's working I'll get it merged into master and update the nuget package.

**Comment by sfmskywalker** [comment]
Hi Andrew, sorry for the late response. I just downloaded the main branch (0.8.3), adjusted my CassetteConfiguration classes so that ConvertImageUrlsToDataUris == true and tested it. I see that even though ConvertImageUrlsToDataUris == true, the uris to the fonts remain intact:

```
<link href="/content/css/fontkits.css?ec4425f23c05a059a222f2917ccb370fc323e3f6" type="text/css" rel="stylesheet"/>
```

Source of fontkits.css:

```
@font-face {
    font-family: 'PalindromeSSiRegular';
    src: url('../fonts/pali1-webfont.eot');
    src: url('../fonts/pali1-webfont.eot?#iefix') format('embedded-opentype'),
         url('../fonts/pali1-webfont.woff') format('woff'),
         url('../fonts/pali1-webfont.ttf') format('truetype'),
         url('../fonts/pali1-webfont.svg#PalindromeSSiRegular') format('svg');
    font-weight: normal;
    font-style: normal;

}
```

So I guess that's looking good.

Thanks!
