### ISSUE TITLE
IIS6 If-None-Match issue

### ISSUE THREAD

**Issue by ghost** [andrewdavey/cassette#84]
Hi

Im not sure if this is related to my previous issue: https://github.com/andrewdavey/cassette/issues/80

but on IIS6 with debug=false in web.config, on an IIS6 instance, I get a HTTP Code of 400 (Bad Request) when trying to access the minified module files (js and css)

Strangely this only happens when the Headers has: "If-None-Match: HASH"
where "0ee87c0c1cd56be8fece1e6bdad6d96f00d53c52" is my hash of the file content

I dont suppose this is a known issue and theres a workaround. Roll on my days to use IIS7 is all I can say!

Ta, Mark

**Comment by andrewdavey** [comment]
An error code of 400 usually means the Cassette handlers are explicitly not liking something from the request, rather than a 500 from some other internal exception. I don't have IIS6 here, does it also break using the VS WebDev server?

I'm going to squeeze a Cassette coding session tonight and hunt down some of these bugs. So I should be able to tell you more later.

**Comment by ghost** [comment]
Hi Andrew

Not sure, ill check. its a little odd, as I was constantly hitting F5 to see if I can recreate the issue, and then it goes away. Until I do a Ctrl + F5 (Hard refresh) then I can recreate

Thanks

**Comment by ghost** [comment]
It doesnt appear to be an issue on the VS Webdev server..

**Comment by andrewdavey** [comment]
OK. Can you provide as much error info as possible? e.g. HTTP request and response (Fiddler is usually good for that).

If you're running from Cassette's source, then any debug/stack trace/etc would be useful too.

Thanks.

**Comment by ghost** [comment]
Hi Andrew

Not currently running from Source of Cassette, but heres a fiddler output

GET http://urlofsite/_assets/stylesheets/Content/Styles/core_0ee87c0c1cd56be8fece1e6bdad6d96f00d53c52 HTTP/1.1
Host: dev-urlofsite
Connection: keep-alive
Cache-Control: max-age=0
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.186 Safari/535.1
Accept: text/css,_/_;q=0.1
If-None-Match: 0ee87c0c1cd56be8fece1e6bdad6d96f00d53c52
Referer: http://dev-urlofsite/
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Cookie: .ASPXAUTH=BLAH

IIS6 Response (RAW)
HTTP/1.1 400 Bad Request
Content-Type: text/html
Date: Wed, 28 Sep 2011 14:30:30 GMT
Connection: close
Content-Length: 20

<h1>Bad Request</h1>

**Comment by ghost** [comment]
Found this:
http://blogs.msdn.com/b/mike/archive/2009/02/17/http-400-bad-request-when-client-terminates-request-headers-improperly.aspx

Not sure if its applicable to cassette?

**Comment by andrewdavey** [comment]
This should be fixed. The problem was related to Cassette generating E-Tags not wrapped in double quotes.

Is it working for you in IIS6 now?

**Comment by ghost** [comment]
Yeh it's all working now thanks!
