### ISSUE TITLE
Wildcards in module.txt

### ISSUE THREAD

**Issue by lukebennett** [andrewdavey/cassette#85]
It would be great if you could specify a wildcard (such as *) in module.txt files to indicate all scripts in the current folder that haven't been explicitly referenced in the file. This is for scenarios where you need to make sure one or two particular scripts are included before all others, but the rest can be included in any order

This is a situation I find myself in where I need to ensure jQuery is included before any plugins/scripts that depend on it, though most of those other files can then be included in any order. Unless I'm missing something, it seems the only way I can achieve this is by 1) adding /// references statements to each file (which I'll need to remember to add back in any time they're updated), 2) splitting jQuery into its own module and loading that first (fine in this situation but doesn't scale well), or 3) explicitly referencing every script in a module.txt file with jQuery first (a bit of a faff and something I'll have to remember to maintain every time I add a new file).

By way of example, I envisage module.txt looking something like this:

```
jquery-1.6.4.js
some-custom-script-part-1.js
some-custom-script-part-2.js
*
```

**Comment by andrewdavey** [comment]
This should already work as you have described. Let me know if it's not working.

**Comment by lukebennett** [comment]
Oh ok... you're quite right, it does! I did dig around to see if I could find any reference to this in the docs or the code and couldn't, but must have missed it.

Thanks

**Comment by andrewdavey** [comment]
The docs are certainly missing information about the \* support. I'll try to get that updated soon.
