### ISSUE TITLE
IIS6 returns 404 error for CoffeeScript and CSS files

### ISSUE THREAD

**Issue by catlion** [andrewdavey/cassette#87]
Hi,

Cassette works fine in Cassini and IIS7.5 Classic mode, but when deployed to IIS6 server, every stylesheet and CoffeeScript reference fails with 404 error. Plane JS files are served correctly (see below). I tried the latest build as well as a current Nuget package version.

Generated URLs for JS files are not linked to Cassette handler for some reason:
http://hostname/Scripts/jquery-ui-1.8.16.min.js?d938873d1520f1507b25c0cd7b4c58d2368fa738

While stylesheets and CS are:
http://hostname/_assets/get/Scripts/home.coffee?211be51275bfdf81c6645fc3688b62c3adc256eb
http://hostname/_assets/get/Content/themes/redmond/jquery-ui-1.8.16.css?548c0f31d6274750d31c4e1d3bfb1dc7b6eb8c61

**Comment by andrewdavey** [comment]
Do you have IIS 6 wildcard mapping configured to send all requests to asp.net?

**Comment by catlion** [comment]
Yes, it's an MVC3 web site.
runAllManagedModulesForAllRequests="true" is also present.

By the way, application requires Windows authentication.

**Comment by catlion** [comment]
Sorry, wildcard mapping was missing as you supposed.
