### ISSUE TITLE
HtmlTemplates for Knockout - Error in generated javascript 

### ISSUE THREAD

**Issue by etishor** [andrewdavey/cassette#88]
If the template contains an  apostrophe ( ' ) , it is not escaped in  the generated javascript for the knockout template, causing an error and the template to stop working.

PS: Other than that everything works nicely with the HtmlTemplates :) thanks

**Comment by andrewdavey** [comment]
Thanks for catching this. I'm looking into fixing it now.

**Comment by andrewdavey** [comment]
Just pushed a fix to master.

**Comment by etishor** [comment]
Thanks. I'll let you know if everything is ok after i update.
