### ISSUE TITLE
Customization of ScriptPipeline

### ISSUE THREAD

**Issue by enusbaum** [andrewdavey/cassette#89]
I'm working on implementing Cassette into a project and am running into an issue where the minification library, when enabled, is resulting in invalid Javascript. The MicrosoftJavaScriptMinifier is evaluating the following 'raw' Javascript:

rangeHandles[2].css("height", (100 - high) + "%");

as

a[2].css("height",NaN-e);

The results is entirely incorrect. For practical reasons, I'd rather not muck with the logic of our application via Minification but would still like to take advantage of the concatenation feature. I'm unable via the CasetteConfiguration.cs to come up with a way to customize our JavaScript ScriptModule in a way that would allow for the files to be concatenated, but not minified. I'm not sure if this is just a limitation on my understanding of the library, or limitations in the ScriptPipeline object.

Any help is appreciated.

Thanks!

**Comment by andrewdavey** [comment]
The docs are currently very lacking in this area!

In the configuration class, where you define the scripts module, try something like:

```
modules.Add(
    new PerSubDirectorySource<ScriptModule>("Scripts")
    {
        // ... other properties ... then add this:
        Customize = module => module.Processor = new ScriptPipeline().Remove<MinifyAssets>()
    }
);
```

BTW: It may be worth logging a bug here http://ajaxmin.codeplex.com/ This is what Cassette uses to minify javascript.

**Comment by enusbaum** [comment]
Using the following code, I'm still seeing minified output from Cassette:

```
moduleConfiguration.Add(
                new DirectorySource<ScriptModule>("Javascript/ThirdParty", "Javascript/Internal")
                    {
                        FilePattern = "*.js",
                        SearchOption = SearchOption.AllDirectories,
                        CustomizeModule = module => module.Processor = new ScriptPipeline().Remove<MinifyAssets>()
                    }
                );
```

Thoughts?

**Comment by andrewdavey** [comment]
Is it loading the cached resources?

Make sure the web application assembly version number is incremented. This will clear the cache. (Otherwise Cassette doesn't know you've altered the pipeline and all the asset files are still the same.)

**Comment by andrewdavey** [comment]
Closing this issue because the latest AjaxMin should resolve it.

If you're still having cache bugs please create another issue - thanks.
