### ISSUE TITLE
How to set MEDIA attribute for stylesheet?

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#9]
For mobile devices I want to include certain stylesheets and set the "media" attribute.
Currently I don't see how to do that using Cassette and am forced to usedirectly  the <link> element.

**Comment by andrewdavey** [comment]
This is a missing feature. I would think this needs to be configurable at the module level.

In web.config, something like this perhaps:

```
<cassette>
  <styles>
    <add path="styles/mobile" media="only screen and (max-device-width: 480px)" />
  </styles>
</cassette>
```

?

**Comment by sfmskywalker** [comment]
That would work out great for me, and is consistent with how everything else is configured in Cassette.

**Comment by andrewdavey** [comment]
I'll leave this open, until the feature is implemented.

**Comment by sfmskywalker** [comment]
Great :)

**Comment by andrewdavey** [comment]
In Cassette 0.6, the `StylesheetModule` class has a `Media` property. So it's now a matter of assigning the property in the configuration. A simple example is:

``` csharp
moduleSource.Add(new DirectorySource<StylesheetModule>("styles/mobile")
{
    FilePattern = "*.css",
    CustomizeModule = m => m.Media = "your-media-query-here"
});
```

However, I assume you'd rather use on `PerSubDirectorySource<StylesheetModule>` for _all_ stylesheets and then set the media of a select few modules? So maybe we need to add something like:

``` csharp
/// after adding the module source...
moduleSource.Customize<StylesheetModule>("styles/mobile", m =>m.Media = "etc");
```

**Comment by sfmskywalker** [comment]
Great enhancements with 0.6!

I currently just use the DirectorySource class, but you you're right that I'd rather use the PerSubDirectorySource to save me from explicitly specifying each subfolder under /css.
I didn't realize I could then customize a module afterwards. Now I do :)

Thanks!
