### ISSUE TITLE
Coffeescript & 304 Not Modified

### ISSUE THREAD

**Issue by barclayadam** [andrewdavey/cassette#94]
Andrew,

As our project is getting larger the time it takes to reload pages after edits to JavaScript / CoffeeScript files is starting to become a problem (particularly with IIS 7.5). Whilst investigating the problem I have noticed that CoffeeScript files are not served up as 304 Not-Modified when appropriate.

Although this is a small issue as this only happens when developing (when debug=false 304 headers are correctly served) perhaps something to straighten out?

That, or this is indicative of a bigger problem I am having with caching which is why I'm seeing the compilation of files take >1 min?

Thanks,
Adam

**Comment by andrewdavey** [comment]
Hi Adam,

I've noticed this as well on projects with a lot of CoffeeScript. I'm sure the debug-mode performance can be drastically improved. I'll be looking into this asap.

**Comment by barclayadam** [comment]
A little more investigation and it seems this issue raises its head a lot more when using IIS7.5, as opposed to IIS Express.

Quick, very non-scientific test that involved changing a single line in a JS file (not touching any CoffeeScript files) shows that IIS 7.5 on reload will take about 2.1 minutes. Using IIS Express the same change and reload was just south of 10 seconds. Subsequent reloads in IIS7.5 are fine if no files change.

At the moment I cannot see what the difference between the two is. I have nothing esoteric set-up in IIS (point a new website to the same folder path and do nothing else).

Thanks,
Adam

**Comment by andrewdavey** [comment]
It might also be useful to run Fiddler (or some other traffic logger) and look at the HTTP requests/responses.

**Comment by barclayadam** [comment]
Inspecting traffic using Fiddler shows nothing obvious that I can see.

All request / responses are essentially the same, with the exception that a reload on IIS 7 takes 41 seconds, IIS Express about 1.5s.

The only small difference I see in responses is IIS Express is adding 'Vary: Accept-Encoding' as a response header, plus the usual X-SourceFiles debug header.

**Comment by andrewdavey** [comment]
v0.9 now sends a 304 status code. It uses the file hash as the E-Tag.

Please note that 0.9 has breaking changes. The migration guide is here:
http://groups.google.com/group/cassette/browse_thread/thread/d0e8ab14c9d54a22

Let me know if you have any problems.
