### ISSUE TITLE
Problem with HtmlTemplates

### ISSUE THREAD

**Issue by lafourmirouge** [andrewdavey/cassette#96]
On some page i've 801f9413-8c72-4741-a656-bc79898dbf76 code instead of my script with Jquery or KnockOut HTMLTemplate.

**Comment by andrewdavey** [comment]
It sounds like the HTML rewriting is not happening on that page.

Is that page special in some way? Is it the result of a redirect or server.transfer?

**Comment by lafourmirouge** [comment]
Andrew, thank you for your answer.
I use version 0.9 but I had seen this problem on version 0.8.
It is not a result of a redirect or server.transfer, is a dynamic page and the problem still appears with particular parameters.
Is there a way to see a debug trace of this problem ?

**Comment by lafourmirouge** [comment]
Ok, i found a solution when i put @Bundles.RenderHtmlTemplates() in my head it's ok now ! But when @Bundles.RenderHtmlTemplates() is just before my end body in the footer on my page the problem appears again.

**Comment by andrewdavey** [comment]
Does your web application install any filters by assigning Response.Filter ?

Cassette installs a filter to rewrite the HTML and I'm wondering if it's
not getting called for some reason.

There aren't great diagnostics in Cassette yet - this is something I'm
working on improving...

**Comment by lafourmirouge** [comment]
No I do not use any filters by assigning Response.Filter
In any case it works very well like that now, if I see this problem again I'll let you know.
A big thank you for your work !
