### ISSUE TITLE
Invalid operation when bundle assets are not concatenated into a single asset

### ISSUE THREAD

**Issue by lafourmirouge** [andrewdavey/cassette#97]
When i've use settings.IsDebuggingEnabled = false.
If I'm in debug mode no problem.

**Comment by andrewdavey** [comment]
I can't reproduce this on my machine. What happens if you remove the `settings.IsDebuggingEnabled = false;` line and instead try switching `debug="false"` in Web.config `<system.web>/<compilation>`?

Are you able to zip up a project that reproduces the error and email it to me andrew@equin.co.uk ?

**Comment by lafourmirouge** [comment]
Same problem when i put debug=false in web.config ...

[InvalidOperationException: Invalid operation when bundle assets are not concatenated into a single asset.]
   Cassette.Bundle.RequireSingleAsset() +158
   Cassette.Bundle.get_Hash() +31
   Cassette.Persistence.BundleCache.CreateBundleElement(Bundle bundle, IBundleContainer bundleContainer) +314
   Cassette.Persistence.<>c__DisplayClass23.<SaveContainerXml>b__22(Bundle bundle) +52
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +85
   System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) +309
   System.Xml.Linq.XContainer.AddContentSkipNotify(Object content) +228
   System.Xml.Linq.XElement..ctor(XName name, Object[] content) +22
   Cassette.Persistence.BundleCache.SaveContainerXml(IBundleContainer bundleContainer) +653
   Cassette.Persistence.BundleCache.SaveBundleContainer(IBundleContainer bundleContainer) +80
   Cassette.Configuration.CachedBundleContainerFactory.Create(IEnumerable`1 unprocessedBundles, CassetteSettings settings) +243
   Cassette.CassetteApplicationBase.CreateBundleContainer(IEnumerable`1 bundles, CassetteSettings settings, String cacheVersion) +186
   Cassette.CassetteApplicationBase..ctor(IEnumerable`1 bundles, CassetteSettings settings, String cacheVersion) +68
   Cassette.Web.CassetteApplication..ctor(IEnumerable`1 bundles, CassetteSettings settings, CassetteRouting routing, Func`1 getCurrentHttpContext, String cacheVersion) +43
   Cassette.Web.StartUp.CreateCassetteApplication() +1040
   Cassette.CassetteApplicationContainer`1.CreateApplication() +106
   System.Lazy`1.CreateValue() +361
   System.Lazy`1.LazyInitValue() +104
   System.Lazy`1.get_Value() +89
   Cassette.CassetteApplicationContainer`1.get_Application() +35
   Cassette.Web.StartUp.<PostApplicationStart>b__0() +31
   Cassette.Web.CassetteHttpModule.HttpApplicationPostMapRequestHandler(Object sender, EventArgs e) +126
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +148
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +75

it worked when I was in 0.8 and below, since i use Bundles instead of Assets.

**Comment by andrewdavey** [comment]
Can you paste in your CassetteConfiguration.cs class?

**Comment by lafourmirouge** [comment]
public class CassetteConfiguration : ICassetteConfiguration
    {
        public void Configure(BundleCollection bundles, CassetteSettings settings)
        {
            settings.IsDebuggingEnabled = true;

```
        bundles.Add<StylesheetBundle>("Skin/css");
        bundles.AddPerSubDirectory<ScriptBundle>("Scripts/Libs");
        bundles.AddPerSubDirectory<ScriptBundle>("Scripts/App");


        bundles.AddPerSubDirectory<HtmlTemplateBundle>(
            "HtmlTemplates/KnockOutTemplate"
            , bundle => bundle.Processor = new KnockoutJQueryTmplPipeline()
            );

        bundles.AddPerSubDirectory<HtmlTemplateBundle>(
            "HtmlTemplates/JqueryTemplate"
            //, bundle => bundle.Processor = new JQueryTmplPipeline()
            );
    }
}
```

For now I have a bug with JQueryTmplPipeline, that's why it's commented out, I use to be so HtmlTemplatePipeline default, KnockoutJQueryTmplPipeline works perfectly.

Since version 9 on my test server when I change a CSS it does reflect the change only when I recycle the pool is not very practical.

Thank you for your work anyway!

**Comment by andrewdavey** [comment]
I need to fix `HtmlTemplatePipeline`. It's not concatenating assets!

**Comment by lafourmirouge** [comment]
HtmlTemplatePipeline works fine yet. FYI I updated to 9.3.

**Comment by lafourmirouge** [comment]
I switched to version 9.4 and the problem "Invalid operation" in release mode is solved ! :)
I still have the problem of changing the CSS once online, only a recycle site updates

**Comment by lafourmirouge** [comment]
sorry with debug=false on online server CSS update change ...
