### ISSUE TITLE
Cassette does not find default configuration

### ISSUE THREAD

**Issue by kekonn** [andrewdavey/cassette#98]
I added Cassette through NuGet to an MVC 3 web app and it seems to completely ignore the code I added to the default configuration class. 

I added the following line `bundles.AddPerSubDirectory<ScriptBundle>("Scripts",true);` which I interpretred as "make a module per subfolder of /Scripts but when I say `Bundles.Reference("validation")` with validation being a subfolder of /Scripts it says it cannot  find a bundle with /validation in the path.

Also, when I put a breakpoint in the configuration class it does not break, which further proves my theory.

**Comment by andrewdavey** [comment]
Try using the application relative path to the folder e.g. `Bundles.Reference("Scripts/validation");`

The configuration class is only executed the first time the application starts. Either stop the web server and re-run your application (or just modify Web.config) to cause an app restart.

**Comment by kekonn** [comment]
That did it. I also noticed a weird thing: when I use `Bundles.Reference("validation")` it throws an exception, but when I add them by hand it actually does break in the configuration class. This seems to suggest that the point at which it is run is not optimal?

**Comment by andrewdavey** [comment]
I'm not sure what you mean by "when I add them by hand".

However, when in debug mode, Cassette will watch the file system for file addition and change events. They cause the Cassette infrastructure to re-initialize, which re-runs the configuration class. So perhaps you were seeing that happen?

**Comment by kekonn** [comment]
I mean that I reference all the JS files individually. The file system itself does not change at that time.
